### ISSUE TITLE
npm global code-server mod

### ISSUE THREAD

**Issue by si458** [linuxserver/docker-mods#144]
i have created a mod which is very handy for code-server

its simply sets the NPM global folder to inside /config which is very helpful between container deletes/restarts/migrates

https://github.com/si458/docker-mods/tree/code-server-npmglobal

**Comment by aptalca** [comment]
Thanks. Just had a quick look over. The sed will repeatedly add the path line to the service run every time the container is restarted: https://github.com/si458/docker-mods/blob/code-server-npmglobal/root/etc/cont-init.d/98-npmglobal#L12

**Comment by si458** [comment]
Hi @aptalca, this is correct because every time to container restarts, it has to load the mods again
ive verified this with kubernetes so in turn loads mine again to make sure the global npm folder is set inside `/config`

**Comment by aptalca** [comment]
You're confusing container restart and recreation. Your script is resulting in duplicate lines in the service run when the container is restarted.

**Comment by si458** [comment]
@aptalca oh ok? erm im not sure then? im not sure how to trigger a restart in kubernetes? i just normally scale to 0 then 1 ?
this works perfectly fine for myself but i will keep trying

**Comment by aptalca** [comment]
Just use docker run in your local testing/dev

**Comment by si458** [comment]
@aptalca thank you!
fixed it!
all ok now?

**Comment by aptalca** [comment]
looks good, thanks.

You can PR to this branch: https://github.com/linuxserver/docker-mods/tree/code-server-npmglobal

**Comment by aptalca** [comment]
thanks

deployed: https://mods.linuxserver.io/?mod=code-server
