### ISSUE TITLE
Plex scanner and agent mod

### ISSUE THREAD

**Issue by ksurl** [linuxserver/docker-mods#147]
requesting new branch `plex-absolute-hama` for PR

**Comment by aptalca** [comment]
Link?

**Comment by ksurl** [comment]
oops, here it is: https://github.com/ksurl/docker-mods/tree/plex-absolute-hama

**Comment by aptalca** [comment]
Looks good, you can PR here: https://github.com/linuxserver/docker-mods/tree/plex-absolute-hama
