### ISSUE TITLE
Issue with Docker Hub API rate limits

### ISSUE THREAD

**Issue by Dids** [linuxserver/docker-mods#160]
Since Docker Hub now applies more aggressive rate limiting, applying docker mods can fail, even if using ghcr.io, because of the API call(s) to Docker Hub's API.

Are there currently any plans or work being done regarding this? As I'm not sure if the plan is to move entirely to ghcr.io, or keep using/supporting both registries?

One way to potentially solve this would be to expose an env var to override the token used for authentication, as the "anonymous" token is very easily rate limited and there's currently no error handling in place to even detect this.

**Comment by Roxedus** [comment]
Do you pull the mod from ghcr too? (this is done automatically for our mods)

**Comment by Dids** [comment]
Sorry, should've mentioned that I've been testing with a custom Docker Mod, but have narrowed it down to the API rate limiting.

I'm currently pushing the mod to both Docker Hub and ghcr.io, but regardless of which one I specify in the `DOCKER_MODS` environment variable, the error seems to be the same (layer extraction fails, because of the unexpected rate limit response).
Not sure if both registries are rate limiting one of my servers, or if the mod loading script is somehow still calling the Docker Hub API for ghcr.io images (or even if ghcr.io actually proxies some API requests to Docker Hub).

**Comment by Roxedus** [comment]
Could you share some logs of when it is happening? Cant really see anything obvious with the logic

**Comment by Dids** [comment]
There's not much there, other than this:
```
gzip: stdin: not in gzip format
```

It fails when trying to download the layer here:
https://github.com/linuxserver/docker-baseimage-ubuntu/blob/bionic/root/docker-mods#L119

I've verified this by adding `set -x` to the `docker-mods` script, running it manually and copying the `curl` request and confirming that it is indeed returning a rate limit error, instead of the layer that it's expecting.

I can keep testing to see if this also happens with ghcr.io, but isn't this a problem nonetheless? Probably not a common one, but as the rate limits are per IP, there could be several scenarios where the rate limits would be hit faster than usual.

In my case this was likely caused by a combination of using watchtower and fleet, plus a dozen or two containers per server.

**Comment by aptalca** [comment]
For our official published mods, it defaults to pulling from ghcr even if it's not defined as ghcr.

For other mods, you can push to ghcr and put in the mood name as `ghcr.io/namespace/modname:tag`

**Comment by mdhiggins** [comment]
I'm getting this same error all the sudden on one of my mods that hasn't been changed recently

```
[mod-init] Applying mdhiggins/sma-mod:latest files to container

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

https://github.com/mdhiggins/sma-mod is the mod. Tried using ghcr.io instead of dockerhub without any improvement

I do notice there was a few recent commits to the docker-mods script in the last few days, not sure if that maybe broke something?

https://github.com/linuxserver/docker-baseimage-ubuntu/commits/bionic/root/docker-mods

**Comment by Roxedus** [comment]
These changes haven't made it to too many images yet, will take about a week to fully propagate down the line.

**Comment by mdhiggins** [comment]
Hm you are correct I verified against the deluge container, in that case I'm not sure why I'm getting this error all the sudden

**Comment by aptalca** [comment]
Changes were made to the docker registry api, necessitating changes on our end, which will propagate over the next week or so
