### ISSUE TITLE
MariaDB Mod for Papermerge

### ISSUE THREAD

**Issue by dafo90** [linuxserver/docker-mods#161]
Can you please create a branch called `papermerge-mariadb` to develop a Mod that adds `libmariadb-dev` package?

**Comment by aptalca** [comment]
Why would that be needed?

**Comment by dafo90** [comment]
Papermerge allows you to use MariaDB (and others Databases) instead of SQLite, but if you try to configure it in this container it fails because `libmariadb-dev` is missing.
I think this feature could be useful especially if you manage this service with many users and documents.

**Comment by tobbenb** [comment]
Why is the dev package needed? Isn't it enough with libmariadb?

**Comment by dafo90** [comment]
Yes, you're right. `libmariadb` is enough.

**Comment by CHBMB** [comment]
Going to close this
