### ISSUE TITLE
[Swag-cloudflare-realip] Mod kills container if it cannot access Cloudflare

### ISSUE THREAD

**Issue by rg9400** [linuxserver/docker-mods#164]
This mod accesses cloudflare's IP page and places them into a file. However, in my case, sometimes my DNS server is not up by the time the Swag container spins up (even if I set Swag to depend on my DNS container). Since this mod runs right away on startup, there is not a huge gap to allow the DNS container to fully spin up.

If it fails to access the website due to DNS resolution errors, it does not actually list out any IPs, and the created file creates a fatal error in nginx -- `nginx: [emerg] invalid number of arguments in "set_real_ip_from" directive in /config/nginx/cf_real-ip.conf:1`.

Ideally, the mod should be able to retry access to the CF page if inaccessible, and maybe if it still cannot access it after a sane number of retries, it has a proper fallback that does not brick the entire container.

**Comment by Roxedus** [comment]
fixable with https://github.com/linuxserver/docker-mods/pull/169
