### ISSUE TITLE
[radarr-striptracks] Unable to test/save script with Sonarr v3 (works with Radarr v3)

### ISSUE THREAD

**Issue by bxlouis** [linuxserver/docker-mods#168]
Sonarr v3.0.4.1098-ls47 by linuxserver.io
Radarr v3.0.1.4259-ls92 by linuxserver.io

When creating a custom script in Sonarr with Settings->Connect, the Test button loads indefinitely. The Save button has the same behaviour. It works like a charm with Radarr, same settings.

I'm calling /usr/local/bin/striptracks-eng-fre.sh. Content below:

`#!/bin/bash`
`. /usr/local/bin/striptracks.sh :eng:fre:und :eng:fre`

**Comment by TheCaptain989** [comment]
This worked for me in the past, let me check into it.

**Comment by TheCaptain989** [comment]
@aptalca, I have a question and I'm not sure where else to ask it.
Does the team have a suggestion on how to organize development and testing for the official mods to your containers?  For example, right now I have a lidarr-flac2mp3 repo that I just updated as kind of a way to dev/test, and I soon plan to merge with the official fork.  However, that's a lot of manual work and I'm not currently doing it this way for the radarr-striptracks project.  There I've been pushing commits straight to the official fork, but limiting the pull requests to your team.
Maybe there's a "GitHub standard" way to do this that you could point me to?  If not, that's fine too.

**Comment by bxlouis** [comment]
Hello @TheCaptain989! 
Were you able to reproduce the issue?
I just tested again on the latest Sonarr 3 version and still not able to add the script.

**Comment by TheCaptain989** [comment]
> Hello @TheCaptain989!
> Were you able to reproduce the issue?
> I just tested again on the latest Sonarr 3 version and still not able to add the script.

Yes, I have reproduced the problem.  I'm now trying to figure out where the issue is.  Thanks for reporting it.

**Comment by aptalca** [comment]
@TheCaptain989 unfortunately we don't currently have a good testing model for these mods. Unlike our regular docker builds, the mods don't push PR builds to a test repo where we can pull from (we should look into adding it, though).

I personally have been either manually copying the init scripts and services into a running container to test locally, or pushing to my personal docker repo so I can do a proper test by pulling from there.

**Comment by TheCaptain989** [comment]
@aptalca, thanks.  I've been using my personal Docker repo the exact same way.  I'll guess I'll keep doing that. :wink:

**Comment by TheCaptain989** [comment]
@bxlouis OMG, what a stupid mess up.  Would you believe it is a numfmt command issue?  Arrgh.
I have an easy fix in the script that I just smoke tested.  Let me run through my other testing for Radarr also and I'll push an update pretty soon, maybe by the weekend.

**Comment by TheCaptain989** [comment]
BTW, sorry it took so long to respond.  I'm going to check my GitHub notification settings...

**Comment by bxlouis** [comment]
Great job @TheCaptain989 thanks for investigating and fixing it!

**Comment by TheCaptain989** [comment]
@bxlouis please try using my test repo (full instructions at link) and let me know how it works:
[thecaptain989/radarr-striptracks](https://hub.docker.com/r/thecaptain989/radarr-striptracks)

**Comment by bxlouis** [comment]
@TheCaptain989 tested this weekend on both Radarr and Sonarr. I did not spot any issue, seems to be working as expected! Thanks!

**Comment by TheCaptain989** [comment]
Great.  I'll review it again briefly and them create a PR for the team.
Thanks again for reporting!

**Comment by bxlouis** [comment]
Hello @TheCaptain989! Were you able to review and create a PR for the team?
Cheers!

**Comment by TheCaptain989** [comment]
I haven't created the PR yet.  I'll do it this weekend.

**Comment by TheCaptain989** [comment]
This issue is closed.
