### ISSUE TITLE
Wrong time shown if f2b Discord mod?

### ISSUE THREAD

**Issue by ICDeadPpl** [linuxserver/docker-mods#175]
I tested the mods:swag-f2bdiscord for the Swag Docker, and got this message in my Discord:
"XXX.XXX.XXX.XXX got banned for 3600 hours after 4 tries."
The jail.local has this  setting:
# "bantime" is the number of seconds that a host is banned.
bantime  = 3600

So shouldn't the mods:swag-f2bdiscord report the time as "3600 seconds" instead of "3600 hours"?

**Comment by Roxedus** [comment]
Fail2Ban is weird regarding this, when you use another variable name, it does a conversion. I have done 2 rewrites of this mod since I added it here, and it always have some quirk like this.

**Comment by emorgoch** [comment]
I'll just mention my experience: I didn't add a bantime variable to my action filter, and it came up in Discord as "got banned for 86400 hours".

**Comment by EVOTk** [comment]
Look the note : 
https://github.com/linuxserver/docker-mods/tree/swag-f2bdiscord#mod-configuration


`action  = discordEmbed[bantime=24]`

```
Action arguments:
bantime(hour) is optional, but defaults to 24 when not set. Just reflects in the message, does not change the ban time
```
