### ISSUE TITLE
Upgrade code-server-php to 8.0?

### ISSUE THREAD

**Issue by accesstechnology-mike** [linuxserver/docker-mods#176]
Current php version for this mod is 7.2, is 8.0+ an option?

**Comment by aptalca** [comment]
Is there even php8 in any ubuntu repos?

**Comment by accesstechnology-mike** [comment]
Not directly. This seems to be the most used repo for adding it:

https://linuxize.com/post/how-to-install-php-8-on-ubuntu-20-04/

**Comment by Wielewout** [comment]
Can be closed.

Separate branch `code-server-php8` is now available for php 8.0.
