### ISSUE TITLE
Apprise mod fails to build cryptography

### ISSUE THREAD

**Issue by TheSpad** [linuxserver/docker-mods#177]
Apprise mod fails to build cryptography due to missing Rust requirement.

**Comment by caronc** [comment]
I also came across this and had the exact same problem.  Unfortunately the new _rust_ route `cryptography` is taking is really a bit of a kink in the fence. It's also no longer compatible with many builds (such as arm6, arm7 as a result). See [**closed** issue with people not to happy about it here](https://github.com/pyca/cryptography/issues/5771). There is another good chunk of information [here](https://github.com/pyca/cryptography/issues/5799) on the workaround.

The workaround to the issue *for now* is [here](https://github.com/caronc/apprise-api/pull/42/files) (if this helps). It basically comes down to your `Dockerfile` adding:
```Dockerfile
ENV CRYPTOGRAPHY_DONT_BUILD_RUST=1
```

Alternatively you can haul in all the rust libraries too.  Good luck.

**Comment by Roxedus** [comment]
We have been battling cryptography since the day that code got merged. I'm pretty sure this will result in us building wheels to ease the load on our builders. AFAIK that env is just a temporary fix, we have already resorted to adding rust as build dependencies, and cleaning it up after building the packages.

**Comment by caronc** [comment]
Right now the only thing `cryptography` offers is  Firebase Cloud Messaging  without the bulky overhead of hauling in the entire google admin framework.  The latest version of Apprise can build the encrypted packets on the fly so it's lightweight in that regard. But i didn't realize it's dependency would create such an annoying ripple.

I'm tempted to just drop `cryptography` as a requirement and just silently disable the FCM Oauth2 section of it's plugin with a warning notice in the logs (to add the package for it's use).  I love the Cryptography package, it was so clean and portable up until now.

**Comment by nemchik** [comment]
This should be fixed now. If anyone still has issues with it please comment here and we'll look into it.
