### ISSUE TITLE
awscli for code server

### ISSUE THREAD

**Issue by capps1994** [linuxserver/docker-mods#182]
Hi, 
I have written a mod that will install the aws cli 

would it be possible to get a branch created called `code-server-awscli`

regards,
Chris

**Comment by aptalca** [comment]
Link?

**Comment by capps1994** [comment]
https://github.com/capps1994/code-server-awscli

**Comment by aptalca** [comment]
Thanks. It needs to be based on the template branch. Once you get that fixed, ping here and we'll review and create a new branch to PR to

**Comment by capps1994** [comment]
Ok, I have got it based on the template branch now 

 https://github.com/capps1994/code-server-awscli/tree/code-server-awscli

**Comment by aptalca** [comment]
You can PR here: https://github.com/linuxserver/docker-mods/tree/code-server-awscli
Also please use `apt-get` instead of `apt` and move the `apt-get update` to right above `apt-get install` so it is inside the if block and doesn't do an unnecessary update

Thanks

**Comment by capps1994** [comment]
cheers for all your help 👍
