### ISSUE TITLE
Problem in linuxserver image relative to token from dockerhub

### ISSUE THREAD

**Issue by StudioEtrange** [linuxserver/docker-mods#202]
There is a problem nowadays to retrieve token from dockerhub.
Something change and there is now a missing grep.

There is a missing grep in the curl instruction to retrieve the token from DockerHub
because the curl request return 4 fields

```
curl     --silent     --header 'GET'     "${AUTH_URL}"
{
 "token": "....",
 "access_token": "...",
 "expires_in": 300,
 "issued_at": "2021-05-07T02:42:01.633778362Z"
}
```

I have opened a PR in ubuntu base image, but i am not sure this was the right place where you centralized docker-mods script

https://github.com/linuxserver/docker-baseimage-ubuntu/pull/69

**Comment by Roxedus** [comment]
Closed with mentioned PR
