### ISSUE TITLE
qbittorrent-vuetorrent mod

### ISSUE THREAD

**Issue by peanutbother** [linuxserver/docker-mods#212]
I want to submit a new mod. 
Please create `qbittorrent-vuetorrent` branch so I can submit my PR for it.
This adds a mod for qbittorrent container which installs vuetorrent web ui and sets it as default web ui.

ref: 
https://github.com/peanutbother/docker-mods/tree/qbittorrent-vuetorrent

**Comment by aptalca** [comment]
Did you forget to push your changes? It looks exactly the same as the template branch

**Comment by pagdot** [comment]
It seems like the changes are in master, not the linked branch

**Comment by aptalca** [comment]
yeah, that's not gonna work

**Comment by peanutbother** [comment]
OH well.
In the event I forgot to push my changes...
My changes are now live, I am sorry for the inconviences!

**Comment by aptalca** [comment]
It looks like you just copied the files from the master branch commit. Please start over with the fresh template branch, make your changes and submit a PR.

**Comment by peanutbother** [comment]
just recreated the fork with correct branch, waiting for the `qbittorrent-vuetorrent`-branch so I can create my PR

**Comment by aptalca** [comment]
Apologies for dropping the ball on this. But a lot has changed with the mods lately. If you're still interested in publishing this, please rebase on the latest template branch and ping me here.

Thanks,

**Comment by peanutbother** [comment]
right now I don't have the necessary equipment anymore to test this in a proper environment.
if anybody needs help in using the mod or rebasing it I will try to help but as of now I can't test anything.
