### ISSUE TITLE
How to enable PHP extensions

### ISSUE THREAD

**Issue by Sander0542** [linuxserver/docker-mods#213]
I am trying to run a Laravel 8 project in the code server, but I am not able to install my composer dependencies, because I need extensions like `mbstring`. How can I install the required extensions and keep them after a restart of the container?

**Comment by aptalca** [comment]
You can use a custom script:
https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

**Comment by CHBMB** [comment]
Going to close this as answered
