### ISSUE TITLE
[FR] Mods to set default auth for all sample

### ISSUE THREAD

**Issue by Alexsaphir** [linuxserver/docker-mods#224]
It would be great to have a mod for each type of auth who when enabled would uncomment the line for this  auth method insise all the sample

Or a unique mod with an environment variable to get the auth mode choosen.

**Comment by nodiaque** [comment]
This could provoke other problem. Like I have 3 services that doesn't require MFA, authelia on my end is not active for these and I wouldn't want it active. It's part of the configuration process, you do it once and only everytime you add a new configuration, from which you already set all the other param. So what is removing 2 #?
