### ISSUE TITLE
Add java11 mod for code-server 595bb42

### ISSUE THREAD

**Issue by EGOISTK21** [linuxserver/docker-mods#233]
https://github.com/EGOISTK21/docker-mods/tree/code-server-java11

**Comment by aptalca** [comment]
Looks good (except the init file needs to be named `98-java11` 😉)

You can PR here: https://github.com/linuxserver/docker-mods/tree/code-server-java11

**Comment by EGOISTK21** [comment]
Oh, I got it. Done: https://github.com/linuxserver/docker-mods/pull/234
