### ISSUE TITLE
[FR] swag auto-proxy: Add label to override preset

### ISSUE THREAD

**Issue by pagdot** [linuxserver/docker-mods#236]
Add following label:

- `swag_address=containername` - *optional* - overrides swag config preset. Defaults to `container name`.

I'm thinking about giving auto-proxy a try and could maybe implement this myself

**Comment by aptalca** [comment]
The container name is how swag decides whether to use a preset conf or the generic template. As listed in the readme, it needs to match the preset conf name.

**Comment by pagdot** [comment]
Yes, I know. My idea is that if the container name isn't the app name. e.g. I don't specify a container name in compose. My container now has a name generated by docker-compose, which doesn't match any config sample. I could use this to override the sample to use.

**Comment by aptalca** [comment]
So you don't want to set a container name in the compose yaml and let it autogenerate, but you want to set a label in the compose yaml? Why not just set the container name?

That's not worth our dev time for no benefit

**Comment by pagdot** [comment]
Hmmm, yeah
