### ISSUE TITLE
Workflow issue: Actions `Tag image` thru `Push tags to DockerHub` are Ignored

### ISSUE THREAD

**Issue by shaneholloman** [linuxserver/docker-mods#255]
Ref: <https://github.com/shaneholloman/docker-mods/actions>

## Workflow Issue: 

Actions `Tag image` thru `Push tags to DockerHub` are Ignored

## I have:
- added the DockerHub and Github secrets for pushes
- and followed instruction to change the endpoint as stated here:

>The only code change you need to make to the build logic file .github/workflows/BuildImage.yml will be to modify the ENDPOINT to your own image:

```yaml
  ENDPOINT: "shaneholloman/endpoint-mod"
  BRANCH: "master"
```

**Nothing fails:** 
But,  the **actions** after `Build image` up to `Post Run actions/checkput@v2.3.3` are ignored and not executed

**Comment by aptalca** [comment]
Your branch is `main`, not `master`

**Comment by shaneholloman** [comment]
Thank you @aptalca ... testing that now

**Comment by shaneholloman** [comment]
Hi there and sorry to bother.
I changed branch from `main` to `master`


Tagging is failing 
https://github.com/shaneholloman/docker-mods/runs/4073670689?check_suite_focus=true

**Comment by shaneholloman** [comment]
Same Tagging issue on a fork with secrets also added

<https://github.com/shaneholloman-org/docker-mods/actions>
<https://github.com/shaneholloman-org/docker-mods/actions/runs/1410143440/workflow>

Is there maybe more to be changed other than what is mentioned here?: <https://github.com/linuxserver/docker-mods#getting-a-mod-to-dockerhub>
