### ISSUE TITLE
code-server MOD: extension-arguments

### ISSUE THREAD

**Issue by RoboMagus** [linuxserver/docker-mods#258]
I've created a mod for code-server that allows installation of code server extensions based on the extension IDs provided in an environment variable: [code-server-extension-arguments](https://github.com/RoboMagus/docker-mods/tree/code-server-extension-arguments)

Please create a `code-server-extension-arguments` branch so that I can create a PR to submit this mod.

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-mods/tree/code-server-extension-arguments

**Comment by RoboMagus** [comment]
Thanks, 

A PR has been made.
With that I'll close this issue.
