### ISSUE TITLE
OCR languages missing in papermerge

### ISSUE THREAD

**Issue by balves42** [linuxserver/docker-mods#260]
Hi,

i tried to run papermerge today, using:

docker run -d \
  -p 8000:8000 \
  -v /docker/papermerge/config:/config \
  -v /docker/papermerge/data:/data \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ="Europe/Lisbon" \
  -e DOCKER_MODS="linuxserver/mods:papermerge-multilangocr" \ 
  -e OCRLANG="por" \
  --restart always \
  --name=papermerge \
  lscr.io/linuxserver/papermerge:latest

but in the OCR languages list the only language that appears is English.
What am i missing? Is there a problem with the mod?

Thanks

**Comment by j0nnymoe** [comment]
Then mod installs the language packs for you then you adjust the papermerge config to use the additional languages you've installed.

**Comment by balves42** [comment]
thank you @j0nnymoe , that was it.
