### ISSUE TITLE
ProjectSend Mods: templates and translations

### ISSUE THREAD

**Issue by alexschomb** [linuxserver/docker-mods#261]
Please create the respective branches `projectsend-templates` and `projectsend-translations`, so that I can create pull requests in the correct branches for my mods.

**Comment by alexschomb** [comment]
For reference: https://github.com/linuxserver/docker-mods/pull/264 issued for `projectsend-translations`. Waiting for `projectsend-templates` branch.

**Comment by aptalca** [comment]
Do you still need projectsend-templates?

**Comment by alexschomb** [comment]
@aptalca Yes, if possible that would be great. Honestly I haven't looked into this topic anymore for a longer time, but I'll try to create a pull request similar to projectsend-translations.
