### ISSUE TITLE
Add R mod for code-server

### ISSUE THREAD

**Issue by greinet** [linuxserver/docker-mods#268]
I created a mod for code-server that installs the programming language R [code-server-r](https://github.com/greinet/docker-mods/tree/code-server-r) .
Please create the branch `code-server-r` so i can create a PR for the mod.

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-mods/tree/code-server-r

**Comment by greinet** [comment]
Thanks for the quick reply, PR created at: #269.
