### ISSUE TITLE
code-server MOD: SVN

### ISSUE THREAD

**Issue by RoboMagus** [linuxserver/docker-mods#272]
I've created a mod for code-server that installs Subversion and the SVN extension in code-server: [code-server-svn](https://github.com/RoboMagus/docker-mods/tree/code-server-svn).

Please create a ```code-server-svn``` branch so that I can create a PR to submit this mod.

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-mods/tree/code-server-svn

**Comment by RoboMagus** [comment]
Thanks you!
PR is made: #273
