### ISSUE TITLE
swag-geoip2influx mod: loading outdated script

### ISSUE THREAD

**Issue by wollsi** [linuxserver/docker-mods#283]
Even though the correct url is used in the Dockerfile:
https://github.com/linuxserver/docker-mods/blob/1683d67685ebe86df28d59dacc977f2a6bce2d89/Dockerfile#L3
if you build the container (linuxserver/swag:latest) with the swag-geoip2influx mod you get not the correct version of the script.

I have no idea why or where this mistake happens.

To reproduce you can use this MWE:

1. Run ```docker run -d -e DOCKER_MODS=linuxserver/mods:swag-geoip2influx linuxserver/swag```
2. Inspect ```/geoip2influx/geoip2influx.py```
3. Notice it is not indentical to the version over on github: https://github.com/GilbN/geoip2influx/blob/master/geoip2influx.py (or even the version referenced in the Dockerfile: https://raw.githubusercontent.com/gilbN/geoip2influx/master/geoip2influx.py)

I hope you can help with that problem. If you need further information I am happy to help wherever I can.

**Comment by wollsi** [comment]
I think I know now why the script is outdated.

If I understand it correctly, the mod does not pull the script directly, rather then a prebuild dockerimage from 
https://hub.docker.com/layers/linuxserver/mods/swag-geoip2influx/images/sha256-993fb221499fdd041d24b185458a4a946866f84a33015567ce7d98f4174f68d9 (in this case)

So to get the up to date version of https://raw.githubusercontent.com/gilbN/geoip2influx/master/geoip2influx.py the build has to be rerun.

And if I see it correctly, this does only happen when this branch https://github.com/linuxserver/docker-mods/tree/swag-geoip2influx gets updated.

Any change you could rerun the build to get the latest updates of the script?

**Comment by GilbN** [comment]
@aptalca Doesn't Jenkins build on commits to the geoip2influx repo?

**Comment by aptalca** [comment]
It does. Last triggered on Jan 10
https://ci.linuxserver.io/job/External-Triggers/job/mod-swag-geoip2influx-external-trigger/

**Comment by aptalca** [comment]
oh wait, it looks like it's getting an `access denied` on github api hit. Looking into it

**Comment by aptalca** [comment]
🤦‍♂️ it's trying to trigger the build on travis. We forgot to update it when we switched the builds to github workflows. I'm on it.

**Comment by aptalca** [comment]
Trigger updated, new build pushed.

@wollsi you can restart your container and it should pick up the new mod build. In the future, new commits should auto trigger a new build

Thanks for letting us know. We totally missed it

**Comment by wollsi** [comment]
Thanks a lot!
