### ISSUE TITLE
[FR] Auth options for swag-dashboard

### ISSUE THREAD

**Issue by pagdot** [linuxserver/docker-mods#297]
Hi, thx for the dashboard :)

Because I'm using it on a Server on a VPS, configuration option using env variables would be nice to use an authentication instead of limiting it to a few ip ranges.

Maybe something similar to swag-auto_proxy where you can select an auth option and the default one is only allow LAN ip ranges.

I managed to add the necessary changes to the proxy conf file, It just would be nicer/easier :)

**Comment by aptalca** [comment]
You can edit the proxy conf for it. Your changes won't get overwritten when the mod is updated

**Comment by pagdot** [comment]
Yes, I know (and I already managed to implement the changes) :) Just would be a nice enhancement. If it is out of scope, I'll close the issue
