### ISSUE TITLE
Auto proxy doesnt work for containers on different nodes in swarm mode

### ISSUE THREAD

**Issue by psbankar** [linuxserver/docker-mods#300]
For many days I was using swag with auto proxy with docker socket auto proxy in swarm mode with a single node as manager. I didnt face any issue with that configuration. But recently I added a new node to the swarm and thats where auto proxy broke. I made docker socket proxy deploy in global mode. But the proxy confs are generated only for some containers on one node or many times the auto proxy itself fails. Any way to make this work correctly in swarm mode?

**Comment by aptalca** [comment]
We do not support or test swarm
