### ISSUE TITLE
Add nvm mod for code-server

### ISSUE THREAD

**Issue by xiaohai-huang** [linuxserver/docker-mods#310]
I created a mod for code-server that installs version manager for node.js - nvm. Here is my repo [https://github.com/xiaohai-huang/docker-mods/tree/code-server-nvm](https://github.com/xiaohai-huang/docker-mods/tree/code-server-nvm)
Please create the branch `code-server-nvm` so that I can create a PR for the mod.

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-mods/tree/code-server-nvm
