### ISSUE TITLE
Add Julia mod for code-server

### ISSUE THREAD

**Issue by MateoPeri** [linuxserver/docker-mods#319]
Made a Julia docker mod https://github.com/MateoPeri/docker-mods/tree/code-server-julia. It installs the language as well as some extensions (the official Julia extension and some formatters).

Please add a branch `code-server-julia` for me to submit a PR. Thanks.

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-mods/tree/code-server-julia
