### ISSUE TITLE
Failing to install dotnet mod

### ISSUE THREAD

**Issue by rsfurlan90** [linuxserver/docker-mods#320]
Hello, looks like something has changed in the versioning schema and broke the dotnet mod configuration. This mod was working fine until past week, when I created my code-server container, however I tried to recreate it today and got errors like this in the logs:

ln: failed to create symbolic link '/**dotnet_6.0.102**/shared/Microsoft.NETCore.App/3.1.22': No such file or directory
ln: failed to create symbolic link '/**dotnet_6.0.102**/shared/Microsoft.AspNetCore.App/3.1.22': No such file or directory
ln: failed to create symbolic link '/**dotnet_6.0.102**/sdk/3.1.416': No such file or directory

**Comment by rsfurlan90** [comment]
Have done some debugging and found that script is able to create dotnet folders properly at root, but can only extract version 3.1.416; for some weird reason folder dotnet_6.0.102 is empty =/

**Comment by aptalca** [comment]
Perhaps it was a faulty curl. I just repushed it. Can you try again? You should be able to just restart the container and it should pull the new version.

**Comment by rsfurlan90** [comment]
It is working again! Thank you so much

**Comment by aptalca** [comment]
Please try again

**Comment by hanc2006** [comment]
Now works. Thank you :+1:
