### ISSUE TITLE
Universal mod: package install

### ISSUE THREAD

**Issue by RoboMagus** [linuxserver/docker-mods#324]
I've created a universal mod that installs packages provided through an environment variable argument `APT_PACKAGES` using apt install: [universal-apt-install](https://github.com/RoboMagus/docker-mods/tree/universal-apt-install).

Please create a `universal-apt-install` branch so that I can create a PR to submit this mod.

**Comment by aptalca** [comment]
if it's universal, it should support both ubuntu and alpine (apt and apk)

**Comment by RoboMagus** [comment]
Thanks for that info. I'll take a look later today to make it apk compatible.
Though name wise it should then probably change to universal-package-installer.

**Comment by RoboMagus** [comment]
@aptalca , I've modified the things to make it compatible with alpine base images as well.
The mod has now been renamed to `universal-package-install`, with packages being provided through the `INSTALL_PACKAGES` environment variable.

Based on quick test with muximux and code-server seems to indicate it now works on both base images.

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-mods/tree/universal-package-install

**Comment by RoboMagus** [comment]
Thanks for guiding me through it and getting the PR merged!
