### ISSUE TITLE
Scarf redirects do not work with mods

### ISSUE THREAD

**Issue by Bockiii** [linuxserver/docker-mods#325]
Using the new lscr.io/* image descriptors does not work with mods logic.

Example:

Call ( in this example with the codeserver image)
`- DOCKER_MODS=lscr.io/linuxserver/mods:code-server-docker|lscr.io/linuxserver/mods:code-server-php`

Log
```
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying lscr.io/linuxserver/mods:code-server-docker files to container
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
/docker-mods: line 117: /lscr.io.linuxserver/mods.code-server-docker: No such file or directory
[mod-init] Applying lscr.io/linuxserver/mods:code-server-php files to container
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
/docker-mods: line 117: /lscr.io.linuxserver/mods.code-server-php: No such file or directory
```

**Comment by TheSpad** [comment]
This is a known limitation at the moment because the mod logic varies depending on the backend registry (docker.io or ghcr.io) and there's not currently a way to publicly query the backend registry that Scarf is using.

We've raised the issue with Scarf to see if we can come up with a solution.

**Comment by thespad** [comment]
Might be workable now that the mod logic has been harmonised between registries, will do some testing.
