### ISSUE TITLE
Add ssl mod for code-server

### ISSUE THREAD

**Issue by MateoPeri** [linuxserver/docker-mods#327]
I'm making a docker mod to allow connections via HTTPS https://github.com/MateoPeri/docker-mods/tree/code-server-ssl.
Please add a branch code-server-ssl for me to submit a PR. Thanks.

**Comment by aptalca** [comment]
Please have your branch ready, and then ping us here

**Comment by MateoPeri** [comment]
I was waiting for the new release of [`code-server`](https://github.com/coder/code-server/releases/tag/v4.1.0), which fixes the issue that prevented ssl from working (see https://github.com/linuxserver/docker-code-server/pull/23). It should now be working.

There are no changes needed to the Dockerfile, just a startup script that changes the run command to include certificate info.
Then, in `docker-compose.yml` two new env variables are needed: `SSL_CERT_PATH` and `SSL_KEY_PATH`.

**Comment by aptalca** [comment]
It needs to be based on the template branch and please follow the instructions there

**Comment by MateoPeri** [comment]
Ah, my mistake. It is now based on the template branch.

**Comment by aptalca** [comment]
Init script is missing. Once that's fixed, you can PR to https://github.com/linuxserver/docker-mods/tree/code-server-ssl

**Comment by MateoPeri** [comment]
It seems it got lost with the branch change. Fixed now.
