### ISSUE TITLE
dotnet dependencies missing

### ISSUE THREAD

**Issue by hanc2006** [linuxserver/docker-mods#332]
In a debian-based distribution, dotnet requires the following dependencies:

- libc6
- libgcc1
- libgssapi-krb5-2
- **libicu67**
- libssl1.1
- libstdc++6
- zlib1g

If you try to run the `dotnet --info` command you will get this error:

`Couldn't find a valid ICU package installed on the system.`

This is because the **libicu67** or equivalent package is missing.

Possible solutions to solve the issue:
- Add an additional script to install the missing dependencies
- Or export the global variable DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1

**Comment by aptalca** [comment]
I'll be damned, you're right. I never noticed it because I always run mine with the docker-in-docker mod, which apparently installs libicu.

I'll get this added. By the way, where did you find a list of those deps?

**Comment by hanc2006** [comment]
I found all the specs here: https://docs.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual
