### ISSUE TITLE
cloudflare_real-ip: nginx: [emerg] invalid number of arguments in "set_real_ip_from" directive in /config/nginx/cf_real-ip.conf:1

### ISSUE THREAD

**Issue by zigacerar** [linuxserver/docker-mods#335]
I have been using cloudflare_real-ip  mod for my SWAG instance for quite some time now. Today though at my server restart, it started throwing out error nginx: [emerg] invalid number of arguments in "set_real_ip_from" directive in /config/nginx/cf_real-ip.conf:1

I have tried the wait for internet mod, but that does not seem to fix anything (makes sense as the server is definitely online before swag tries to run. My cf_real-ip conf looks like this:

set_real_ip_from ;
set_real_ip_from ;
set_real_ip_from 172.18.0.0/16;

**Comment by Byrrell** [comment]
I had the same problem, and restarting swag didn't seem to fix it. I manually copied the IPV4 and IPV6 lists from [the docker mod page](https://github.com/linuxserver/docker-mods/tree/swag-cloudflare-real-ip), so my cf_real-ip.conf looked like this:
```
set_real_ip_from 173.245.48.0/20;
set_real_ip_from 103.21.244.0/22;
set_real_ip_from 103.22.200.0/22;
set_real_ip_from 103.31.4.0/22;
set_real_ip_from 141.101.64.0/18;
set_real_ip_from 108.162.192.0/18;
set_real_ip_from 190.93.240.0/20;
set_real_ip_from 188.114.96.0/20;
set_real_ip_from 197.234.240.0/22;
set_real_ip_from 198.41.128.0/17;
set_real_ip_from 162.158.0.0/15;
set_real_ip_from 104.16.0.0/13;
set_real_ip_from 104.24.0.0/14;
set_real_ip_from 172.64.0.0/13;
set_real_ip_from 131.0.72.0/22;
set_real_ip_from 2400:cb00::/32;
set_real_ip_from 2606:4700::/32;
set_real_ip_from 2803:f800::/32;
set_real_ip_from 2405:b500::/32;
set_real_ip_from 2405:8100::/32;
set_real_ip_from 2a06:98c0::/29;
set_real_ip_from 2c0f:f248::/32;
set_real_ip_from 172.18.0.0/16;
```
The error then went away. When I tried copying the cf_real-ip.conf that @zigacerar mentioned back into my cf_real-ip.conf and restarted swag, the ips were retrieved correctly again and everything is working. Not sure why this happened.

**Comment by Roxedus** [comment]
Try again, fix was merged 10 minutes ago

**Comment by zigacerar** [comment]
I can confirm it works after a swag restart.
