### ISSUE TITLE
Add mediadc mod for nextcloud

### ISSUE THREAD

**Issue by JonathanTreffler** [linuxserver/docker-mods#338]
The new mediaDC Nextcloud App requires a bunch of extra dependencies.
My new mod for it is currently at: https://github.com/JonathanTreffler/docker-mods/tree/nextcloud-mediadc
If you create a branch for it I can create a Pull Request when testing is done :)

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-mods/tree/nextcloud-mediadc

**Comment by JonathanTreffler** [comment]
I opened the PR in #339
