### ISSUE TITLE
Requesting branch for transmission mod

### ISSUE THREAD

**Issue by josevh** [linuxserver/docker-mods#340]
I'd like to add a docker mod to enable setting Transmission settings in the docker-transmission container via environment variables. I'd like a `transmission-env-var-settings` branch opened to open a PR against.

The mod currently lives at https://github.com/josevh/docker-mods/tree/transmission-env-var-settings.

**Comment by aptalca** [comment]
Sorry, We were very busy with getting all the mods updated for s6v3 and a new mod builder action.

Are you still interested in PRing this mod? If so, please rebase on the new template branch

**Comment by josevh** [comment]
@aptalca I went ahead and rebased off the latest `template` branch.

**Comment by aptalca** [comment]
Here you go: https://github.com/linuxserver/docker-mods/tree/transmission-env-var-settings

**Comment by josevh** [comment]
Awesome, thank you.
Opened a PR: https://github.com/linuxserver/docker-mods/pull/718

**Comment by josevh** [comment]
PR is merged, thank you.
