### ISSUE TITLE
Problem with papermerge mod

### ISSUE THREAD

**Issue by killiampm** [linuxserver/docker-mods#341]
Good Moorning,

I have create a papermerge docker container with the following environment variables:
 -e DOCKER_MODS=linuxserver/mods:papermerge-multilangocr 
-e OCRLANG=spa

Than a i have modified the papermerge.conf.py:

OCR_DEFAULT_LANGUAGE = "spa"

OCR_LANGUAGES = {
    "eng": "English",
    "spa": "Spanish"
}

And modified the preferences in papermerge, to OCR language to Spanish.

The problem is that when i upload a document and run ocr, it seems that is working fine, i have looked in the logs and i have found nothing.... but seems that the OCR is not working...

¿Could you please help me? 

Any suggestion is welcome

Thanks in advance,

Killiam

**Comment by killiampm** [comment]
Good Night Roxedus,

I have attached the docker container logs.

Looking in the papermerge log I see that OCR process in spanish is starting: 

_**STARTED OCR for document Prueba_3_5.pdf, page=1, language=spa, doc_id=12.**_

But is not finishing...

[docker_papermerge_logs.txt](https://github.com/linuxserver/docker-mods/files/8149398/docker_papermerge_logs.txt)

Thanks in advance.

Killiam

**Comment by Roxedus** [comment]
`Temporary failure resolving 'archive.ubuntu.com'` Container doesnt have internet at startup, it never installs the mod.

**Comment by killiampm** [comment]
Thanks a lot @Roxedus in fact the problem was that...  it was driving me crazy :)
