### ISSUE TITLE
Dashboard Mod. Error starting SWAG.

### ISSUE THREAD

**Issue by rzrpt** [linuxserver/docker-mods#347]
I'm feeling a bit dumb.

I enabled the dashboard mod:

DOCKER_MODS=linuxserver/mods:swag-dashboard

But SWAG fails to start with:

"server" directive is not allowed here in /config/nginx/proxy-confs/dashboard.subdomain.conf:4

I tried deleting the file or moving it to the site-confs folder, but everytime swag starts it creates the conf file in the proxy-confs directory (that should only have .sample files)

Any help?

**Comment by Roxedus** [comment]
`proxy-confs` is not exclusively for samples, swag is set up to work with `proxy-confs` out of the box. This error should not be a thng with stock configs. Post your default file, as I cannot assume you are using stock.

**Comment by rzrpt** [comment]
I had an include in the default nginx config that shouldn't been there. It seems i am indeed dumb :)

Thank you.
