### ISSUE TITLE
Dashboard Mod: Opening issue here as recommended

### ISSUE THREAD

**Issue by STaRDoGG** [linuxserver/docker-mods#350]
Asked this in the LSIO SWAG channel and was directed to ask here instead, by j0nnymoe. Rather than retype it all, I'll just post the screenshot:

![image](https://user-images.githubusercontent.com/1524526/158483560-84696404-4c41-45eb-ba91-bd73fcc669ba.png)

My proxy conf folders look like this:

![image](https://user-images.githubusercontent.com/1524526/158483672-ac6b27c8-1dee-4c5c-95c4-fc70fbf300a3.png)

As described [here](https://github.com/linuxserver/docker-swag/issues/211#issuecomment-1055578950).

**Comment by quietsy** [comment]
Added under [https://github.com/linuxserver/docker-mods/pull/351](https://github.com/linuxserver/docker-mods/pull/351)
