### ISSUE TITLE
[SWAG-Dashboard] persistent data

### ISSUE THREAD

**Issue by EVOTk** [linuxserver/docker-mods#352]
Hello,
In [goaccess.conf](https://github.com/linuxserver/docker-mods/blob/swag-dashboard/root/dashboard/goaccess.conf#L731) the **db-path** variable is by default on `/tmp` which means that the dashboard data is lost when the container is re-created!
Would it be possible to configure another path, for example `dashboard/db`/ and to give the possibility of making this folder persistent on the host?

thank you

**Comment by quietsy** [comment]
Hey @EVOTk, you can mount `/tmp` to make it persistent on the host, or you can mount your own `goaccess.conf` with modified paths, though keep in mind these configurations haven't been tested.

**Comment by EVOTk** [comment]
Hello, 
I tried that without success, goaccess.conf seems to be overwritten.
