### ISSUE TITLE
Add tesseract mod for nextcloud

### ISSUE THREAD

**Issue by JonathanTreffler** [linuxserver/docker-mods#357]
I developed another nextcloud mod, this time for two apps "Full text search - Files - Tesseract OCR" and "Workflow OCR".
Their required dependencies are very similar, so i combined them into the "tesseract" mod.
If you create a branch nextcloud-tesseract i can create a PR.

https://github.com/JonathanTreffler/docker-mods/tree/nextcloud-tesseract

**Comment by JonathanTreffler** [comment]
ping

**Comment by evanre** [comment]
IMHO, it's overhead, to install all the available languages, isn't it better to provide some additional var with the list of needed languages?

PS. I have implemented a workaround for myself, but to be honest, this extension is penniless in Nextcloud, so I decided to stick to papermerge/peperless.
**custom-cont-init.d/custom.sh**
```sh
#!/usr/bin/with-contenv bash

echo "**** CUSTOM SCRIPT START ****"
apk add --no-cache --upgrade \
        tesseract-ocr \
        tesseract-ocr-data-pol \
        tesseract-ocr-data-rus \
        tesseract-ocr-data-ukr

echo "**** CUSTOM SCRIPT END ****"
```

**Comment by JonathanTreffler** [comment]
> We already have a mod for ocr languages that we use with paperX containers. It accepts a var for the languages requested. It's currently Ubuntu only, so we just need to make it universal

(Small Note: That mod does not have ocrmypdf, which would be neccessary if we adapt it for nextcloud)

**Comment by aptalca** [comment]
Sorry, We were very busy with getting all the mods updated for s6v3 and a new mod builder action.

Are you still interested in PRing this mod? If so, please rebase on the new template branch

**Comment by JonathanTreffler** [comment]
In general yes, but I won't have time for it for a while.
