### ISSUE TITLE
Question about mods

### ISSUE THREAD

**Issue by YouveGotMeowxy** [linuxserver/docker-mods#358]
Nextcloud  needs ImagicMagick (IM) for generating video previews ([as per](https://help.nextcloud.com/t/show-thumbnails-for-videos/71251/19));  if I add the Nginx IM mod does it also affect Nextcloud? Or do I need to somehow add IM seperately to the Nextcloud container?

**Comment by aptalca** [comment]
our nextcloud image is nginx based and that mod should work fine for it. I'll look into whether it's appropriate to advertise it for nextcloud as well.

**Comment by aptalca** [comment]
umm, scratch that. Our nextcloud already has imagemagick installed: https://github.com/linuxserver/docker-nextcloud/blob/master/Dockerfile#L32

**Comment by YouveGotMeowxy** [comment]
@aptalca Can you answer that real quick please?

Just so I'm clear, for example if I add `DOCKER_MODS=linuxserver/mods:universal-apprise` to my swag Compose, does apprise get added to all sites that swag is serving?

**Comment by aptalca** [comment]
Serve, yes. Reverse proxy, no.

**Comment by YouveGotMeowxy** [comment]
@aptalca Sorry, I'm kinda dense sometimes, lol. So if say I wanted to use apprise from all of my containers, would I be better off running a separate apprise container and putting it in the same network as those other containers? Or just add the mod to the swag compose, and then all those containers would be able to use apprise the same as if I had been running apprise in an individual container?

**Comment by aptalca** [comment]
Other containers won't magically have apprise if you put it in swag.

I never used apprise so no idea how the apprise container works

**Comment by YouveGotMeowxy** [comment]
@aptalca ok, ty.

**Comment by YouveGotMeowxy** [comment]
> Other containers won't magically have apprise if you put it in swag.
> 
> I never used apprise so no idea how the apprise container works

@aptalca Similar question: if I run a crowdsec container, and then add the crowdsec bouncer mod to the swag docker-compose, does crowdsec then also handle all of the subdomains that swag is managing? 

i.e. if my main/default swag domain is `blah.domain.com`, and i have a subdomain `blahblah.domain.com`, does blahblah get protected by crowdsec as well? OD do I need to somehow add an individual bounder to every subdomain swag handles as well?

Reason I ask: My default domain is running organizr, but I also have subdomains like nextcloud, dozzle, radarr; and after adding crowdsec I'm getting a DNS error trying to access organizr, but I can access all my subdomains just fine. Very confused, lol.

Sorry if this is annoying, but it's a bit confusing for noobies like me, lol.
