### ISSUE TITLE
Ability to update node for code-server

### ISSUE THREAD

**Issue by HarveyB02** [linuxserver/docker-mods#366]
I'd like to update node to v16 in code server, was told to make an issue here as the code server does not use the system node anymore and isnt required to be locked to v14 anymore

**Comment by squeezeboxhuf** [comment]
Same! Currently I'm manually updating to nodejs v16 after each container restart...

**Comment by colwellkr** [comment]
> Same! Currently I'm manually updating to nodejs v16 after each container restart...

Same issue here... How are you going about upgrading to v16?

**Comment by aptalca** [comment]
The nodejs mod now allows for defining the version via an env var
