### ISSUE TITLE
goaccess.conf (and other /dashboard file changes)

### ISSUE THREAD

**Issue by AlastairBateman** [linuxserver/docker-mods#369]
I have to make two changes after I `docker compose up -d`..

I need to add the following lines to /dashboard/goaccess.conf
`log-format '%^ %h - %^ [%d:%t %^] "%r" %s %b "%R" "%u"'
date-format %d/%b/%Y
time-format=%T`

And I have to modify line 19 of /dashboard/swag_proxies.py from:
`file = open(file_path, "r")`
to
`file = open(file_path, "r", encoding='unicode_escape')`

Otherwise I get a white screen with 'Cleaning up resources..."

I haven't created a pull request because I'm not sure if this is related to my environment or more general. The question remains, though.. Each time I bring up swag, it seems to generate these files again, even if I mount them in my `docker-compose.yml`. Is there any way to persistently modeify these files or pass environemnt variables through to goaccess?

**Comment by GonzoTG** [comment]
Thanks for this. I have had this issue since installing and haven't had time to dig in. I also am having that error with "Cleaning up resources" and have customized my log format. I will have to parse out the log-format option for my situation.

I guess that' the long way to say "me too"

**Comment by GonzoTG** [comment]
@AlastairBateman if you want to update goaccess.conf and sway_proxies.py every time the docker starts up, then you can add a container customization script in /config/custom-cont-init.d

I've added the following script called: 20-dashboard

which contains
```
#!/bin/bash
cp /config/dashboard/* /dashboard
```
I realized that my log format was causing havoc on the existing config.

The feature reust might be to add customization of goaccess.conf

**Comment by AlastairBateman** [comment]
Thanks @GonzoTG ... I hadn't thought of doing it that way. I thought there must be some way of doing it in the mod configuration but this works just as well. 

I'm not a python developer so not sure whether the `swag_proxies.py` change requires a pull request created, but I can do that if necessary.

And the `goaccess.conf` changes could probably do with some documentation, particularly around log formats, etc.
