### ISSUE TITLE
Mod Request: Nano

### ISSUE THREAD

**Issue by YouveGotMeowxy** [linuxserver/docker-mods#370]
I use nano as my preferred editor, so for containers that don't include it I have to always do an `apk add nano` inside of it after every restart; could someone please create a Universal nano mod?

I would do it because it seems super simple but I'm not familiar at all with the whole GH buildimage stuff, and I'd have to create a DH repo and all that stuff, which is a long, time-consuming learning curve for a noobie, and I'm guessing a 10 minute thing for someone experienced.

I would immensely appreciate it  :)!

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-mods/tree/universal-package-install
