### ISSUE TITLE
swag-auto-proxy auth fails for apps that have an proxy template

### ISSUE THREAD

**Issue by cheesemarathon** [linuxserver/docker-mods#372]
Hi

When using the auto-proxy setting the `swag-auto-proxy` label produces the following response when a proxy template exists.

`**** Swag auth bypass is auto managed via preset confs and cannot be overridden via env vars ****`

Is there a way that this can be updated so the `swag-auto-proxy` label always works? For example, opening up API endpoints like with Sonarr.

Thanks,

**Comment by aptalca** [comment]
built-in proxy confs already handle that automatically: https://github.com/linuxserver/reverse-proxy-confs/blob/master/sonarr.subdomain.conf.sample#L41-L49

**Comment by cheesemarathon** [comment]
Ok, that makes sense. I have created the following application at dash.teams.cloudflare.com but it is still asking for authentication. Any ideas?

```
{
    "domain": "sonarr.XXX.com/api",
    "name": "Sonarr API",
    "policies": [
        {
            "created_at": "2022-05-11T15:13:31Z",
            "decision": "allow",
            "exclude": [],
            "id": "f77c049c-124c-4eee-93c7-03d1c7962fe2",
            "include": [
                {
                    "everyone": {}
                }
            ],
            "name": "Sonarr API Allow",
            "precedence": 1,
            "require": [],
            "uid": "f77c049c-124c-4eee-93c7-03d1c7962fe2",
            "updated_at": "2022-05-11T15:13:31Z"
        }
    ],
    "allowed_idps": [
        "402ee4ed-6951-47df-96b7-482acc968d32"
    ],
    "auto_redirect_to_identity": true,
    "session_duration": "24h",
    "zoneId": 174878392,
    "http_only_cookie_attribute": true,
    "app_launcher_visible": true,
    "type": "web"
}
```

**Comment by cheesemarathon** [comment]
If anyone else finds this and was a moron like me, check to ensure your access rule is set to `bypass` not `allow`

**Comment by ajnart** [comment]
Hi @aptalca , I am also struggling with this. Is it possible to make it so that `swag-auto-proxy` labels take over the default configs ?

**Comment by aptalca** [comment]
No. We want the default configs to take priority as they are curated for each app.

**Comment by aptalca** [comment]
One thing you can do is, rename the container so it doesn't match a default config and then it will be created from scratch based on your labels

**Comment by ajnart** [comment]
> No. We want the default configs to take priority as they are curated for each app.

So in order to overwrite them I'd need to delete the config and use the tags instead or create a new config ? It seems kind of counter-productive. 

In my example for Photoprism,. am trying to add the `swag_url_bypass=/s/` (it means share, to create a public URL to share a subset of photos) in order to be able to share sharing links with people and them not having to login but also relying on photoprism auth. 

> One thing you can do is, rename the container so it doesn't match a default config and then it will be created from scratch based on your labels

Alright I will do that then. Would you like me to do a PR so that public share links are bypassed by authelia in the default config of photoprism too ?

**Comment by ajnart** [comment]
> > In my example for Photoprism,. am trying to add the swag_url_bypass=/s/ (it means share, to create a public URL to share a subset of photos) in order to be able to share sharing links with people and them not having to login to anything
> 
> > Would you like me to do a PR so that public share links are bypassed by authelia in the default config of photoprism too ?
> 
> If that's something other people would also use, it can be PRed to the default config, sure

Actually after trying it seems that the client requests the url in `/library/albums/` when using a `/s/` link. Therefore it's redirected to authelia and forced to log-in. I will just disable authelia for my photoprism instance and rely on the integrated auth
