### ISSUE TITLE
Maxmind mod

### ISSUE THREAD

**Issue by johnvick** [linuxserver/docker-mods#378]
The databases are not being downloaded and this is in the log:

Applying the maxmind mod...
Downloading GeoIP2 City database.
tar: invalid tar magic
Applied the maxmind mod

What's the reason?

**Comment by aptalca** [comment]
Please post a compose yaml and a full log

**Comment by johnvick** [comment]
The container updated overnight, the tar error is no longer there and the database is in place.

**Comment by aptalca** [comment]
It was likely a temporary connection issue to github
