### ISSUE TITLE
Maxmind mod step seven

### ISSUE THREAD

**Issue by johnvick** [linuxserver/docker-mods#384]
Can I check I am doing this correctly - all seems fine until step 7.

I created file maxmind.subdomain.conf and pasted from step 7 calling it maxmind not some-app:

`
server {
     listen 443 ssl;
     listen [::]:443 ssl;

     server_name maxmind.*;
     include /config/nginx/ssl.conf;
     client_max_body_size 0;

     if ($lan-ip = yes) { set $geo-whitelist yes; }
     if ($geo-whitelist = no) { return 404; }

     location / {
`
But get this error in SWAG log:

nginx: [emerg] unexpected end of file, expecting "}" in /config/nginx/proxy-confs/maxmind.subdomain.conf:13

Looks like a syntax error? 

Any help appreciated.

**Comment by drizuid** [comment]
step 7 is an example for how you modify existing proxy-configs, hence it saying use it in the following way, not copy paste it. maxmind isn't a web ui so you wouldn't proxy it as you're showing. You would modify something like sonarr.subdomain.conf and add the step7 info in so it looks similar.

If you need further help, please join our discord.
