### ISSUE TITLE
Requesting Branch creation for Deluge Mod

### ISSUE THREAD

**Issue by hollanbm** [linuxserver/docker-mods#385]
[deluge-nopass](https://github.com/hollanbm/Linuxserver-Deluge-NoPass-Mod)

This mod, modifies the deluge UI to automatically submit the default password, when the webui is launched. The initial login, password change prompt is also disabled.

**Comment by hollanbm** [comment]
@aptalca bump

**Comment by aptalca** [comment]
Sorry, We were very busy with getting all the mods updated for s6v3 and a new mod builder action.

Are you still interested in PRing this mod? If so, please rebase on the new template branch
