### ISSUE TITLE
Upgrade java to 17

### ISSUE THREAD

**Issue by nickyhuyskens** [linuxserver/docker-mods#391]
Could java 11 be upgraded to 17? or 17 added?

**Comment by bamtests** [comment]
I actually just created and tested a new mod for that and also working on maven real quick. Looking at how to ask the team to creat the branch and this will be ready for everyone

**Comment by bamtests** [comment]
can use this in the meantime - bambam018/docker-mod-java17

**Comment by aptalca** [comment]
Nodejs mod now allows seeing the version via an env var
