### ISSUE TITLE
[radarr-striptracks] How to keep only original + english tracks?

### ISSUE THREAD

**Issue by adityachandelgit** [linuxserver/docker-mods#392]
Suppose radarr has downloaded a Japanese movie with multiple audio tracks including Japanese (original track detected by radarr) and English. 
What arguments should I provide to script if I want to keep just 2 tracks, i.e. "original/detected audio track"(Japanese in this case) and english track? Another example, for a German movie, only German and English tracks should be kept.
Thanks!

**Comment by aptalca** [comment]
@TheCaptain989

**Comment by TRaSH-** [comment]
> Suppose radarr has downloaded a Japanese movie with multiple audio tracks including Japanese (original track detected by radarr) and English. What arguments should I provide to script if I want to keep just 2 tracks, i.e. "original/detected audio track"(Japanese in this case) and english track? Another example, for a German movie, only German and English tracks should be kept. Thanks!

Questions like this doesn't belong here, app specific questions should be asked in the app support channels.
For [Radarr Discord](https://radarr.video/discord) is the best place to ask and get support.

**Comment by TheCaptain989** [comment]
@adityachandelgit,

The script can't automatically do what you're asking.  Until recently, the idea of "original" language was not even completely coded in Radarr (maybe this was added in v4?  I haven't been keeping close watch on this.)  However, you can accomplish what you want with tagging and a bit of work.  Let's look at an example.

**Japanese language films example**
1. Create a new [wrapper script](https://github.com/TheCaptain989/radarr-striptracks#example-wrapper-script) named `striptracks-jpn-eng.sh` in your `/config` directory (wherever it is mapped to) containing: 
   ```shell
   #!/bin/bash

   . /usr/local/bin/striptracks.sh --audio :jpn:eng --subs :jpn:eng
   ```
2. Make it executable:
   `chmod +x /config/striptracks-jpn-eng.sh`
3. Create a new custom Connect script in Radarr named "Remux Japanese movie", adding the path to the new script and adding the "japanese" tag:
![Screenshot 2022-07-03 124434](https://user-images.githubusercontent.com/11523885/177051477-4c93868b-e104-4218-a6e8-8044e06dc701.png)
4. Add the "japanese" tag name to any movie you want to process using the custom script:
![Screenshot 2022-07-03 125116](https://user-images.githubusercontent.com/11523885/177051553-754b242f-9aba-4af0-85cc-05042f55befe.png)
5. When a tagged movie is downloaded (e.g. "Imported" or "Upgraded") the language specific custom script will execute and remux the movie keeping only Japanese and English audio and subtitles.
>NOTE: If you also have a striptracks.sh Connect script will **no tags** it might also execute, causing undesired results!

Using this method, you'll have to create a custom script and tag for each primary language you want to keep, so in your example, a German script and "german" tag would be needed also, replacing "jpn" with "deu" in the script.

Now that I see Radarr has the "originalLanguage" value coded in, I will consider this as an enhancement request for my script.  It will take quite a bit of testing to see how Sonarr behaves with any change like this.

**Comment by TheCaptain989** [comment]
The latest dev commit TheCaptain989/radarr-striptracks@ced3559 resolves this.  Once I issue a PR I'm considering this closed.

**Comment by TheCaptain989** [comment]
This is closed (@aptalca)
