### ISSUE TITLE
New Branch Request - code-server-java17

### ISSUE THREAD

**Issue by bamtests** [linuxserver/docker-mods#394]
I have forked the repo and added a new branch on my end: https://github.com/bamtests/docker-mods/tree/code-server-java17
I tested it by pulling it from dockerhub and creating a new openvscode-server instance and adding the mod to it. After creating, running `java -version` results in the expected: 
```
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment (build 17.0.3+7-Ubuntu-0ubuntu0.20.04.1)
OpenJDK 64-Bit Server VM (build 17.0.3+7-Ubuntu-0ubuntu0.20.04.1, mixed mode, sharing)
```

DockerHub: https://hub.docker.com/repository/docker/bambam018/docker-mod-java17

**Comment by aptalca** [comment]
Nodejs mod now allows for setting the version via an env var
