### ISSUE TITLE
New Branch Request - code-server-maven

### ISSUE THREAD

**Issue by bamtests** [linuxserver/docker-mods#395]
I have forked the repo and added a new branch on my end: https://github.com/bamtests/docker-mods/tree/code-server-maven
I tested it by pulling it from dockerhub and creating a new openvscode-server instance and adding the mod to it. After creating, running `mvn -v` results in the expected: 
```
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 17.0.3, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.18.10-200.fc36.x86_64", arch: "amd64", family: "unix"
```

DockerHub: https://hub.docker.com/repository/docker/bambam018/docker-mod-maven

**Comment by aptalca** [comment]
New branch created, but keep in mind that the mods have changed since. They are now hybrid s6v2 and s6v3
https://github.com/linuxserver/docker-mods/tree/code-server-maven

**Comment by aptalca** [comment]
Closing.

If still interested, you can open a new request because the template changed significantly.
