### ISSUE TITLE
Host's Fail2ban not showing in Dashboard

### ISSUE THREAD

**Issue by zedocrob** [linuxserver/docker-mods#398]
Hi,
Trying to mount volume:
- /var/lib/fail2ban/fail2ban.sqlite3:/dashboard/fail2ban.sqlite3:ro
in the SWAG compose file, but host's Fail2ban still not showing in Dashboard.

Then i tried to add these two ENV:
      - MOD_DASHBOARD_F2B_HOST_DB=/var/lib/fail2ban/fail2ban.sqlite3
      - MOD_DASHBOARD_F2B_MAX_LINES=30
But still not showing

Is there something else to try?

**Comment by j0nnymoe** [comment]
The host DB path needs to be the path within the container, not the host path.

**Comment by zedocrob** [comment]
You mean like this exemple?
https://github.com/linuxserver/docker-mods/pull/343#issuecomment-1056110368

      i tried:
      - /var/lib/fail2ban/fail2ban.sqlite3:/var/lib/fail2ban/fail2ban.sqlite3:ro
      
      but not showing either

**Comment by MilesTEG1** [comment]
> The host DB path needs to be the path within the container, not the host path.

What if I want to use another instance of fail2ban instead of the one included with swag ?
I mounted the fail2ban.sqlite3 from my host 
`- /volume1/docker/fail2ban/fail2ban.sqlite3:dashboard/fail2ban.sqlite3:ro `
I use Crazy-max image of fail2ban because the fail2ban included in swag doesn’t come with ssmtp  to send emails with an auth smtp server …

**Comment by player666au** [comment]
the docs are incorrect:
in https://github.com/linuxserver/docker-mods/tree/swag-dashboard
the mount:
/path/to/host/fail2ban.sqlite3:/dashboard/fail2ban.sqlite3:ro
should be 
/path/to/host/fail2ban.sqlite3:/dashboard/fail2ban/fail2ban.sqlite3:ro

This worked for me.

**Comment by jon-f-novastor** [comment]
> the docs are incorrect: in https://github.com/linuxserver/docker-mods/tree/swag-dashboard the mount: /path/to/host/fail2ban.sqlite3:/dashboard/fail2ban.sqlite3:ro should be /path/to/host/fail2ban.sqlite3:/dashboard/fail2ban/fail2ban.sqlite3:ro
> 
> This worked for me.

Thanks for correcting this, they will need to update the documentation to point out how to do this correctly, as I too was not able to get it to work based on their original documentation to get the hosts fail2ban to report the jails, only the fail2ban hosted by docker-swag were shown.
