### ISSUE TITLE
New Branch Request - code-server-asdf

### ISSUE THREAD

**Issue by devRMA** [linuxserver/docker-mods#408]
I made a mod to install asdf, and I would like to create a pr.
Repo link: https://github.com/devRMA/code-server-asdf/tree/code-server-asdf

**Comment by aptalca** [comment]
We are just in the middle of switching the mods to be compatible with s6v3. Why don't we hold off on adding a new one until we finalize the new structure and make this compatible from the get go? Here's an example mod that supports both s6v2 and s6v3: https://github.com/linuxserver/docker-mods/tree/code-server-dotnet-s6v3

**Comment by devRMA** [comment]
All right, I'll wait.
