### ISSUE TITLE
New branch request - jellyfin-rffmpeg

### ISSUE THREAD

**Issue by junkman690** [linuxserver/docker-mods#450]
Request for new branch to be created to add rffmpeg support to Jellyfin https://github.com/junkman690/docker-mods/tree/jellyfin-rffmpeg

Allows remote transcoding on multiple hosts with optional WOL support.

**Comment by aptalca** [comment]
Here you go: https://github.com/linuxserver/docker-mods/tree/jellyfin-rffmpeg

**Comment by junkman690** [comment]
Thanks mate. Added pull request #451 which would close this one out
