### ISSUE TITLE
s6-rc-compile: fatal: unable to read /etc/s6-overlay/s6-rc.d/init-mods-package-install/type: No such file or directory

### ISSUE THREAD

**Issue by cfauvet** [linuxserver/docker-mods#484]
Hello, 

When redeploying the same docker compose that was working previously for months, I got this error visible on the running swag container:

```
s6-rc-compile: fatal: unable to read /etc/s6-overlay/s6-rc.d/init-mods-package-install/type: No such file or directory
[mod-init] Applying linuxserver/mods:swag-dashboard files to container
[mod-init] Attempting to run Docker Modification Logic
```
I checked the container, this file or directory is missing /etc/s6-overlay/s6-rc.d/init-mods-package-install/type

it works perfectly when removing  - DOCKER_MODS=linuxserver/mods:swag-dashboard from the docker compose file.

What am I missing?

**Comment by aptalca** [comment]
Make sure you pull the latest swag image before recreating

**Comment by Erriez** [comment]
Related to https://github.com/linuxserver/docker-swag/issues/260

I'm using the latest `image: ghcr.io/linuxserver/swag:version-1.29.0` and recreating the container does not work.

**Comment by Erriez** [comment]
Now it works after removing the Swag image and recreating the container. Thanks.

**Comment by cfauvet** [comment]
It's now working after pulling the last version of the Swag image. Thank you!

**Comment by aptalca** [comment]
> Related to [linuxserver/docker-swag#260](https://github.com/linuxserver/docker-swag/issues/260)
> 
> I'm using the latest `image: ghcr.io/linuxserver/swag:version-1.29.0` and recreating the container does not work.

You need to pull the image again to update your local image as described above.
