### ISSUE TITLE
> It's likely because the mods have been upgraded to a new version but the paperless-ngx images having had a rebuild since we updated our baseimages for these new version of the mods.

### ISSUE THREAD

**Issue by solluh** [linuxserver/docker-mods#492]
Which of the database options there do I need to use to migrate?

_Originally posted by @Openhabber in https://github.com/linuxserver/docker-mods/issues/490#issuecomment-1236321219_

This question is imho still open. How can I transfer my internal sqlite-database to postgres14? Is there a chance of export- and import?
TNX!

**Comment by j0nnymoe** [comment]
Our paperless-ngx container used sqlite by default. You will need to consult their documentation to see how to migrate to postgres.
