### ISSUE TITLE
Papermerge - failed install multilangocr

### ISSUE THREAD

**Issue by drSchaps** [linuxserver/docker-mods#495]
Hi,
I have install new default papermerge instance, but multilang mod failed to install. Interesting part of server log is here, but whole log and config files are attached too.

> papermerge    | [mod-init] Attempting to run Docker Modification Logic
> papermerge    | [mod-init] Applying "linuxserver/mods:papermerge-multilangocr" files to container
> papermerge    | tar (child): /modtarball.tar.xz: Cannot open: No such file or directory
> papermerge    | tar (child): Error is not recoverable: exiting now
> papermerge    | tar: Child returned status 2
> papermerge    | tar: Error is not recoverable: exiting now
> papermerge    | cp: cannot stat '/tmp/mod/*': No such file or directory
> papermerge    | [mod-init] "linuxserver/mods:papermerge-multilangocr" applied to container

Thank you for help
Regards

[papermerge_container.log](https://github.com/linuxserver/docker-mods/files/9524260/papermerge_container.log)
[docker-compose.txt](https://github.com/linuxserver/docker-mods/files/9524270/docker-compose.txt)
[papermerge.conf.py.txt](https://github.com/linuxserver/docker-mods/files/9524292/papermerge.conf.py.txt)

**Comment by aptalca** [comment]
It failed to download the mod. Try recreating the container

**Comment by drSchaps** [comment]
Hi aptalca,
thank you for quick reply. Unfortunately no difference after recreating. Could you give me a direct link to download? I'll try to download with wget on host.

[papermerge_container.log](https://github.com/linuxserver/docker-mods/files/9527190/papermerge_container.log)

**Comment by aptalca** [comment]
Mods are hosted as single layer docker images on ghcr and docker hub. The container downloads the image layer as a tarball

**Comment by drSchaps** [comment]
I removed all related docker images and created the container again - same error. Any ideas what's wrong? 
[papermerge_verbose_logs.txt](https://github.com/linuxserver/docker-mods/files/9576947/papermerge_verbose_logs.txt)

**Comment by miro-gk** [comment]
Hi, unfortunately, I faced the same issue, is there any update on how to resolve it? 
Thanks in advance for any assistance may be provided.

**Comment by huang12zheng** [comment]
@miro-gk @drSchaps Adding docker's registry-mirrors setting might solve your problem. 
That's what I just found out

**Comment by aptalca** [comment]
Mod is deprecated, closing
