### ISSUE TITLE
[not working] s6-rc.d/init-mods-package-install/type: No such file or directory

### ISSUE THREAD

**Issue by dluca22** [linuxserver/docker-mods#496]
Hi
I've installed code-server with python docker mods couple of months ago on my raspberry pi to access locally in my lan, used it a bit then stopped for a month or so

I was trying to access today and couldn't, looked through logs on portainer and i get
`[mod-init] Applying linuxserver/mods:code-server-python3 files to container`

`s6-rc-compile: fatal: unable to read /etc/s6-overlay/s6-rc.d/init-mods-package-install/type: No such file or directory`

I didn't rebuild the container or nothing, afaik it kept running togherer with other containers i've used.

tried deleting and re deploying and still wouldn't work.

Installed a new plain container without mods and it's working fine.
anyone had the same issue?
I lack technical knowledge and only things i could try is to run `docker exec` of the container and got to ping to www.google.com so I only got to know that it could connect to internet but i'm not able to access it anymore

edit:
also i tried adding the DOCKER-MOD evirnoment variable to the new container I just deployed and that was working fine, and got the same issue of it throwing the same error, then removed it and is working fine

**Comment by jaredallard** [comment]
Having this same issue with `openssh-server-ssh-tunnel`, it seems like every docker mod stopped working?

**Comment by aptalca** [comment]
pull the latest images and recreate the containers

**Comment by pearlythepirate** [comment]
I solved it by changing the image I was pulling from ghcr.io/linuxserver/swag:latest to just linuxserver/swag:latest - maybe that will help you OP?

**Comment by aptalca** [comment]
Both of those endpoints contain the same exact images. All you needed to do was `docker pull imagename` or `docker compose pull` and then recreate

**Comment by dluca22** [comment]
> Both of those endpoints contain the same exact images. All you needed to do was `docker pull imagename` or `docker compose pull` and then recreate

I'll try it asap when I get back home.
I don't remember if i tried docker pull or not, it was late at night
