### ISSUE TITLE
Setup script tries to install Debian packages on the Alpine-based image and fails.

### ISSUE THREAD

**Issue by Nocifer** [linuxserver/docker-mods#499]
Ever since the migration to the Alpine-based image, I've been getting the following error when booting with the python3 mod applied (and I suspect I'd get it with any other mod as well, since they probably install and run the same way):

```
s6-rc: info: service init-mod-code-server-python3-add-package: starting
/etc/s6-overlay/s6-rc.d/init-mod-code-server-python3-add-package/run: line 3: dpkg: command not found
**** Adding python3 to package install list ****
s6-rc: info: service init-mod-code-server-python3-add-package successfully started
s6-rc: info: service init-mods-package-install: starting
**** Installing all mod packages ****
fetch http://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  build-essential (no such package):
    required by: world[build-essential]
  libssl-dev (no such package):
    required by: world[libssl-dev]
  python3-pip (no such package):
    required by: world[python3-pip]
  python3-venv (no such package):
    required by: world[python3-venv]
```

The error is because AFAICT the setup script unconditionally tries to run `dpkg -l` and then install Debian packages instead of running `apk info` and then opting to install the equivalent Alpine packages. If I change the script to this:

```
#!/usr/bin/with-contenv bash

if ! apk info | grep python3 > /dev/null; then
    echo "**** Adding python3 to package install list ****"
    echo "\
        build-base \
        libressl-dev \
        libffi-dev \
        python3 \
        py3-pip \
        py3-virtualenv" >> /mod-repo-packages-to-install.list
else
    echo "**** python3 already installed ****"
fi

```

...and proceed to manually run it, everything goes smoothly.

It's been more than a few months since the migration to Alpine and I've not seen any bug reports about this issue, which means that either nobody else is using the python3 mod and so the error has gone unnoticed, or nobody else is getting this error and so I'm the one who's doing something wrong on my end. Perhaps there is some manual step required when switching from the Debian- to the Alpine-based image that I'm not aware of?

Any input would be appreciated.

**Comment by aptalca** [comment]
That mod is for code server and openvscode server only, as listed in its readme. Neither of those images are alpine based.

**Comment by Nocifer** [comment]
I was about to reply that on the Docker Hub page for all LinuxServer images there is a section about Docker Mods that links to this repository, but after reading it a bit more carefully I realize that for each image there are a couple of links that point to specific mods that can be applied to it. So, it turns out that it is indeed my fault!

So, since the specific image I have in mind does include it in its list of mods, am I correct to assume that the proper way to do what I want is to use the `universal-package-install` mod instead of this one?

**Comment by aptalca** [comment]
Right, for each image there is a list of specific mods for that image (if any) and a list of universal mods that should work with all images (with the exception of universal-calibre being ubuntu only).

Yes, you can use `universal-package-install` for installing python in any image
