### ISSUE TITLE
[swag-dashboard] Unknown applications showing up in Swag Dashboard

### ISSUE THREAD

**Issue by Unlimited0012** [linuxserver/docker-mods#501]
Two unknown applications showed up in Swag Dashboard.

There are no active proxy confs for either of these applications, and there are no set subdomains for them in my yml file.

The applications are:
- http://audiobookshelf:80/
   - Available: YES
   - Proxied: NO
   - Location: (this field is blank)
- http://tasmobackup:80/
   - Available: YES
   - Proxied: NO
   - Location: (this field is blank)

I've seen one other report on Reddit with the user reporting "tasmobackup" and "documentserver" randomly showing up similarly.

**Comment by aptalca** [comment]
That just means your dns resolves both of those hostnames from inside SWAG and something responds to requests on those IPs and port 80. But they are not reverse proxied by SWAG.

**Comment by Unlimited0012** [comment]
@aptalca thank you.

Could you help me understand? 
Does this mean that there are services on my server broadcasting those hostnames?

**Comment by aptalca** [comment]
The only things for sure are (iirc) 
1) your dns (or rather docker dns) is resolving those hostnames to some IP(s) and
2) those IPs are listening and responding on port 80

**Comment by MilesTEG1** [comment]
I was having the same issue with the exact same domain. But I was not using those.
I see that when I delete the .sample file corresponding to those domains, they were gone.

But since the yesterady update of swag, the dashboard doesn't show any proxies now:
![image](https://user-images.githubusercontent.com/29298312/191983202-4270acc9-e5d5-404d-80f0-c9efbe2de5ce.png)

**Comment by Unlimited0012** [comment]
@MilesTEG1 Evidently the main issue of unknown applications showing up was sorted out on the linuxserver discord. I forget the exact specifics, but essentially it's not threatening.

I haven't noticed my proxies missing as yours are though.

**Comment by Shiwigy** [comment]
I also have the exact same problem, it's an easy fix if you edit /dashboard/swag-proxies.py line 13

FROM
    file_paths = glob.glob("/config/nginx/**/**", recursive=True)
TO
    file_paths = glob.glob("/config/nginx/**/*.conf", recursive=True)

It seems it picks up every available file by default, with the change above it only process the files "enabled" *.conf and not the *.conf.sample files

**Comment by MilesTEG1** [comment]
Hello,
I forgot I had post here.
The problem disappears after the big update recently, and when I had to move all my custom .conf from /site-confs/ to proxy-confs/ : all unwanted proxy entry in the dashboard was gone.

**Comment by Original-Gekko** [comment]
> I also have the exact same problem, it's an easy fix if you edit /dashboard/swag-proxies.py line 13
> 
> FROM file_paths = glob.glob("/config/nginx/**/**", recursive=True) TO file_paths = glob.glob("/config/nginx/**/*.conf", recursive=True)
> 
> It seems it picks up every available file by default, with the change above it only process the files "enabled" *.conf and not the *.conf.sample files

I have the same exact problem too on a fresh install of swag and swag dashboard and this modification you provided also fixed it.

I still have one issue.
It's showing me the Version Updates of /config/nginx/proxy-confs/dashboard.subdomain.conf which is already up to date
![image](https://github.com/linuxserver/docker-mods/assets/142528674/80040a6b-c431-4473-a9d0-0c7fe6096fd8)

Everything else is working fine.
