### ISSUE TITLE
DBIP: geoip2db folder

### ISSUE THREAD

**Issue by ghost** [linuxserver/docker-mods#509]
When I tried to set up the DBIP mod with SWAG, SWAG wouldn't start.  Checkign the logs, I saw a message that "dbip-country-lite.mmdb" in "geoip2db" directory  couldn't be reached as the directory didn't exist.

I shut down SWAG, created the directory and was able to restart SWAG.  "dbip-country-lite.mmdb" was created in the "geoip2db" directory automatically.

I'm just reporting this  in case it is not expecrted behaviour or, if it is, to suggest adding the info to the walkthrough.
Apologies if this is not the correct place to post this.

**Comment by drizuid** [comment]
Please fill out the issue template properly

**Comment by Huisie** [comment]
My apologies, but where do I find info about the issue template, please?

**Comment by drizuid** [comment]
When you clicked new issue, there was a template to be filled out. you need to provide your full compose, docker version, how you installed docker, and container logs.

**Comment by Huisie** [comment]
Hi, drizuid - I'm afraid I didn't get any of that.  I tried clicking on the "new issue" button now, to test it - all I get is a Title field and a text box to type in.  I reviewed several other posts under "Issues" and that seems to be standard.  I didn't see any that followed a template.

**Comment by aptalca** [comment]
oops, just realized the issue template is not added to this repo (because our jenkins doesn't touch this)
But you can find the template and what information is needed in the SWAG repo here: https://github.com/linuxserver/docker-swag/blob/master/.github/ISSUE_TEMPLATE/issue.bug.md

**Comment by drizuid** [comment]
> Hi, drizuid - I'm afraid I didn't get any of that. I tried clicking on the "new issue" button now, to test it - all I get is a Title field and a text box to type in. I reviewed several other posts under "Issues" and that seems to be standard. I didn't see any that followed a template.

Our mistake and thank you for letting us know!  That said, if you can provide the info i mentioned we can try to assist.

**Comment by Huisie** [comment]
### Expected Behavior
SWAG starts with DB-IP mod active and geoip2db directory automatically created in SWAG /config directory, to contain dbip-country-lite.mmdb MaxMind DB file.

### Current Behavior
SWAG doesn't start, error message is: 

> nginx: [emerg] MMDB_open("/config/geoip2db/dbip-country-lite.mmdb") failed - Error opening the specified MaxMind DB file in /config/nginx/dbip.conf:1

To resolve this, I had to create the geoip2db directory manually.

### Steps to reproduce
**Error:**
Stop SWAG (SSH: docker stop swag)
rename geoip2db directory (old-geoip2db)
Restart SWAG (SSH: docker-compose up -d swag)
SWAG doesn't start up, receive error message as listed under Current Behavior

**Resolve:**
Stop SWAG (SSH: docker stop swag)
rename geoip2db directory (geoip2db)
Restart SWAG (SSH: docker-compose up -d swag)
SWAG start up properly

### Commands Used
docker-compose pull swag
docker-compose up -d swag

>     swag:
>         image: lscr.io/linuxserver/swag
>         container_name: swag
>         cap_add:
>             - NET_ADMIN
>         environment:
>             - PUID=$PUID
>             - PGID=$PGID
>             - TZ=$TZ
>             - DOCKER_MODS=linuxserver/mods:swag-dashboard|linuxserver/mods:swag-dbip
>             - URL=mydomain.me
>             - SUBDOMAINS=wildcard
>             - VALIDATION=dns
>             - DNSPLUGIN=cloudflare
>             - EMAIL=myemailaddress@myemailprovider.com
>         volumes:
>             - $DOCKER/swag:/config
>         ports:
>             - "443:443"
>             - "81:81"
>         restart: always

**Comment by poldim** [comment]
I'm getting a similar error:
![image](https://user-images.githubusercontent.com/16869713/201537399-16fe8df4-9b1f-46c2-a2bb-01e16637dbf8.png)

**Comment by OpieO1** [comment]
I had the same problem. I found that starting the container did not create /config/geoip2db. I manually created the folder and it was then able to move the database from /tmp to /config/geoip2db.

**Comment by Huisie** [comment]
Hi, Opie01

I had to do the same which was why i raised the issue. Not a big deal but a little confusing for those less technically adept like myself.  Glad to see you figured it out.


Hi, Poldim

Sorry I missed your comment, hope you managed to get it sorted.

**Comment by OlivierMartinez** [comment]
I had the same problem than found this thread. Thank you ! Manually creating the folder did the job !
