### ISSUE TITLE
Hugo Mod

### ISSUE THREAD

**Issue by WoosterInitiative** [linuxserver/docker-mods#51]
Please create a branch for code-server-hugo that I can create a Hugo mod for code-server.

**Comment by aptalca** [comment]
@WoosterInitiative please fork and checkout the `template` branch and make your changes in your forked repo. When it's ready, ping me here or discord and share a link to your branch. We'll then create a new branch for the mod here and ask you to PR against that.

Thanks

**Comment by aptalca** [comment]
Closing for now. Reopen if/when ready.
