### ISSUE TITLE
swag-auto-proxy: use multiple sub-domains for a Docker

### ISSUE THREAD

**Issue by Aerya** [linuxserver/docker-mods#515]
Hi,

I'm trying to use this mod using multiple sub-domains for a Docker. ie domain.tld, blog.domain.tld, www.domain.tld

I see each time I reload SWAG, the auto-proxy-XXX.subdomain.conf is rewrite.
I also tried using labels but it doesn't work. ie swag_url=domain.tld,blog.domain.tld,www.domain.tld

Thanks

**Comment by aptalca** [comment]
Not officially supported but if you use spaces instead of commas between the urls, it will likely work
