### ISSUE TITLE
feature request: swag-auto-proxy: multiple names in swag_url=

### ISSUE THREAD

**Issue by RichBrew** [linuxserver/docker-mods#518]
in docker-mod 'swag-auto-proxy', please add a method to add multiple values to swag_url label

for example, if i want to have 2 or more addresses that will proxy the 'organizr' container
organizr.* (organizr.domain.com) -> organizr
home.* (home.domain.com) -> organizr
test.* (test.domain.com) -> organizr

possible usage:
swag_address=containername|home|test
or 
swag_address=organizr|home|test
or
swag_address=containername.domain.com|home.domain.com|test.domain.com
or 
swag_address=organizr.domain.com|home.domain.com|test.domain.com

**Comment by aptalca** [comment]
you can already do that, they'd have to be space delimited like 
```
  labels:
    - "swag_url=blah.domain.com blah2.domain.com"
```
