### ISSUE TITLE
code-server-rust

### ISSUE THREAD

**Issue by luisalrp** [linuxserver/docker-mods#519]
Hello,

I did a docker mod to add rust to code-server. Could you check if I did properly? I am not sure if I did it well.

[https://github.com/luisalrp/docker-mods/tree/template](https://github.com/luisalrp/docker-mods/tree/template)

Thanks.

**Comment by aptalca** [comment]
Remove all unnecessary lines, don't just comment out
Remove all unnecessary init and service files
Dockerfile needs to be sorted out
Readme needs sorted out
Needs to be hybrid (v2 and v3)

**Comment by luisalrp** [comment]
Thanks! I did several changes. How I test that I've done it properly?

**Comment by aptalca** [comment]
You can locally build, push to docker hub and use its image name to add to code server as a mod

**Comment by huang12zheng** [comment]
@luisalrp Are there any new developments?

**Comment by huang12zheng** [comment]
error happen in
'/Users/huangzheng/rusts/docker-mods/root/etc/s6-overlay/s6-rc.d/init-mod-code-server-rust-add-package/run'.
sorry for my noisy.

**Comment by huang12zheng** [comment]
https://github.com/huang12zheng/docker-mods/tree/code-server-rust

1. Note that for always, apt-get seems to be installed all the time.
2. rustup is installed incorrectly, but can be used normally(compile something like surrealdb).
3. I don't know how to pr to this repo
