### ISSUE TITLE
Flutter Mod

### ISSUE THREAD

**Issue by flavio20002** [linuxserver/docker-mods#53]
Hi, 
I've created a mod for developing browser Flutter Apps.

https://github.com/flavio20002/docker-mods/tree/code-server-flutter

If you like it, I would like to push it on your repository.

Thanks

Flavio

**Comment by aptalca** [comment]
Looks good, but I'd much prefer it if it was versioned and had a separate tag for betas (pre-releases). I'll play with it a little and send a PR to your repo.

**Comment by aptalca** [comment]
@flavio20002 I looked into it more and versioning it is more trouble than its worth. Your implementation works, and it allows users to upgrade via `flutter upgrade` in code-server terminal if they need to.

Couple of suggestions:
- Please use the `stable` branch (currently beta is older than stable)
- Please add `flutter config --no-analytics`

When ready, you can PR to this branch: https://github.com/linuxserver/docker-mods/tree/code-server-flutter

Thanks

**Comment by flavio20002** [comment]
Hi, the problem is that browser support in Flutter is still beta ([link]( https://flutter.dev/docs/get-started/web)). Without browser support, Flutter is not so useful in code server (still, one could run unit and widget tests, or could connect to remote adb, if install another mod for Android developing). I could create two docker dags, one called code-server-flutter and the other code-server-flutter-beta. What do you think? 
Thanks

**Comment by aptalca** [comment]
Google always makes their releases so confusing, which is very frustrating. Beta seems to be at version `1.20.0-7.4.pre` whereas stable is at `1.20.1`.
Anyway, let's go by that page and assume beta and stable are parallel but separate tracks.

No reason to do 2 separate mods. You can leave it on beta for now and once that browser support is merged to stable, we can switch it to stable.

Thanks.

**Comment by flavio20002** [comment]
Closed with https://github.com/linuxserver/docker-mods/pull/55
