### ISSUE TITLE
New branch request - code-server-ros2

### ISSUE THREAD

**Issue by greinet** [linuxserver/docker-mods#530]
Request for a new branch to be created to add ROS2 to code-server and openvscode-server.
Repository link: https://github.com/greinet/docker-mods/tree/code-server-ros2

This adds the Robot Operating System (ROS), specifically [ROS2 Humble](https://docs.ros.org/en/humble/index.html), a set of libraries and tools to create robot applications.

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-mods/tree/code-server-ros2
