### ISSUE TITLE
Jellyfin AMD Mod Tonemapping not working - OpenCL drivers missing?

### ISSUE THREAD

**Issue by Joly0** [linuxserver/docker-mods#533]
The Problem i have can be read here https://github.com/jellyfin/jellyfin/issues/8030
Its the exact same problem. I have got the docker to work with my amd igpu, though tone mapping doesnt work, i only get an opencl error. 
I guess it should be possible to integrate the missing driver (if thats the problem, but i think so) into the docker mod.

**Comment by aptalca** [comment]
@PascalMinder is the maintainer for that mod

**Comment by PascalMinder** [comment]
As I understand it, the mod would need to install in addition to the already installed 
`mesa-vdpau-drivers mesa-va-drivers mesa-vdpau-drivers libdrm-radeon1` the additional `amdgpu-install` script?

**Comment by Joly0** [comment]
> As I understand it, the mod would need to install in addition to the already installed 
> `mesa-vdpau-drivers mesa-va-drivers mesa-vdpau-drivers libdrm-radeon1` the additional `amdgpu-install` script?
> 
> - [amdgpu](https://amdgpu-install.readthedocs.io/en/latest/install-script.html)
> - [Jellyfin Docs - HW transcoding](https://jellyfin.org/docs/general/administration/hardware-acceleration/#opencl--cuda--intel-vpp-tone-mapping)

As far as i understood, yes. The amdgpu-install script with the additional opencl arguments is needed
