### ISSUE TITLE
New branch request: qbittorrent-vuetorrent

### ISSUE THREAD

**Issue by RoboMagus** [linuxserver/docker-mods#534]
Request for a branch to be created for a docker-mod that installs [vuetorrent](https://github.com/WDaan/VueTorrent) UI for qBittorrent.

Link to created mod: https://github.com/RoboMagus/docker-mods/tree/qbittorrent-vuetorrent

**Comment by RoboMagus** [comment]
Just saw another issue for the same idea, but it's a stale one: #212.

**Comment by RoboMagus** [comment]
@aptalca, thoughts?
(Would this be a worthy addition?)

**Comment by aptalca** [comment]
It looks like you just unzip somewhere (config folder?) and point to it in the gui? Is a mod really needed?
I'm not against it, if you want to create a mod for it, go ahead.

As is, there are some issues with it, though. The readme mentions versioning, but there is no versioning in the mod itself. Also, the mod only adds the gui settting to qbit conf if there is no qbit conf, which can create two potential issues: does it mess with qbit's ability to create and manage the config file? and it doesn't enable it for existing users.

**Comment by RoboMagus** [comment]
Closing, as i'm no longer a user myself
