### ISSUE TITLE
Striptrack not able to remove all subtitles

### ISSUE THREAD

**Issue by deepika05** [linuxserver/docker-mods#537]
Striptrack has an option shown in the help as:
:eng ""                     # Keep English audio and no subtitles

but trying it out results in:
root@83436882dc6a:/data/media/tvshows/xxxx# /usr/local/bin/striptracks.sh -d 2 -f yyy.mkv :eng ""                                                                                                                  
Debug|Enabling debug logging level 2. Starting Batch run for: yyy                              
Error|No subtitles languages specified or detected! 

I'm able to get the script to do its thing by specifying :eng :eng 

On the same vein, the option i'm really looking for is to strip out all subtitles. so my end goal is to do :Any ""
Thanks!

**Comment by TheCaptain989** [comment]
Let me take a look, I like buggered up something.  It is intended to work like the documentation says.

**Comment by TheCaptain989** [comment]
I've updated the code.  Could you please test it?  You'll have to modify your DOCKER_MODS variable to pull my develop branch as follows: `DOCKER_MODS=thecaptain989/radarr-striptracks:latest`

**Comment by deepika05** [comment]
thanks! this works. i did figure out a workaround using postprocessing in bazarr. in my case, the bazarr postprocessing helps with extracting the subtitle before removing it. this mod is the cleaner way to do it. so i'm sure this will help other users! thanks again for your quick response!
