### ISSUE TITLE
Swag ffmpeg mod

### ISSUE THREAD

**Issue by sanmadjack** [linuxserver/docker-mods#54]
I've branched template and created a mod to install ffmpeg in swag, it's at https://github.com/sanmadjack/docker-mods/tree/swag-ffmpeg-pull

I'd like to submit it to the official mod repo if you'll have it.

**Comment by aptalca** [comment]
Looks great, but please add a MAINTAINER label [like here](https://github.com/linuxserver/docker-mods/blob/code-server-nodejs/Dockerfile#L3). Then you can PR to this branch: https://github.com/linuxserver/docker-mods/tree/swag-ffmpeg

**Comment by sanmadjack** [comment]
Should I add my name as maintainer, or yours like in the example?

**Comment by j0nnymoe** [comment]
Add yourself :)
