### ISSUE TITLE
dbip-country-lite.mmdb file nowhere to be found

### ISSUE THREAD

**Issue by aldialloMC** [linuxserver/docker-mods#545]
Hi all and Merry Christmas,

I've followed the tutorial to get this mod installed but I'm running into and error after restarting my stack.

As you can see below during the initialization of the stack the file dbip-country-lite.mmdb.gz is downloaded but it's unabled to be copied to the /config/geoip2db folder stating that the folder does not exist.

Here's what I see in the container logs:

`Applying the dbip mod...
**** Applying the SWAG dashboard mod... ****
Downloading GeoIP2 City database.
**** Configuring CrowdSec nginx Bouncer ****
**** Goaccess already installed and up to date ****
**** libmaxminddb already installed, skipping ****
Connecting to download.db-ip.com (172.67.75.166:443)
**** Applied the SWAG dashboard mod ****
s6-rc: info: service init-mod-swag-dashboard-add-package successfully started
saving to '/tmp/dbip-country-lite.mmdb.gz'
dbip-country-lite.mm  98% |******************************* | 3294k  0:00:00 ETA
dbip-country-lite.mm 100% |********************************| 3349k  0:00:00 ETA
'/tmp/dbip-country-lite.mmdb.gz' saved
mv: cannot move '/tmp/dbip-country-lite.mmdb' to '/config/geoip2db/dbip-country-lite.mmdb': No such file or directory
Applied the dbip mod
s6-rc: info: service init-mod-swag-dbip-setup successfully started`

I've created the directory manually and I'm still getting the same error and also I tried to move the file manually but can't find the downloaded file in the /tmp directory.

Any idea of what I'm doing wrong here?

Here's my stack, created and run on Portainer

`---
version: "3.8"

secrets:
  JWT_SECRET:
    file: ./data/authelia/secrets/JWT_SECRET
  STORAGE_ENCRYPTION_KEY:
    file: ./data/authelia/secrets/STORAGE_ENCRYPTION_KEY
volumes:
  swag:
  authelia:

networks:
  net:
    driver: bridge

services:
  swag:
    container_name: swag
    image: lscr.io/linuxserver/swag
    restart: unless-stopped
    networks:
      net:
        aliases: []
    ports:
      - 80:80
      - 443:443
      - 81:81

    volumes:
      - ./data/swag:/config
      - ./data/authelia/config/authelia.log:/authelia/authelia.log:ro
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
      URL: domain.Ttld
      SUBDOMAINS: wildcard
      VALIDATION: dns
      CERTPROVIDER: cloudflare
      DNSPLUGIN: cloudflare
      DOCKER_MODS: linuxserver/mods:swag-dbip|linuxserver/mods:swag-dashboard|linuxserver/mods:swag-mod2|linuxserver/mods:swag-crowdsec

      EMAIL: SECRETE
      CROWDSEC_API_KEY: ALSO_SECRET
      CROWDSEC_LAPI_URL: http://crowdsec:8080      
    cap_add:
      - NET_ADMIN
        
  authelia:
    container_name: authelia
    image: authelia/authelia
    restart: unless-stopped
    networks:
      net:
        aliases: []
    expose:
      - 9091
    secrets: [JWT_SECRET, SESSION_SECRET, STORAGE_PASSWORD, STORAGE_ENCRYPTION_KEY]  
    volumes:
      - ./data/authelia/config:/config
    environment:
      TZ: Europe/Paris
      AUTHELIA_JWT_SECRET_FILE: /run/secrets/JWT_SECRET
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /run/secrets/STORAGE_ENCRYPTION_KEY
      AUTHELIA_SESSION_NAME: authelia_session
      AUTHELIA_SESSION_DOMAIN: domain.tld
      AUTHELIA_SESSION_SAME_SITE: lax
      AUTHELIA_SESSION_EXPIRATION: 1h
      AUTHELIA_SESSION_INACTIVITY: 5m
      AUTHELIA_STORAGE_LOCAL_PATH: /config/db.sqlite3
      AUTHELIA_NOTIFIER_FILESYSTEM_FILENAME: /config/notification.txt
      AUTHELIA_AUTHENTICATION_BACKEND_FILE_PATH: /config/users_database.yml
      AUTHELIA_THEME: dark
      AUTHELIA_ACCESS_CONTROL_DEFAULT_POLICY: deny
      #AUTHELIA_ACCESS_CONTROL_NETWORKS: 10.0.1.0/24, 172.16.0.0/12
      
  crowdsec:
    container_name: crowdsec
    image: crowdsecurity/crowdsec
    restart: unless-stopped
    environment:
      - COLLECTIONS=crowdsecurity/nginx
      - GID=1000
    depends_on:
      - swag
    volumes:
      - ./data/swag/log/nginx:/var/log/nginx
      - ./crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml
      - ./crowdsec/crowdsec-db:/var/lib/crowdsec/data/
      - ./crowdsec/crowdsec-config:/etc/crowdsec/
    security_opt:
      - no-new-privileges=true      
...
`

**Comment by Turiok** [comment]
Hi,

I have the same problem.
For me it's because the folder is not created.
In this script : https://github.com/linuxserver/docker-mods/blob/17612a0ca537495df2a93ba4f9a94350069090d5/root/etc/s6-overlay/s6-rc.d/init-mod-swag-dbip-setup/run#L9 

It miss a `mkdir /config/geoip2db`

The module swag-maxmind create it : https://github.com/linuxserver/docker-mods/blob/swag-maxmind/root/etc/s6-overlay/s6-rc.d/init-mod-swag-maxmind-setup/run
