### ISSUE TITLE
Add memories mod for nextcloud

### ISSUE THREAD

**Issue by JonathanTreffler** [linuxserver/docker-mods#546]
The [Memories](https://apps.nextcloud.com/apps/memories) Nextcloud App requires perl5 as a dependency.
I created a simple mod at: https://github.com/JonathanTreffler/docker-mods/tree/nextcloud-memories with the BuildImage Action modified to push it to https://hub.docker.com/r/tessypowder/docker-mods

If you create a branch for it I can create a Pull Request to get it into the list of official mods.

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-mods/tree/nextcloud-memories

**Comment by cravas** [comment]
Hello all
Just to inform that the README.MD is showing `RSYNC - Docker Mod for openssh-server`
![image](https://github.com/linuxserver/docker-mods/assets/21242022/fdc2e3e4-ab5a-4613-b1c6-109199e5eecc)

Cheers

**Comment by Roxedus** [comment]
Thats because OP havent created a PR to get his changes merged.
