### ISSUE TITLE
calibre mod missing new dependencies

### ISSUE THREAD

**Issue by Ramblurr** [linuxserver/docker-mods#547]
As reported [over here](https://github.com/linuxserver/docker-calibre-web/issues/219) the docker calibre mod is missing some (apparently) new deps.

After updating my calibre-web setup, I had to disable the mod to get it working. Would be nice to have the docker mod working again for conversions.

**Comment by juergenpf** [comment]
I've a similar problem. When trying to use the admin function to update the app inside the container, it loops and complains that it is missing PyPi module Flask-Limiter.
This update used to work a while ago.

**Comment by aptalca** [comment]
We don't support updating apps inside the container. You need to pull the new docker image and recreate the container.

As posted in the linked issue, the calibre mod also works fine. There are errors logged but they are harmless and do not affect the functionality.
