### ISSUE TITLE
geoip2.conf to maxmind.conf not working - db not downloading

### ISSUE THREAD

**Issue by nodiaque** [linuxserver/docker-mods#549]
Hello,

I just updated my swag from 1.31.0-ls152 to latest tag and I saw some warning about configuration needed to be updated. One is that it found a geoip2.conf and I need to move to maxmind module.

I followed the instruction on this page
https://github.com/linuxserver/docker-mods/tree/swag-maxmind

I created an account and acquired a key. I added the env variable with my key, removed the geoip2.conf file and added the mod. My current mod list is:

linuxserver/mods:universal-docker|linuxserver/mods:swag-auto-reload|linuxserver/mods:swag-auto-proxy|linuxserver/mods:swag-dashboard|linuxserver/mods:swag-maxmind

I restarted the container and wanted to follow the next step to include maxmind.con but the file wasn't created. Thus, I copied the content from 
https://github.com/linuxserver/docker-mods/blob/swag-maxmind/root/defaults/maxmind.conf and created the file, then include the conf in nginx.conf and restart.

Now, I'm getting error that the DB cannot be found

nginx: [emerg] MMDB_open("/config/geoip2db/GeoLite2-City.mmdb") failed - Error opening the specified MaxMind DB file in /config/nginx/maxmind.conf:1

During the load sequence, I'm getting message
**** libmaxminddb already installed, skipping ****

I'm not sure where to go from there.

I'm on unraid 6.9.2.

Thank you

**Comment by BIGFAAT** [comment]
Copying manually the database once solved the problem for now.

**Comment by quietsy** [comment]
Check your license key, if it's valid `/config/geoip2db/GeoLite2-City.mmdb` will be downloaded.
If it already exists and still throws the same error try to delete it and restart the container, it will be downloaded again.

**Comment by nodiaque** [comment]
When you create the licence, there is multiple different option. This is not documented, maybe it's because it doesn't care?
