### ISSUE TITLE
InfluxDB v2 support

### ISSUE THREAD

**Issue by Coolgam3r2152** [linuxserver/docker-mods#551]
Is there a chance this can be compatible with influxdb v2?

**Comment by aptalca** [comment]
Needs a lot more context and info. GitHub issues are not for questions. Not even clear which mod is being referred to.

**Comment by Coolgam3r2152** [comment]
Oh shoot didnt even realize that the mod was in this. The mod Im talking about is the geoip2influx mod

**Comment by Coolgam3r2152** [comment]
Oh shoot didnt even realize that the mod was in this. The mod Im talking about is the geoip2influx mod
