### ISSUE TITLE
code-server-golang Path error

### ISSUE THREAD

**Issue by Beariful** [linuxserver/docker-mods#555]
I am receiving an error when code-server-golang is initializing. I am unable to access go from the vscode server terminal, in order to use the go command I must path out to /usr/local/go/bin. I believe the path is not being added to the path environment correctly. 

> grep: /etc/services.d/code-server/run: No such file or directory
> sed: can't read /etc/services.d/code-server/run: No such file or directory 

I verified that there is no directory named code-server in /etc/services.d when the container is running.

I believe this error is related to the following lines of code (3-13) from [the init-mod-code-server-golang-add-package/run file](https://github.com/linuxserver/docker-mods/blob/code-server-golang/root/etc/s6-overlay/s6-rc.d/init-mod-code-server-golang-add-package/run)

**Comment by aptalca** [comment]
you can add it to profile or bashrc or other relevant file as they are all in the persistent `/config` folder
