### ISSUE TITLE
Java Mod

### ISSUE THREAD

**Issue by flavio20002** [linuxserver/docker-mods#57]
Hi, 
I'm developing a Java Code Server Mod. My first idea is to create multiple versions (just one branch like code-server-go mod), i.e. code-server-java-8, code-server-java-11, etc and use alternative ([url](https://dev.to/thegroo/install-and-manage-multiple-java-versions-on-linux-using-alternatives-5e93) as a mean to change the version. In this way, one could install multiple mod and switch between versions if needed.
What do you think?

Flavio

**Comment by aptalca** [comment]
Sure, go for it

**Comment by flavio20002** [comment]
Hi, I've done it: https://github.com/flavio20002/docker-mods/tree/code-server-java

**Comment by aptalca** [comment]
@flavio20002 sorry I've been busy and kinda ignored this one. Here's a branch you can PR to: https://github.com/linuxserver/docker-mods/tree/code-server-java

**Comment by aptalca** [comment]
looking through the dockerfile, there is no versioning beyond the major version, which means the versioning would have to be handled entirely by the trigger.

The api linked is only referencing the latest build and not the versions. Is there an endpoint there to query the latest minor version so we can use that for the trigger?

**Comment by aptalca** [comment]
closing for now, you can reopen if you'd like to revisit
