### ISSUE TITLE
swag-dashboard : Flooding DNS server with requests with default swag config

### ISSUE THREAD

**Issue by hadjilucasL** [linuxserver/docker-mods#570]
Hi,

I got a warning on my DNS server about many concurrent requests from the host on which SWAG is hosted.

Like many attempts to resolve services like:

```
adguard
adguard.mydomain.com
adminer
adminer.mydomain.com
adminmongo
adminmongo.mydomain.com
...
```

At first I thought something was compromised and someone was scanning my local network but upon investigation it turns out this behaviour is coming from the SWAG Dashboard.

The culprit is down to the code [here](https://github.com/linuxserver/docker-mods/blob/6e6ddfb166974561599e55ca3ea94591990e1fd1/root/dashboard/swag-proxies.py#L13). 

From my experience when first setting up SWAG, the default config included all these [reverse proxy config samples](https://github.com/linuxserver/reverse-proxy-confs) that are only activated if you rename the suffix from `.conf.sample` to `.conf`. These are placed in the ` /config/nginx/proxy-confs` directory. This is indicated in the SWAG documentation as well [here](https://docs.linuxserver.io/general/swag#preset-proxy-confs).

From looking at the code, SWAG Dashboard globs all files in the nginx conf directory, including the samples and as a result it spams a lot of concurrent connections that might otherwise look like someone malicious is probing.

This behaviour also gave rise to issue #501.

The suggestion is to rework the code as to at least only glob files ending in `.subdomain.conf` or `.subfolder.conf`.

**Comment by aptalca** [comment]
It's not a bug. It is intended behavior

**Comment by hadjilucasL** [comment]
Thanks for the response @aptalca . 

I am not quite sure I understand how is this intended behaviour ? The files ending in `.sample` are not being considered as active in nginx. Yet they are present as per default configuration to facilitate users. So anyone enabling SWAG Dashboard will inevitably be making a number of connection attempts to these yet-to-be-enabled configurations. Why add these in the applications being scanned ? 

Furthermore some DNS servers do impose warnings on the number of concurrent connections (e.g. pihole is set at 150). The current code will launch a large number of threads without rate limitation and attempt to connect to all sample reverse proxy configurations. There are currently 270 samples so it can add up every time you visit the SWAG Dashboard page.

**Comment by aptalca** [comment]
A feature of the dashboard is to show you if you have any of those known services running but not reverse proxied (perhaps not properly activated).

The dns warning is a false positive so not something that needs fixing on the dashboard's side.

**Comment by hadjilucasL** [comment]
But by default, only the ones ending in `.conf` are considered in nginx, not the ones ending in `.sample`. I feel you are making a lot of connection attempts without cause by scanning these sample files. 

Why not just restrict it to `.conf` files ? SWAG itself by will only reverse proxy configurations in these files.

**Comment by aptalca** [comment]
How would we find out about services not reverse proxied yet if we only scanned the conf files?

**Comment by hadjilucasL** [comment]
Why would SWAG DAshboard need to know about services not under the SWAG `proxy-conf` directories ?

To my understanding SWAG Dashboard is presented as a complement to existing SWAG installations. So if a user enabled this mod on their current SWAG configuration, the expectations is to analyse and provide details on the existing SWAG configuration - not scan my network to find services users have not configured in SWAG.

The Dashboard page itself only has a `Proxies` heading. So it does not mention non-reverse-proxied services. I believe it can be confusing for someone to see services they have not configured in SWAG pop up there.

![image](https://user-images.githubusercontent.com/295876/215268040-4475d88b-c40f-42ee-ba72-e94a11739f28.png)

**Comment by aptalca** [comment]
I explained it above. If you have for instance overseerr running but you forgot to reverse proxy it, or didn't do it properly, it would list it and show a green checkmark under `Available`, and a red X under `Proxied`.

**Comment by hadjilucasL** [comment]
Hmm ok. I believe SWAG Dashboard is perhaps trying to do too much ? I believe it's behaviour should be restricted to the configuration of SWAG - it is the SWAG Dashboard after all. 

Users may have enabled other services, outside of SWAG, in subdomains or subfolders that match the sample files. I do not believe it is correct behaviour for this mod to be scanning those, outside of the SWAG domain. I don't feel it should be trying to discover things a user has not configured in SWAG explicitly - even if it is for the sake of discovering misconfigurations. 

Perhaps this can be added as a secondary option so the user can consciously opt in or out ? I leave the choice to you.

The reason I am making a note of this is also because of the effect this has. Below is a graph of the DNS requests over my network for the past few hours. There are 20-30 devices running here and yet SWAG Dashboard is responsible for the two spikes of over 1,000 DNS requests. This hopefully indicates how this behaviour is not typical wrt to other services running on the network and some users might be puzzled by it.

![image](https://user-images.githubusercontent.com/295876/215268781-834a7761-67fb-4b01-b37e-28af4b0893db.png)

**Comment by hadjilucasL** [comment]
Just some final thoughts.. given I understood how the code works, it will probably also speed up loading the dashboard as it will typically be doing far fewer connection attempts.

**Comment by aptalca** [comment]
I don't personally consider an increase in dns queries to be an issue. Answering queries is what a dns resolver is for. 

What you're asking for is for us to remove a feature that some users (including me) find useful because you experienced a warning from your dns resolver which was a false positive.

We'll consider it but removal is not likely.

**Comment by hadjilucasL** [comment]
Although this issue started off with the DNS requests - that is just a side effect. 

The main point I would reconsider is whether SWAG Dashboard should be performing arbitrary service discovery i.e. it tries to ping services users do not have active in SWAG configuration. I believe it should be limited in only parsing configuration that has been explicitly made active by the user - e.g. by renaming `nextcloud.subdomain.conf.sample` -> `nextcloud.subdomain.conf`. That is all.

**Comment by aptalca** [comment]
I don't know how else to tell you that it's a feature and it's behaving as intended. It does service discovery with a predefined list of known services. Looking at conf files only would break that functionality.

Arguing with us on this is like asking Toyota to remove all air conditioners from their cars because you don't use it and argue that a car's main function is to take you from point a to point b and that it shouldn't get involved in climate control. Sure, you may not use/need/want it and it does add weight and reduce gas mileage, but other people do and it's here to stay.

**Comment by hadjilucasL** [comment]
If you intend to keep this as is, I've opened a PR to make the docs a bit more clear how it works. Feel free to merge it if you are happy with the wording.

**Comment by hadjilucasL** [comment]
I will close the issue now. If you intend to keep the functionality then feel free to also close/not-merge PR #571. Have a nice weekend!
