### ISSUE TITLE
code-server-nodejs mod: npm version is outdated

### ISSUE THREAD

**Issue by phirestalker** [linuxserver/docker-mods#573]
I did an image pull only last week, so my image is pretty up to date. I just installed something with npm in the code-server console with one of my projects loaded. It informed me `New major version of npm available! 6.14.17 → 9.4.0`. That is a big jump. I was under the impression that nodejs was updated each time I rebuilt the image?

Can something be added to this mod so that it updates npm along with nodejs?

**Comment by thespad** [comment]
The mod specifically installs node 14, with whatever version of npm comes along with it

https://github.com/linuxserver/docker-mods/blob/code-server-nodejs/root/etc/s6-overlay/s6-rc.d/init-mod-code-server-nodejs-add-package/run#L11

It does probably need bumping, but we need to be careful about people who are expecting it to remain version 14. Might be something we can make configurable.

**Comment by phirestalker** [comment]
That makes sense. A configurable option would be awesome. I guess we could
make it the node version number we want installed?

**Comment by Roxedus** [comment]
As this is a system-wide install, allowing to install any node version may break code-server itself.

**Comment by thespad** [comment]
Looks like 16.x is the currently supported version for code-server https://github.com/coder/code-server/blob/main/docs/npm.md#nodejs-version

**Comment by aptalca** [comment]
Did you give this a try?
https://github.com/linuxserver/docker-mods/tree/code-server-nvm

**Comment by phirestalker** [comment]
> Did you give this a try? https://github.com/linuxserver/docker-mods/tree/code-server-nvm

Do I use this instead of code-server-nodejs or use both?

**Comment by colwellkr** [comment]
> > Did you give this a try? https://github.com/linuxserver/docker-mods/tree/code-server-nvm
> 
> Do I use this instead of code-server-nodejs or use both?
> 
> EDIT: nevermind, figured it out.

What ended up working for you?

**Comment by aptalca** [comment]
Nodejs mod is being updated to support passing the desired node version in an env var called `NODEJS_MOD_VERSION`

https://github.com/linuxserver/docker-mods/pull/642 should be merged within a day or so
