### ISSUE TITLE
mod initialization times out

### ISSUE THREAD

**Issue by ReenigneArcher** [linuxserver/docker-mods#575]
I have spent a lot of time diagnosing this issue, so I will try to be as detailed as possible.

I develop 3 docker mods. Two are plugins for Plex, and one is a plugin for Jellyfin.

In the past day I have one user for one of my Plex plugins, and one user for the Jellyfin plugin report that they cannot install the mod, and get an error like this.

```txt
2023-02-04 22:49:07 [mod-init] Attempting to run Docker Modification Logic
2023-02-04 22:49:07 [mod-init] Applying lizardbyte/themerr-plex:nightly files to container
2023-02-04 22:50:12 tar (child): /modtarball.tar.xz: Cannot open: No such file or directory
2023-02-04 22:50:12 tar (child): Error is not recoverable: exiting now
2023-02-04 22:50:12 tar: Child returned status 2
2023-02-04 22:50:12 tar: Error is not recoverable: exiting now
2023-02-04 22:50:12 cp: cannot stat '/tmp/mod/*': No such file or directory
2023-02-04 22:50:12 [mod-init] lizardbyte/themerr-plex:nightly applied to container
2023-02-04 22:50:12 [migrations] started
2023-02-04 22:50:12 [migrations] no migrations found
```

I'm also able to replicate the issue. So I dug in a bit using the image in the above logs. Here is what I found.

| tag | docker registry result | ghcr registry result |
| --- | --- | --- |
| v0.0.1 | ✅ | ❌ |
| v0.0.2 | ✅ | ❌ |
| v0.0.3 | ✅ | ❌ |
| v0.0.4 | ✅ | ❌ |
| v0.0.5 | ✅ | ❌ |
| v0.0.6 | ✅ | ❌ |
| v0.0.7 | ✅ | ❌ |
| v0.0.8 | ✅ | ❌ |
| v0.1.0 | ✅ | ❌ |
| v0.1.1 | ❌ | ❌ |
| v0.1.1 | ❌ | ❌ |
| v0.1.2 | ❌ | ❌ |
| v0.1.3 | ❌ | ❌ |

There are possibly two issues going on here, since every image on ghcr is failing. I can pull those images using `docker pull ghcr.io/lizardbyte/themerr-plex:<tag>`.

There was no change in the structure of the image I publish between v0.1.0 and v0.1.1. This is the commit where it starts to break on docker hub. https://github.com/LizardByte/Themerr-plex/commit/7595dcc32f500fc8c1c6a5f1e99f044abcc55716 (note: the CI file modified here is not the one responsible for publishing to docker)

Additionally, the user reported that they could v0.0.7 and v0.0.8, but not v0.1.0 or anything after it. Which is slightly different than my findings.

Anyway, digging into the logic of the docker mod script, this is the responsible part of the code.

```bash
        echo "[mod-init] Applying ${DOCKER_MOD} files to container"
        # Get Dockerhub token for api operations
        TOKEN="$(
            curl -f --retry 10 --retry-max-time 60 --retry-connrefused \
                --silent \
                --header 'GET' \
                "${AUTH_URL}" |
                jq -r '.token'
        )"
        # Determine first and only layer of image
        SHALAYER=$(get_blob_sha "${MODE}" "${TOKEN}" "${MANIFEST_URL}")
        # Check if we have allready applied this layer
        if [[ -f "/${FILENAME}" ]] && [[ "${SHALAYER}" == "$(cat /"${FILENAME}")" ]]; then
            echo "[mod-init] ${DOCKER_MOD} at ${SHALAYER} has been previously applied skipping"
        else
            # Download and extract layer to /
            curl -f --retry 10 --retry-max-time 60 --retry-all-errors \
                --silent \
                --location \
                --request GET \
                --header "Authorization: Bearer ${TOKEN}" \
                "${BLOB_URL}${SHALAYER}" -o \
                /modtarball.tar.xz
            mkdir -p /tmp/mod
            tar xzf /modtarball.tar.xz -C /tmp/mod
            if [[ -d /tmp/mod/etc/s6-overlay ]]; then
                if [[ -d /tmp/mod/etc/cont-init.d ]]; then
                    rm -rf /tmp/mod/etc/cont-init.d
                fi
                if [[ -d /tmp/mod/etc/services.d ]]; then
                    rm -rf /tmp/mod/etc/services.d
                fi
            fi
            shopt -s dotglob
            cp -R /tmp/mod/* /
            shopt -u dotglob
            rm -rf /tmp/mod
            rm -rf /modtarball.tar.xz
            echo "${SHALAYER}" >"/${FILENAME}"
            echo "[mod-init] ${DOCKER_MOD} applied to container"
        fi
```

The second `curl` command seems to be failing, and there is no error handling of that command.

These issues also seem related, but don't go into much detail.

- https://github.com/linuxserver/docker-mods/issues/531
- https://github.com/linuxserver/docker-mods/issues/496
- https://github.com/linuxserver/docker-mods/issues/495

**Comment by thespad** [comment]
Short version: your mods are breaking for several different reasons.

Your GHCR mods contain multi-arch manifests, which is why they've never worked, as our mod logic assumes a single manifest record. *Why* only your GHCR images (until v0.1.1) container multi-arch manifests and not the DH ones I can't tell you.

Your DH and GHCR mods post v0.1.1 are using the `application/vnd.oci.image.manifest.v1+json` mediatype instead of `application/vnd.docker.distribution.manifest.v2+json`, and include attestation layers in the manifest, both of which are likely buildkit-related changes.

At the moment our mod logic doesn't set an Accept header for `application/vnd.oci.image.manifest.v1+json` so will never receive those manifests, we'll need to get that changed because it's going to become a common change going forward.

**Comment by ReenigneArcher** [comment]
Thanks for the answer.

Although, the docker hub containers are multi arch as well. Images for both registries are built at the same time and pushed to each registry using docker's GitHub actions.

![image](https://user-images.githubusercontent.com/42013603/216835776-75fc22e8-a87b-45ec-90af-f0740d8e064f.png)

![image](https://user-images.githubusercontent.com/42013603/216835430-057f9de1-3567-4693-9529-a89df92ff577.png)

**Comment by ReenigneArcher** [comment]
Thanks to your comment, found some info on the manifest here: https://github.com/docker/build-push-action/issues/755

**Comment by thespad** [comment]
I'm going to dig into properly supporting more complex manifests but it's not going to be an overnight change - the logic is lot more complicated than what we currently do for mods and despite supposedly supporting the same API, DH and GHCR do things differently enough to need different flows for each.

**Comment by ReenigneArcher** [comment]
I'd prefer not to change the `provenance` setting, so I'll follow this issue for updates.

One final question though. Does, or can the mod logic handle getting the correct architecture of the mod image based on the base image arch?

I don't currently have anything in the images that is arch specific, but don't know if that will change in the future when some dependency is added. I mostly just set it to multi arch to match the arches of the base image, although I can set just a single arch for now, if needed.

**Comment by thespad** [comment]
At the moment, no, but it's something I'll look at as part of this. It's extremely fiddly though because of how the manifests handle the arch, i.e.
```json
      "platform": {
        "architecture": "amd64",
        "os": "linux"
      }
```
For amd64 but
```json
      "platform": {
        "architecture": "arm",
        "os": "linux",
        "variant": "v7"
      }
```
For arm32 and then
```
      "platform": {
        "architecture": "unknown",
        "os": "unknown"
      }
```
For the attestation layers

**Comment by aptalca** [comment]
Just to add that, our mod implementation is all about storing and retrieving a single tarball. (We use the registries as merely a storage platform).

Therefore it only supports a single image, single layer and thus a single tarball. No manifests or multi arch.

**Comment by ReenigneArcher** [comment]
Thanks! I'll periodically check the base images for updates. Much appreciated!

**Comment by ReenigneArcher** [comment]
> Note that the above PR will take days/weeks to flow into downstream images so don't expect anything immediate.

How do I know when the images have been updated with this change? I've seen commits to both the plex and jellyfin images but don't see any reference to mods in the commits. Not sure if I would even see any commit in those images or how your build process is set up.

**Comment by thespad** [comment]
Yeah it's because the changes are to the mods script which gets pulled into the base images, not the downstream ones. Simplest check is `docker exec foo grep "MULTIDIGEST" /docker-mods`, if that exists then it's using the updated version of the mods script.

**Comment by aptalca** [comment]
This should have waterfalled to all images by now. Closing.
