### ISSUE TITLE
nginx: [emerg] "geoip2" directive is not allowed here in /config/nginx/maxmind.conf:1

### ISSUE THREAD

**Issue by scubieman** [linuxserver/docker-mods#578]
nginx: [emerg] "geoip2" directive is not allowed here in /config/nginx/maxmind.conf:1

Having this error and can not figure this out. I tried googling and nothing.

**Comment by yolanv** [comment]
Hey @scubieman, how did you manage to solve this? Bumping into the same issue.

**Comment by scubieman** [comment]
> Hey @scubieman, how did you manage to solve this? Bumping into the same issue.

not 100% sure, i believe i just started upgrading the packages and once complete it took care of it.

**Comment by yolanv** [comment]
> 

Thanks for the fast reply. Which packages are you talking about? I did a docker pull from the SWAG image. Is there more I should update? (other than the maxmind mod)
