### ISSUE TITLE
Applying mods without 'linuxserver' prefix results with 'tar' error

### ISSUE THREAD

**Issue by labmonkey** [linuxserver/docker-mods#585]
Hello, I am using the latest docker-swag image although this issue possibly might be same for other images.

When I define my mods as follows:
`- DOCKER_MODS=mods:swag-maxmind|mods:swag-cloudflare-real-ip|mods:swag-crowdsec`

Then the swag logs are as below. Additionally each mod takes about 30sec to load and output the error:
```
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying mods:swag-maxmind files to container
tar: can't open '/modtarball.tar.xz': No such file or directory
cp: cannot stat '/tmp/mod/*': No such file or directory
[mod-init] mods:swag-maxmind applied to container
[mod-init] Applying mods:swag-cloudflare-real-ip files to container
tar: can't open '/modtarball.tar.xz': No such file or directory
cp: cannot stat '/tmp/mod/*': No such file or directory
[mod-init] mods:swag-cloudflare-real-ip applied to container
[mod-init] Applying mods:swag-crowdsec files to container
tar: can't open '/modtarball.tar.xz': No such file or directory
cp: cannot stat '/tmp/mod/*': No such file or directory
[mod-init] mods:swag-crowdsec applied to container
```

When I define my mods as follows:
`- DOCKER_MODS=linuxserver/mods:swag-maxmind|linuxserver/mods:swag-cloudflare-real-ip|linuxserver/mods:swag-crowdsec`

Then the swag logs are as below. Everything loads in 1 second:
```
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying linuxserver/mods:swag-maxmind files to container
[mod-init] linuxserver/mods:swag-maxmind applied to container
[mod-init] Applying linuxserver/mods:swag-cloudflare-real-ip files to container
[mod-init] linuxserver/mods:swag-cloudflare-real-ip applied to container
[mod-init] Applying linuxserver/mods:swag-crowdsec files to container
[mod-init] linuxserver/mods:swag-crowdsec applied to container
```

**Comment by thespad** [comment]
Well yes, if you set `DOCKER_MODS=mods:swag-maxmind` you're asking the container to download `docker.io/mods:swag-maxmind`, which doesn't exist.

**Comment by labmonkey** [comment]
Ah ok stupid me. I though some mods don't have linuxserver prefix and it turned out to be just my mistake when copying name from some guide.

Well then what would you say about a feature request so that there is a nice error message when you try to add a non existing mod? I mean typos can happen so it would be way better to have a message like "requested mod does not exist, check if the name is correct" instead of tarball error

**Comment by thespad** [comment]
We have some improvements in the works for mod error handling, but the problem is there's no way for us to tell if a given repo is a valid mod or not without trying to download them, at which point they'll hang for ~30 seconds until the connection times out.
