### ISSUE TITLE
[Question:] Use local image as mod

### ISSUE THREAD

**Issue by bettinaheim** [linuxserver/docker-mods#602]
I could not figure out how to use a local docker image as a mod;
When I run a container with
```
docker run -d --name=code-server -p 8443:8443 -e DOCKER_MODS=<name_of_local_image> --restart unless-stopped linuxserver/code-server:latest
```
I see an error
```
[mod-init] <name_of_local_image> could not be found on dockerhub
```

How is it possible to test a mod locally to confirm functionality before pushing it anywhere?

**Comment by thespad** [comment]
You can't, it has to be pushed to a Docker Hub or GHCR repo somewhere to be accessible to the mod logic. There's no way for it to access a docker image on the local host.

**Comment by bettinaheim** [comment]
Thanks for the quick reply! 
That is unfortunate. Consider this a feature request then. :)

**Comment by thespad** [comment]
There's no practical way to do it. You'd need to mount the docker socket into the container, and we'd have to write custom logic to extract an image through it.

The only possible option would be supporting a local registry, but even that is likely to be more effort than it's worth - I'll have a look at what's involved though.

**Comment by bettinaheim** [comment]
Could you clarify if a mod that is a docker image built from the Dockerfile

```
FROM scratch
COPY --from=<a custom but public registry>/<image_name> / /
```
would work?

**Comment by thespad** [comment]
If that image was subsequently pushed to a registry, yes. The way the mod logic works is that it downloads the single image layer tarball from the registry and extracts it locally inside the image.

**Comment by bettinaheim** [comment]
One last maybe naive question: If the mod is fairly large (a couple of GB), is it possible to avoid that it needs to be re-downloaded every time the code-server is launched with that mod (other than creating an image based off of the running container)?

**Comment by thespad** [comment]
Not really. The whole mod has to be downloaded every time the container is recreated.

Your only option would be to make the mod small, and have it download the large payload on init into persistent storage so it could check on startup and only download if the data is missing.

Honestly probably not a great mod candidate if it's that big though.

**Comment by ravensorb** [comment]
> There's no practical way to do it. You'd need to mount the docker socket into the container, and we'd have to write custom logic to extract an image through it.
> 
> The only possible option would be supporting a local registry, but even that is likely to be more effort than it's worth - I'll have a look at what's involved though.

@thespad if your interested I have a version of the docker-mod script that works with any registry that follows the docker standards.  Right now its based off of the v2 docker-mod script and I was about to start migrated it to your latest v3.

**Comment by thespad** [comment]
I'm happy to take a look at the changes you've made and see if we can integrate them into the existing mod script; support for local registries is extremely niche but there's no real reason not to support it if we can.

**Comment by ravensorb** [comment]
@thespad  -- here is the current script (Based on the v2 of the docker-mod) if you want to have a quick look

https://gist.github.com/ravensorb/8f95adada527eeb02074a7454f90d3f8

High-level, what it does is:
- Parses the docker-mod out into components - registry (optional), repository, image, version (optional), hash (optional)
- Attempts to the manifest and parses the "www-authenticate" header to get the correct info for the auth token
- Request the auth token based on the results from the previous step
- Pulls down the manifest, and if it is a multi-archi makes a 2nd call to pull down the 1st platforms manifest
- Optionally validates the hash from the DOCKER_MOD against the digest in the manifest
- Downloads and applies the mod

**Comment by ravensorb** [comment]
@thespad I updated the gist with a 2nd file.  It is a shell script that can be run locally to test the updated script (it will skip the container specific steps and then download and apply the mods to a local path).
