### ISSUE TITLE
Unable to use multiple mods

### ISSUE THREAD

**Issue by abrockhoff** [linuxserver/docker-mods#605]
attempting to use multiple mods with the following env variable setup
`-e DOCKER_MODS=linuxserver/mods:swag-dashboard|linuxserver/mods:swag-dbip|linuxserver/mods:swag-f2bdiscord \`

This is the error I get

`Current status: 127 (Interrupted)
Standard output/error:
/bin/bash: line 10: linuxserver/mods:swag-dbip: No such file or directory
/bin/bash: line 11: linuxserver/mods:swag-f2bdiscord: No such file or directory
"docker run" requires at least 1 argument.
See 'docker run --help'.`

**Comment by aptalca** [comment]
wrap it in quotes

**Comment by abrockhoff** [comment]
Thank!

**Comment by AD-Wright** [comment]
Can that be mentioned in the README?  
Current text:
 - DOCKER_MODS- This can be a single endpoint `user/endpoint:tag` or an array of endpoints separated by `|` `user/endpoint:tag|user2/endpoint2:tag`   

Suggested revision:
 - DOCKER_MODS- This can be a single endpoint `user/endpoint:tag` or an array of endpoints separated by `|` and enclosed by quotes, e.g. `DOCKER_MODS="user/endpoint:tag|user2/endpoint2:tag"`

**Comment by aptalca** [comment]
Quotation depends on how the vars are set and it's ultimately the users' responsibility
