### ISSUE TITLE
code-server-dotnet

### ISSUE THREAD

**Issue by pegasy** [linuxserver/docker-mods#61]
Hi.
I made a fork and branch for adding dotnet (3.1 and 2.1 as of now) as a mod for code-server
Branch is here: https://github.com/pegasy/docker-mods/commits/code-server-dotnet

**Comment by aptalca** [comment]
@pegasy sorry for the delay, here's a branch you can PR to: https://github.com/linuxserver/docker-mods/tree/code-server-dotnet

**Comment by aptalca** [comment]
Digging into your branch, I noticed that it uses the repo to install, but MS docs state that the repo only contains the x86_64 package: https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#unable-to-find-package

If we do manual install, the latest versions get a bit complicated to retrieve. For each runtime release, there seem to be 2 sdk releases, for different versions of visual studio (I have no idea what the differences are and which one we need): https://dotnet.microsoft.com/download/dotnet-core/3.1

Therefore, there doesn't seem to be a simple endpoint to retrieve latest versions other than scraping that webpage (I'm still digging)

**Comment by aptalca** [comment]
Found this which would be extremely useful: https://github.com/dotnet/core/blob/master/release-notes/3.1/releases.json
We just need to parse the current supported versions first (ie. `3.1` and `2.1`)
