### ISSUE TITLE
Mod IonCube Loader

### ISSUE THREAD

**Issue by justfor-it** [linuxserver/docker-mods#615]
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║      
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
using keys found in /config/keys
**** Installing Ioncube Loader ****
**** Linux architecture found: x86-64 ****
**** PHP Version found: 8.1.x ****
**** Downloading Ioncube Loader... ****
Connecting to downloads.ioncube.com (192.241.136.243:443)
saving to '/tmp/ioncube_loaders_lin_x86-64.tar.gz'
ioncube_loaders_lin_   9% |**                              | 1312k  0:00:09 ETA
ioncube_loaders_lin_  65% |*********************           | 9392k  0:00:01 ETA
ioncube_loaders_lin_ 100% |********************************| 13.9M  0:00:00 ETA
'/tmp/ioncube_loaders_lin_x86-64.tar.gz' saved
**** Ioncube Loader downloaded: ioncube_loaders_lin_x86-64.tar.gz ****
**** Extracting Ioncube Loader... ****
ioncube/
ioncube/ioncube_loader_lin_5.0.so
ioncube/ioncube_loader_lin_4.3.so
ioncube/ioncube_loader_lin_7.0_ts.so
ioncube/ioncube_loader_lin_4.2.so
ioncube/ioncube_loader_lin_5.6.so
ioncube/ioncube_loader_lin_7.1.so
ioncube/ioncube_loader_lin_5.3.so
ioncube/ioncube_loader_lin_7.3_ts.so
ioncube/ioncube_loader_lin_5.5_ts.so
ioncube/ioncube_loader_lin_5.4.so
ioncube/loader-wizard.php
ioncube/ioncube_loader_lin_4.3_ts.so
ioncube/ioncube_loader_lin_5.5.so
ioncube/LICENSE.txt
ioncube/USER-GUIDE.pdf
ioncube/ioncube_loader_lin_5.4_ts.so
ioncube/ioncube_loader_lin_7.4_ts.so
ioncube/ioncube_loader_lin_7.0.so
ioncube/ioncube_loader_lin_5.3_ts.so
ioncube/ioncube_loader_lin_4.4.so
ioncube/ioncube_loader_lin_4.4_ts.so
ioncube/ioncube_loader_lin_7.4.so
ioncube/ioncube_loader_lin_7.3.so
ioncube/ioncube_loader_lin_7.1_ts.so
ioncube/ioncube_loader_lin_7.2_ts.so
ioncube/ioncube_loader_lin_5.2.so
ioncube/USER-GUIDE.txt
ioncube/ioncube_loader_lin_4.1.so
ioncube/README.txt
ioncube/ioncube_loader_lin_5.1_ts.so
ioncube/ioncube_loader_lin_7.2.so
ioncube/ioncube_loader_lin_8.1.so
ioncube/ioncube_loader_lin_5.0_ts.so
ioncube/ioncube_loader_lin_8.1_ts.so
ioncube/ioncube_loader_lin_5.1.so
ioncube/ioncube_loader_lin_5.6_ts.so
ioncube/ioncube_loader_lin_5.2_ts.so
**** Ioncube Loader extracted: /usr/local/ioncube ****
/etc/s6-overlay/s6-rc.d/init-mod-swag-ioncube-setup/run: line 37: /etc/php8/conf.d/00-ioncube.ini: No such file or directory
**** Ioncube Loader PHP extension enabled: ioncube_loader_lin_8.1.so ****
**** Ioncube Loader Installed ****
[custom-init] No custom files found, skipping...
[ls.io-init] done.

Ioncube will not install in nginx. docker compose

**Comment by aptalca** [comment]
@Spunkie it seems the script is looking for php in the wrong folder (`8` vs `81`): https://github.com/linuxserver/docker-mods/blob/swag-ioncube/root/etc/s6-overlay/s6-rc.d/init-mod-swag-ioncube-setup/run#L38
