### ISSUE TITLE
New branch request: swag-cloudflare-dyndns-updater

### ISSUE THREAD

**Issue by kytay** [linuxserver/docker-mods#616]
Request for a new branch to be created to add cloudflare-dyndns-updater to swag.
Repository link: https://github.com/kytay/docker-mods/tree/swag-cloudflare-dyndns-updater

This mod provides feature for SWAG, when deployed as a public facing reverse proxy, to update cloudflare on ip address changes.

**Comment by aptalca** [comment]
Please give me a couple of days. I have a few improvements to add to the template first. You can ping me in a week if I forget.

**Comment by aptalca** [comment]
Here it is: https://github.com/linuxserver/docker-mods/tree/swag-cloudflare-dyndns-updater
