### ISSUE TITLE
[SWAG Dashboard] Any way to show the swag_address and public port(s) in an extra row under "Proxies"?

### ISSUE THREAD

**Issue by GlassedSilver** [linuxserver/docker-mods#633]
This would really be helpful to discern services when you work with manual setups a lot.

For example:

- services running not on the same docker host are accessed by IP of the secondary host
- services running in docker's default bridge network rather than all being on the same docker network to keep them more isolated

That way the public address is your reference, something that should always be rather identifiable.

**Comment by GlassedSilver** [comment]
Please kindly unstale this, thank you

**Comment by GlassedSilver** [comment]
unstale please

**Comment by GlassedSilver** [comment]
Bot begone :D

**Comment by GlassedSilver** [comment]
unstale

**Comment by quietsy** [comment]
I didn't fully understand the request.
How can the dashboard know these details?
I can have a proxy for `radarr.*`, it will catch requests to any domains starting with `radarr.`.
