### ISSUE TITLE
Universal Cloudflare no longer working (Invalid tarball, could not download linuxserver/mods:universal-cloudflared)

### ISSUE THREAD

**Issue by sunbear87** [linuxserver/docker-mods#634]
The linuxserver/mods:universal-cloudflared mod refuses to install at docker creation. No matter what I do I get this error at startup and it fails to install the mod:

`Invalid tarball, could not download linuxserver/mods:universal-cloudflared`

I've been trying to use it with the nextcloud docker for a couple days now to no avail. I've tried deleting and rebuilding my docker image.

I was hoping someone else was seeing this but the log line returns nothing on google.

Any ideas?

**Comment by aptalca** [comment]
Works fine here. Probably networking issues

**Comment by sunbear87** [comment]
Any recommendations for where I should start troubleshooting?

**Comment by sunbear87** [comment]
All my other docker mods including linuxserver ones are working fine.

**Comment by sunbear87** [comment]
Is there someway I can download and install the mod manually?

**Comment by sunbear87** [comment]
Had to roll back to linuxserver/mods:universal-cloudflared-2023.4.1 to get it functional again.
