### ISSUE TITLE
SAbnzbd Mod

### ISSUE THREAD

**Issue by DisasteR** [linuxserver/docker-mods#65]
Hi,

needed git inside sabnzbd image to run nzbtomedia.

https://github.com/DisasteR/docker-mods/tree/sabnzbd-git

can you validate and create the branch so i can PR ?

Regards,

**Comment by aptalca** [comment]
Did you try this locally?

I'm guessing no 😉 because sab is ubuntu based, not alpine: https://github.com/linuxserver/docker-sabnzbd/blob/master/Dockerfile#L1

**Comment by DisasteR** [comment]
Oops !
I did it mechanically, so used to using alpine. :D
Just fixed it :)

**Comment by DisasteR** [comment]
@aptalca it is ok for you ?

**Comment by aptalca** [comment]
The mod is fine, but I'm thinking it would be better as a generic mod as it applies to many images we provide, not just sab. We just need to have a discussion within the team on how we would handle generic mods going forward in terms of promoting. Currently, the mod badge only displays the image specific mods.

**Comment by DisasteR** [comment]
@aptalca I agree with that generic mods will be the perfect match for that type of feature. have you already some idea of how to handle them ?

**Comment by aptalca** [comment]
@DisasteR we finally figured out how to tackle universal mods. We're adding a second badge to all readmes for the universal ones and the git one was the first test: https://github.com/linuxserver/docker-diskover#docker-mods
The readme updates should happen during image package checks throughout the week.

**Comment by DisasteR** [comment]
@aptalca really good news. Thanks for your work.
