### ISSUE TITLE
Request for cloudflared mod to not publish new cnames

### ISSUE THREAD

**Issue by ksurl** [linuxserver/docker-mods#717]
I have a wildcard cname published for my domain to point to my existing tunnel. you could instead publish a new/update cname such as tunnel.domain.com to point to the tunnel or just create a wildcard directly? this way there is no clutter of cnames for each service

**Comment by aptalca** [comment]
I don't follow. Please provide examples, confs, and/or screenshots

**Comment by ksurl** [comment]
so when you setup this mod, it will publish cname entries on your domain for each service defined in the config. such as plex.domain.com, tautulli.domain.com and they point to the new tunnel that was created.

I currently run the tunnel standalone with an existing tunnel, a cname named tunnel.domain.com pointing to the tunnel domain (blah.cftunnel.com or something). and then a wildcard cname pointing to the tunnel, *.domain.com to tunnel. I guess that can be simplified to just pointing to the tunnel instead of another cname. this basically does not publicize the services you are running.

Instead of creating a new tunnel cname, just have the option via ENV to set cname=yes (publish individual cnames as it does currently, by default) or cname=wildcard and have it publish *.domain.com to point to the tunnel and no further entries created.

**Comment by ksurl** [comment]
Would you be open to a pr to implement this with default behavior remaining the same as it is currently?

**Comment by aptalca** [comment]
I personally wouldn't be because I wouldn't want to get stuck with support and maintenance for a feature that would benefit so few.

**Comment by ksurl** [comment]
Ok I'll keep using the separate container then.
