### ISSUE TITLE
Update conf sample to include http2

### ISSUE THREAD

**Issue by halorrr** [linuxserver/docker-mods#721]
The [dashboard sample config](https://github.com/linuxserver/docker-mods/blob/swag-dashboard/root/dashboard/dashboard.subdomain.conf.sample) needs to be updated to be like https://github.com/linuxserver/reverse-proxy-confs/pull/576

The current version causes warnings:
```
nginx: [warn] protocol options redefined for 0.0.0.0:443 in /config/nginx/proxy-confs/dashboard.subdomain.conf:53
nginx: [warn] protocol options redefined for [::]:443 in /config/nginx/proxy-confs/dashboard.subdomain.conf:54
```

**Comment by Mat-DB** [comment]
I still have this issue and I have the latest version of dashboard.subdomain.conf with the http2.

`swag  | nginx: [warn] protocol options redefined for 0.0.0.0:443 in /config/nginx/proxy-confs/dashboard.subdomain.conf:72
swag  | nginx: [warn] protocol options redefined for [::]:443 in /config/nginx/proxy-confs/dashboard.subdomain.conf:73`

**Comment by halorrr** [comment]
resolved in https://github.com/linuxserver/docker-mods/commit/fad06b553e740ca910940320fc6f42b335b85ee6
