### ISSUE TITLE
New branch request: transmission-transmission-web-control

### ISSUE THREAD

**Issue by FujiZ** [linuxserver/docker-mods#723]
Request for a new branch to be created to add transmission-web-control back to transmission.
Repository link: https://github.com/FujiZ/docker-mods/tree/transmission-transmission-web-control

This mod provides a web UI called  Transmission Web Control for transmission. It was once removed when transmission was upgraded to v4.0.

**Comment by FujiZ** [comment]
Does anybody have time to check this issue?

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-mods/tree/transmission-transmission-web-control
