### ISSUE TITLE
[Jellyfin rffmpeg mod] Native WoL from outside NAT.

### ISSUE THREAD

**Issue by a-priestley** [linuxserver/docker-mods#727]
For those with more complicated network topologies, broadcast magic packet may not be enough.
My set up at the moment requires sending the packet to the WAN side of the switch, targeting a port mapped to the specific machine I want to wake, along with that machines MAC address.
Is it feasible to implement?

**Comment by aptalca** [comment]
@junkman690

**Comment by a-priestley** [comment]
I made a small edit to the `root/usr/bin/wol_rffmpeg/wol` script, with some extra environment variables for wol port and IP. It seems to work now but may require more testing.
Do you accept PRs?
