### ISSUE TITLE
radarr: striptracks

### ISSUE THREAD

**Issue by TheCaptain989** [linuxserver/docker-mods#73]
I created PR #72 for this mod.  Hopefully I did that right.
Also, not sure how to handle the fact that the mod works in both Radarr and Sonarr containers.

**Comment by TheCaptain989** [comment]
After thinking on it, I think I messed up.  I issued the PR against your master branch, when I should have waited for you to create the new branch.

**Comment by aptalca** [comment]
no worries, we'll fix that

**Comment by TheCaptain989** [comment]
Thanks for your review and help.
Any suggestions on getting the mod published to the Sonarr container also?  I was hoping to do it in a way without maintaining different code bases as that was the reason I merged them in the first place.  When I was building my own radarr/sonarr containers I had Docker build hooks that would auto build both containers from a single PR.

**Comment by aptalca** [comment]
The mod listing is handled through this yaml: https://github.com/linuxserver/docker-mods/blob/master/mod-list.yml

I'll add it to both so it will show up on both readmes

**Comment by aptalca** [comment]
listed under both: https://mods.linuxserver.io/

**Comment by TheCaptain989** [comment]
Awesome!  Thanks.
