### ISSUE TITLE
universal-cron broken for baseimage-kasmvnc:arch

### ISSUE THREAD

**Issue by TonyPrindel** [linuxserver/docker-mods#730]
Hi!

I'm attempting to use universal-cron to get cron running under the kasmvnc arch image. However, when trying to run it through Docker, I get a series of errors in my Docker logs. On top of this, kasmvnc doesn't seem to be loading, and trying to enter into the Docker's shell leads to some weird behavior.

For reference, I'm running 

`docker run --rm -it -e DOCKER_MODS=linuxserver/mods:universal-cron -p 3000:3000 ghcr.io/linuxserver/baseimage-kasmvnc:arch`

on my test machine. After some of the initial usual output I would expect, it seems the container gets hung up at:

```
**** cron package already installed, skipping ****
/etc/s6-overlay/s6-rc.d/init-mod-universal-cron-setup/run: line 12: crontab: command not found
/etc/s6-overlay/s6-rc.d/init-mod-universal-cron-setup/run: line 22: crontab: command not found
/etc/s6-overlay/s6-rc.d/init-mod-universal-cron-setup/run: line 28: crontab: command not found
/etc/s6-overlay/s6-rc.d/init-mod-universal-cron-setup/run: line 38: crontab: command not found
s6-rc: warning: unable to start service init-mod-universal-cron-setup: command exited 127
```

After this, nothing happens and I'm unable to access the container through vnc. Removing the mod from the run arguments makes everything work as expected.

This issue was reproduced on Debian 12 and on unRAID. Any guidance is appreciated.

**Comment by aptalca** [comment]
Our published mods only support our ubuntu and alpine based images, which constitute the great majority of our images. Only a couple of images are based on other distros, which are mainly kasmvnc based (incl webtop and digikam).

Also, I noticed you're using a baseimage in your tests, which is not meant for end user consumption.

If you let us know what your end goal is, we can perhaps provide a more helpful answer/solution.

**Comment by TonyPrindel** [comment]
Thanks for the quick reply!

> Our published mods only support our ubuntu and alpine based images, which constitute the great majority of our images. Only a couple of images are based on other distros, which are mainly kasmvnc based (incl webtop and digikam).

That clears that up, thanks. :)

> If you let us know what your end goal is, we can perhaps provide a more helpful answer/solution.

Right now I'm just wanting to set up a very simple Docker container with cron to run yt-dlp on a timer. I was originally going to start from scratch, but I figured I would try out y'all's cron mod since I had already been working with the kasmvnc image for some other stuff.

**Comment by TonyPrindel** [comment]
Just switched over to the alpine318 image and it works like a charm. Thank you very much!
