### ISSUE TITLE
PIP packages install failing due to PEP 668

### ISSUE THREAD

**Issue by UNCode101** [linuxserver/docker-mods#738]
I have been using universal-package-installer mod to install `python3` and `py3-pip` packages and also `qbittorrent-api` pip-package for sometime. However, I noticed today that `qbittorrent-api` pip-package install is failing due to PEP 668.

Here's the `ENV_VARIABLES`:

    - DOCKER_MODS=linuxserver/mods:universal-package-install
    - INSTALL_PACKAGES=python3|py3-pip
    - INSTALL_PIP_PACKAGES=qbittorrent-api

Here's the Error from the log:

	[custom-init] No custom services found, skipping...
	[mod-init] Attempting to run Docker Modification Logic
	[mod-init] Adding linuxserver/mods:universal-package-install to container
	[mod-init] Downloading linuxserver/mods:universal-package-install from lscr.io
	[mod-init] Installing linuxserver/mods:universal-package-install
	[mod-init] linuxserver/mods:universal-package-install applied to container
	[migrations] started
	[migrations] no migrations found
	───────────────────────────────────────
				██╗     ███████╗██╗ ██████╗ 
				██║     ██╔════╝██║██╔═══██╗
				██║     ███████╗██║██║   ██║
				██║     ╚════██║██║██║   ██║
				███████╗███████║██║╚██████╔╝
				╚══════╝╚══════╝╚═╝ ╚═════╝ 
		 Brought to you by linuxserver.io
	───────────────────────────────────────
	To support LSIO projects visit:
	https://www.linuxserver.io/donate/
	───────────────────────────────────────
	GID/UID
	───────────────────────────────────────
	User UID:    1000
	User GID:    1000
	───────────────────────────────────────
	**** Adding python3 to OS package install list ****
	**** Adding py3-pip to OS package install list ****
	**** Adding qbittorrent-api to pip install list ****
	/usr/bin/python3
	[mod-init] **** Installing all mod packages ****
	fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
	fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
	(1/10) Installing py3-setuptools-pyc (68.0.0-r2)
	(2/10) Installing py3-pip-pyc (23.2.1-r0)
	(3/10) Installing py3-parsing (3.1.1-r0)
	(4/10) Installing py3-parsing-pyc (3.1.1-r0)
	(5/10) Installing py3-packaging-pyc (23.1-r3)
	(6/10) Installing py3-packaging (23.1-r3)
	(7/10) Installing py3-setuptools (68.0.0-r2)
	(8/10) Installing py3-pip (23.2.1-r0)
	(9/10) Installing pkgconf (1.9.5-r0)
	(10/10) Installing python3-dev (3.11.4-r4)
	Executing busybox-1.36.1-r4.trigger
	OK: 206 MiB in 93 packages
	[mod-init] **** Installing all pip packages ****
	WARNING: The directory '/config/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
	error: externally-managed-environment
	× This environment is externally managed
	╰─> 
			The system-wide python installation should be maintained using the system
			package manager (apk) only.
			
			If the package in question is not packaged already (and hence installable via
			"apk add py3-somepackage"), please consider installing it inside a virtual
			environment, e.g.:
			
			python3 -m venv /path/to/venv
			. /path/to/venv/bin/activate
			pip install mypackage
			
			To exit the virtual environment, run:
			
			deactivate
			
			The virtual environment is not deleted, and can be re-entered by re-sourcing
			the activate file.
			
			To automatically manage virtual environments, consider using pipx (from the
			pipx package).
	note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
	hint: See PEP 668 for the detailed specification.
	WARNING: The directory '/config/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
	error: externally-managed-environment
	× This environment is externally managed
	╰─> 
			The system-wide python installation should be maintained using the system
			package manager (apk) only.
			
			If the package in question is not packaged already (and hence installable via
			"apk add py3-somepackage"), please consider installing it inside a virtual
			environment, e.g.:
			
			python3 -m venv /path/to/venv
			. /path/to/venv/bin/activate
			pip install mypackage
			
			To exit the virtual environment, run:
			
			deactivate
			
			The virtual environment is not deleted, and can be re-entered by re-sourcing
			the activate file.
			
			To automatically manage virtual environments, consider using pipx (from the
			pipx package).
	note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
	hint: See PEP 668 for the detailed specification.

**Comment by UNCode101** [comment]
Portainer on Ubuntu (not synology)

**Comment by Roxedus** [comment]
https://info.linuxserver.io/issues/2023-05-22-portainer/

**Comment by UNCode101** [comment]
Thanks for the link. So, it's a Portainer issue!

**Comment by Dominaezzz** [comment]
I've just ran into this issue as well but I don't use either Portainer or Synology.

It happens with the deluge container but not with the wireguard one.

**Comment by j0nnymoe** [comment]
I would suggest then opening a new issue.
