### ISSUE TITLE
[universal-docker] Docker buildx component missing or broken

### ISSUE THREAD

**Issue by Yukigamine** [linuxserver/docker-mods#741]
Universal docker mod comes with a new version of Docker that should support the new Buildkit build system for creating docker images, however attempting to do so results in the following error:

```
$ DOCKER_BUILDKIT=1 docker build .                                             
ERROR: BuildKit is enabled but the buildx component is missing or broken.
       Install the buildx component to build images with BuildKit:
       https://docs.docker.com/go/buildx/
```
Using the Universal Docker plugin on codeserver Docker container.
Please let me know if I missed something or if there is any further information I can provide.

**Comment by aptalca** [comment]
@Yukigamine can you test the mod PR image listed at https://github.com/linuxserver/docker-mods/pull/742#issuecomment-1668290074 and let us know if it works?

Thanks

**Comment by Yukigamine** [comment]
Thank you for the quick turnaround and apologies for the delay on my response.

The PR for the module fixes the lack of buildkit and the image starts building, but I'm running into an issue that I'm having trouble determining if the cause lies in codeserver/dockermod or just something about my setup/codebase.

It doesn't seem like it should be an issue with codeserver/dockermod, but the same Dockerfile runs fine on the exact same codebase on my desktop, which is why I'm on the fence. (it seems like the builder container is looking for something in the codeserver's filesystem??)

Here's the error, and if you agree that it doesn't seem like it should be codeserver/dockermod related, I'm cool with this issue being closed/merged, but someone else might want to double-check another repo/build to make fully sure that it's working as intended.

Thanks again!

```
...
 => [builder 4/5] COPY . .                                                                                                                                       26.7s 
 => ERROR [builder 5/5] RUN yarn build                                                                                                                            6.4s 
------                                                                                                                                                                 
 > [builder 5/5] RUN yarn build:                                                                                                                                       
4.438 node:internal/modules/cjs/loader:1051                                                                                                                            
4.438   throw err;                                                                                                                                                     
4.438   ^                                                                                                                                                              
4.438                                                                                                                                                                  
4.438 Error: Cannot find module '/config/workspace/project/node_modules/.store/next-virtual-2f7d86e049/node_modules/next/dist/bin/next'
4.438     at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
4.438     at Module._load (node:internal/modules/cjs/loader:901:27)
4.438     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
4.438     at node:internal/main/run_main_module:23:47 {
4.438   code: 'MODULE_NOT_FOUND',
4.438   requireStack: []
4.438 }
4.438 
4.438 Node.js v20.5.0
------
ERROR: failed to solve: executor failed running [/bin/sh -c yarn build]: exit code: 1 ```

**Comment by aptalca** [comment]
No idea what you're trying to build, but the path referenced `/config/workspace/project/node_modules` is presumably inside the code server container, however, the build process is running inside a docker container on (presumably) the host (or wherever you pointed the docker host variable to), in either case, that build process would not have access to that path in the code server container. Yarn would only have access to whatever is inside that build container, which includes the directory path the Dockerfile resides in (and the subfolders), after a proper `COPY` into the container (which you seem to do in step 4), as well as whatever is installed via the Dockerfile in the steps above yarn.

In any case, it seems the docker mod is working, so I'll go ahead merge the PR and close this.

Thanks for testing.
