### ISSUE TITLE
Pip packages incorrectly create venv

### ISSUE THREAD

**Issue by JeWe37** [linuxserver/docker-mods#744]
Consider the following situation: Two docker mods are added to an image. Docker mod A installs pip packages via the package manager, as they are available in the repos. A also installs python itself. Individually, this works fine. Mod B however installs pip packages. As python hasn't been installed at this point yet, a [`venv` will be requested to be created](https://github.com/linuxserver/docker-mods/blob/f8776c7297fc8a9bb9d5b796c1d00220d0f893bb/package-install.v1#L7). The packages, including python, are then correctly installed, however, the pip packages getting installed will cause the creation of a venv, thereby masking the pip packages installed via the system package manager by mod A, in turn breaking its functionality.

Originally I believe this is the work of @thespad. Optimally a different virtual environment would be available for every mod that uses this functionality, rather than a system wide one(in so far as I can tell that is what it is, though I have not found where that is implemented in the scripts). However that might be somewhat difficult to implement without accounting for each and every mod. 

Therefore I think a fair compromise that would remedy this in the majority of cases is I defaulting to inheriting the pip packages already installed and only updating these should specific versions be required by the pip environment.

**Comment by aptalca** [comment]
No mod or image should be installing Python packages/modules from the distro repos as python 3.11 no longer allows mixing and matching distro and pip installed packages. If you see any, let us know and we'll update it.

**Comment by JeWe37** [comment]
jellyfin-rffmpeg does, both the original Ubuntu code as well as the Alpine code I recently contributed, since I followed what was done for Ubuntu.

**Comment by aptalca** [comment]
Yeah, click and yaml need to be added to the pip package install list. And no need to add python3 as it will be installed by the package installer
