### ISSUE TITLE
Go not installed with code-server-golang

### ISSUE THREAD

**Issue by mardijker** [linuxserver/docker-mods#746]
When running this Docker mod in code-server, it doesn't seem to install any golang package, here is a truncated logs with grep

``` dcl | grep golang
code-server  | [mod-init] Adding linuxserver/mods:code-server-golang to container
code-server  | [mod-init] Downloading linuxserver/mods:code-server-golang from lscr.io
code-server  | [mod-init] Installing linuxserver/mods:code-server-golang
code-server  | [mod-init] linuxserver/mods:code-server-golang applied to container
code-server  | **** ensuring golang is in PATH ****
code-server  | **** Installing golang ****
```

When exec'ing

```
root@9ac61b2fb59b:/# go
bash: go: command not found
```

Would be happy to provide more details if needed. Currently using the image with version [4.16.1-ls172](https://github.com/linuxserver/docker-code-server/releases/tag/4.16.1-ls172).

**Comment by aptalca** [comment]
Try it in the code-server terminal, not while exec'ed in

**Comment by mardijker** [comment]
Huh, yeah it works as intended. There was a problem with the Go VS extension screaming that the go binary doesn't exist, but seems fine now

Thanks
