### ISSUE TITLE
New mod: SWAG auto-uptime-kuma

### ISSUE THREAD

**Issue by labmonkey** [linuxserver/docker-mods#747]
Hello I've created a new mod for Uptime Kuma: https://github.com/labmonkey/docker-mods
Everything is explained in the Readme. I still need to merge into "template" branch before making a PR (I suppose that's only the .github directory which will change).

If you see this contribution acceptable then based on the documentation I am asking you to create a new branch 'swag-auto-uptime-kuma' so I can open a PR.

**Comment by aptalca** [comment]
It needs to be based on the template branch

Instructions here: https://github.com/linuxserver/docker-mods#submitting-a-pr-for-a-mod-to-be-added-to-the-official-linuxserverio-repo

**Comment by labmonkey** [comment]
Well that's what I meant. I've updated the template branch.

**Comment by aptalca** [comment]
Here it is:
https://github.com/linuxserver/docker-mods/tree/swag-auto-uptime-kuma

**Comment by labmonkey** [comment]
Thanks a lot. I hope somebody will find this useful. https://github.com/linuxserver/docker-mods/pull/748
