### ISSUE TITLE
New Branch: Audnexus.bundle Mod for Plex

### ISSUE THREAD

**Issue by tylernguyen** [linuxserver/docker-mods#749]
PR Repo: https://github.com/tylernguyen/docker-mods/tree/template

This mod adds [Audnexus.bundle](https://github.com/djdembeck/Audnexus.bundle) for Plex, which is an audiobook and author metadata agent for Plex.

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-mods/tree/plex-audnexus

**Comment by aptalca** [comment]
#750
