### ISSUE TITLE
docker mod `s6-rc.d` not in final image

### ISSUE THREAD

**Issue by ReenigneArcher** [linuxserver/docker-mods#753]
I am the dev of a jellyfin mod. A user reported an issue that my jellyfin plugin is causing a crash due to incorrect permissions on the plugin files. https://github.com/LizardByte/Themerr-jellyfin/issues/68

I attempted to correct this by using the s6 init methodology; however the issue seems to persist. It's possible that I missed something, but I cannot determine what the issue might be.

[s6-rc.d directory](https://github.com/LizardByte/Themerr-jellyfin/tree/nightly/dockermod_root/etc/s6-overlay/s6-rc.d)

I really just have a single `run` file, and the `up` file points to that file.

I have `chmod +x`ed the run file -> https://github.com/LizardByte/Themerr-jellyfin/blob/f9d11125e9bf6c1a4e54ebeb3c124fdc9b532e42/Dockerfile#L88

And I believe everything is in the correct location. Copied from `./dockermod_root` to `/` at the end of the image in the final stage. -> https://github.com/LizardByte/Themerr-jellyfin/blob/f9d11125e9bf6c1a4e54ebeb3c124fdc9b532e42/Dockerfile#L101

But it appears these files are not in the jellyfin image after creating the image with the mod argument.
![image](https://github.com/linuxserver/docker-mods/assets/42013603/ecffb071-b9d1-4aac-9771-bb6fb0b9a086)

Could someone give a quick review and see where I might have went wrong?

Additionally, is there anyway to use a local image for the `DOCKER_MODS` variable? As far as I am seeing it appears to ignore local images.

**Comment by ReenigneArcher** [comment]
As suggested by the readme, I have inspected my mod image with dive, which does show the files in `/etc` ... so not sure whey they are not appearing in the final image.

![image](https://github.com/linuxserver/docker-mods/assets/42013603/b73302db-7190-481d-8de1-edf5972fa95e)

**Comment by aptalca** [comment]
Your final image has two layers (2 copy directives). The mod has to have only 1 layer.

In our mods, we copy all necessary files/folders into the same folder, and then in the final image do a single copy directives to move all files and folders to the final image, resulting in a single layer.

The reason is because we treat the mods as free storage in the registries. We download and extract the single tarball (each layer is a separate tarball) during container start.

**Comment by aptalca** [comment]
With regards to local images, the answer is no. Our mod logic just downloads the tarball from the registry.

For testing, you can either build local and push to your docker or ghcr account, or you can utilize our mod builder github workflow, which builds and pushes PRs to your registries along with a PR comment with the image link:
https://github.com/linuxserver/docker-mods/blob/universal-docker-in-docker/.github/workflows/BuildImage.yml

You just need to set the github repo to your own and set the 4 secrets with your values.

**Comment by ReenigneArcher** [comment]
Okay, now the layer is there, but I am getting an error about the `type` file.

```txt
2023-08-29 14:51:26 [mod-init] Attempting to run Docker Modification Logic
2023-08-29 14:51:26 [mod-init] Adding lizardbyte/themerr-jellyfin:nightly to container
2023-08-29 14:51:27 [mod-init] Downloading lizardbyte/themerr-jellyfin:nightly from registry-1.docker.io
2023-08-29 14:51:28 [mod-init] Installing lizardbyte/themerr-jellyfin:nightly
2023-08-29 14:51:28 [mod-init] lizardbyte/themerr-jellyfin:nightly applied to container
2023-08-29 14:51:28 s6-rc-compile: fatal: invalid /etc/s6-overlay/s6-rc.d/init-mod-jellyfin-themerr-config/type: must be oneshot, longrun, or bundle
```

I copied this file from another mod, and it is a `oneshot`

https://github.com/LizardByte/Themerr-jellyfin/blob/8819383ce26500bb700beb408a16012c2988df36/dockermod_root/etc/s6-overlay/s6-rc.d/init-mod-jellyfin-themerr-config/type#L1

**Comment by Roxedus** [comment]
The type (and the other S6 files) are saved with a encoding of `UTF8 with bom`, changing it to `UTF8` does the trick.

**Comment by ReenigneArcher** [comment]
@Roxedus do you have an example of how I am supposed to fix that?

**Comment by Roxedus** [comment]
In ie VSCode you press the `UTF8 with bom` text on the bottom bar, and select the save with encoding when pressing the text.

**Comment by ReenigneArcher** [comment]
@Roxedus okay, thanks I found it in Rider... Never faced an issue like this before, ha... So all the s6 init files should not have BOM encoding? Including the `run` file?

**Comment by ReenigneArcher** [comment]
"hopefully" the final issue. Again, this is the Jellyfin image.

```txt
2023-08-29 17:34:40 System.UnauthorizedAccessException: Access to the path '/config/data/plugins/configurations' is denied.
```

I'm thinking the permissions on this directory should be handled by the main image, as multiple mods could be applied. I've submitted a PR here -> https://github.com/linuxserver/docker-jellyfin/pull/214
