### ISSUE TITLE
[swag-dashboard] Using http for upstream to Plex on <other host device> causes duplicates in the Proxies section with error

### ISSUE THREAD

**Issue by FizzGiGG** [linuxserver/docker-mods#757]
I have the same/close to the same problem as in issue #407 that was closed due to inactivity with no resolution. I am only using http on the upstream though, not https, but it appears to be the same thing.

SWAG Dashboard displays an error that states the plex.subdomain.conf file cannot be found.
![image](https://github.com/linuxserver/docker-mods/assets/1538645/d263a731-c9de-45de-acf7-c3fdcdbffba2)

![image](https://github.com/linuxserver/docker-mods/assets/1538645/2344e2cf-df42-4b6b-a59c-fa20907625df)

There is only one proxy-confs / plex.subdomain.conf file that is active, I have it named plex**2**.subdomain.conf; all other files are .samples. (Yes, I have tried keeping the plex.subdomain.conf file name, it doesn't matter)

Here are the complete contents of plex2.subdomain.conf:

```
## Version 2023/05/31
# make sure that your plex container is named plex
# make sure that your dns has a cname set for plex
# if plex is running in bridge mode and the container is named "plex", the below config should work as is
# if not, replace the line "set $upstream_app plex;" with "set $upstream_app <containername>;"
# or "set $upstream_app <HOSTIP>;" for host mode, HOSTIP being the IP address of plex
# in plex server settings, under network, fill in "Custom server access URLs" with your domain (ie. "https://plex.yourdomain.url:443")

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name plex2.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;
    proxy_redirect off;
    proxy_buffering off;

    # enable for ldap auth (requires ldap-location.conf in the location block)
    #include /config/nginx/ldap-server.conf;

    # enable for Authelia (requires authelia-location.conf in the location block)
    #include /config/nginx/authelia-server.conf;

    # enable for Authentik (requires authentik-location.conf in the location block)
    #include /config/nginx/authentik-server.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable for ldap auth (requires ldap-server.conf in the server block)
        #include /config/nginx/ldap-location.conf;

        # enable for Authelia (requires authelia-server.conf in the server block)
        #include /config/nginx/authelia-location.conf;

        # enable for Authentik (requires authentik-server.conf in the server block)
        #include /config/nginx/authentik-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app plex2.mydomain.here;
        set $upstream_port 32400;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

        proxy_set_header X-Plex-Client-Identifier $http_x_plex_client_identifier;
        proxy_set_header X-Plex-Device $http_x_plex_device;
        proxy_set_header X-Plex-Device-Name $http_x_plex_device_name;
        proxy_set_header X-Plex-Platform $http_x_plex_platform;
        proxy_set_header X-Plex-Platform-Version $http_x_plex_platform_version;
        proxy_set_header X-Plex-Product $http_x_plex_product;
        proxy_set_header X-Plex-Token $http_x_plex_token;
        proxy_set_header X-Plex-Version $http_x_plex_version;
        proxy_set_header X-Plex-Nocache $http_x_plex_nocache;
        proxy_set_header X-Plex-Provides $http_x_plex_provides;
        proxy_set_header X-Plex-Device-Vendor $http_x_plex_device_vendor;
        proxy_set_header X-Plex-Model $http_x_plex_model;
    }
}
```

**Comment by aptalca** [comment]
`set $upstream_app plex2.mydomain.here;`

That doesn't seem right. Is it even working? That should be the container name or IP of your plex service

**Comment by FizzGiGG** [comment]
> `set $upstream_app plex2.mydomain.here;`
> 
> That doesn't seem right. Is it even working? That should be the container name or IP of your plex service

Well, as stated in the header section of that file it appears that it just needs to know where it's at. I use this method for other services that are not Docker containers and located elsewhere (e.g., AdGuardHome on RaspPi).

```
# if plex is running in bridge mode and the container is named "plex", the below config should work as is
# if not, replace the line "set $upstream_app plex;" with "set $upstream_app <containername>;"
# or "set $upstream_app <HOSTIP>;" for host mode, HOSTIP being the IP address of plex
```

**Comment by FizzGiGG** [comment]
Ah ha! I should have included this in the original post, but I run 2 Plex servers. One _is_ a Docker container, but I had opted to not run it through Swag. It's there and Swag knows it. I shut down the Plex container just now, and that's where the error came from. The error goes away when the Plex container is shutdown.

**Comment by FizzGiGG** [comment]
> While true, based on the info you posted, that plex instance seems to be running in a container named `plex`, which is in the same docker network as SWAG.
> 
> The dashboard mod does 2 things:
> 
> 1. Search for enabled proxy confs and see if they're accessible
> 2. Search for accessible services and see if they're enabled for proxy
> 
> So here, the dashboard finds the enabled plex conf (item 1), and sees it as enabled. It also finds a plex container that is accessible, but thinks it's not enabled, because it doesn't see any proxy confs that reference it.



> Ah, so the dashboard info is correct, no duplication. One listing is for the proxied plex instance, and the other is for the service that is accessible but not proxied

Yep, that all makes sense now. Kind of weird it's configured to do that, but as long as it isn't an actual problem, I'll ignore it.
