### ISSUE TITLE
[SWAG IonCube] Fails to install with linuxserver/NGINX:Latest

### ISSUE THREAD

**Issue by jetski28** [linuxserver/docker-mods#773]
During the RUN script it fails with the following error...

`/etc/s6-overlay/s6-rc.d/init-mod-swag-ioncube-setup/run: line 37: /etc/php8/conf.d/00-ioncube.ini: No such file or directory`

Looking at the file/folder structure for linuxserver/NGINX:Latest it appears that the PHP folder has both the major & minor verison numbers (eg. php82).

**Comment by thespad** [comment]
Please provide the full container startup logs, not just the single error line.

**Comment by jetski28** [comment]
`/etc/s6-overlay/s6-rc.d/init-mod-swag-ioncube-setup/run: line 37: /etc/php8/conf.d/00-ioncube.ini: No such file or directory
**** Ioncube Loader extracted: /usr/local/ioncube ****
**** Ioncube Loader PHP extension enabled: ioncube_loader_lin_8.2.so ****
**** Ioncube Loader Installed ****
[custom-init] No custom files found, skipping...
[ls.io-init] done.
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Adding linuxserver/mods:swag-ioncube to container
[mod-init] linuxserver/mods:swag-ioncube at sha256:91b294022fb4e7795c7f4ff5e826fb8249f69ebd3219ab0c7b55223389ec5f6f has been previously applied skipping
[mod-init] Adding linuxserver/mods:universal-cron to container
[mod-init] linuxserver/mods:universal-cron at sha256:5d7d862a06d872793733eafb9574aa6dac483409b631d0d181c71803bedb5f53 has been previously applied skipping
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done
usermod: no changes
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    911
User GID:    911
───────────────────────────────────────
using keys found in /config/keys
**** cron package already installed, skipping ****
**** Installing Ioncube Loader ****
**** Linux architecture found: x86-64 ****
**** PHP Version found: 8.2.x ****
**** Downloading Ioncube Loader... ****
Connecting to downloads.ioncube.com (192.241.136.243:443)
saving to '/tmp/ioncube_loaders_lin_x86-64.tar.gz'
ioncube_loaders_lin_   0% |                                | 81920  0:03:11 ETA
ioncube_loaders_lin_   1% |                                |  304k  0:01:39 ETA
ioncube_loaders_lin_   7% |**                              | 1168k  0:00:36 ETA
ioncube_loaders_lin_  43% |*************                   | 6656k  0:00:05 ETA
ioncube_loaders_lin_ 100% |********************************| 15.0M  0:00:00 ETA
'/tmp/ioncube_loaders_lin_x86-64.tar.gz' saved
**** Ioncube Loader downloaded: ioncube_loaders_lin_x86-64.tar.gz ****
**** Extracting Ioncube Loader... ****
ioncube/
ioncube/ioncube_loader_lin_5.0.so
ioncube/ioncube_loader_lin_4.3.so
ioncube/ioncube_loader_lin_7.0_ts.so
ioncube/ioncube_loader_lin_4.2.so
ioncube/ioncube_loader_lin_5.6.so
ioncube/ioncube_loader_lin_8.2_ts.so
ioncube/ioncube_loader_lin_7.1.so
ioncube/ioncube_loader_lin_5.3.so
ioncube/ioncube_loader_lin_7.3_ts.so
ioncube/ioncube_loader_lin_5.5_ts.so
ioncube/ioncube_loader_lin_5.4.so
ioncube/loader-wizard.php
ioncube/ioncube_loader_lin_4.3_ts.so
ioncube/ioncube_loader_lin_5.5.so
ioncube/LICENSE.txt
ioncube/USER-GUIDE.pdf
ioncube/ioncube_loader_lin_5.4_ts.so
ioncube/ioncube_loader_lin_7.4_ts.so
ioncube/ioncube_loader_lin_7.0.so
ioncube/ioncube_loader_lin_5.3_ts.so
ioncube/ioncube_loader_lin_4.4.so
ioncube/ioncube_loader_lin_4.4_ts.so
ioncube/ioncube_loader_lin_7.4.so
ioncube/ioncube_loader_lin_7.3.so
ioncube/ioncube_loader_lin_7.1_ts.so
ioncube/ioncube_loader_lin_7.2_ts.so
ioncube/ioncube_loader_lin_5.2.so
ioncube/USER-GUIDE.txt
ioncube/ioncube_loader_lin_4.1.so
ioncube/ioncube_loader_lin_8.2.so
ioncube/README.txt
ioncube/ioncube_loader_lin_5.1_ts.so
ioncube/ioncube_loader_lin_7.2.so
ioncube/ioncube_loader_lin_8.1.so
ioncube/ioncube_loader_lin_5.0_ts.so
ioncube/ioncube_loader_lin_8.1_ts.so
ioncube/ioncube_loader_lin_5.1.so
ioncube/ioncube_loader_lin_5.6_ts.so
ioncube/ioncube_loader_lin_5.2_ts.so
**** Ioncube Loader extracted: /usr/local/ioncube ****
/etc/s6-overlay/s6-rc.d/init-mod-swag-ioncube-setup/run: line 37: /etc/php8/conf.d/00-ioncube.ini: No such file or directory
**** Ioncube Loader PHP extension enabled: ioncube_loader_lin_8.2.so ****
**** Ioncube Loader Installed ****
[custom-init] No custom files found, skipping...
[ls.io-init] done.`

**Comment by aptalca** [comment]
#781
