### ISSUE TITLE
Failing to install Node

### ISSUE THREAD

**Issue by jesuzon** [linuxserver/docker-mods#779]
I've encountered a bit of a strange issue with the code-server-nodejs docker mod.

Initially things ran smoothly, but whilst trying to troubleshoot some issues with my environment (and restarting the code-server container a few times) I noticed that npm was no longer available in my code-server terminal. 
I tried changing the node version and once again things ran smoothly, but it seems that after a few container restarts, this version stopped working too.

From the logs I can see the following:
`The following NEW packages will be installed:
  libpython3.10-minimal nodejs python3-minimal python3.10-minimal yarn
0 upgraded, 5 newly installed, 0 to remove and 6 not upgraded.
Need to get 34.3 MB of archives.
After this operation, 210 MB of additional disk space will be used.
Get:1 https://dl.yarnpkg.com/debian stable/main amd64 yarn all 1.22.19-1 [893 kB]
Err:2 https://deb.nodesource.com/node_20.x jammy/main amd64 nodejs amd64 20.5.1-deb-1nodesource1
  404  Not Found [IP: 172.67.10.205 443]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libpython3.10-minimal amd64 3.10.12-1~22.04.2 [811 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 python3.10-minimal amd64 3.10.12-1~22.04.2 [2,258 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 python3-minimal amd64 3.10.6-1~22.04 [24.3 kB]
E: Failed to fetch https://deb.nodesource.com/node_20.x/pool/main/n/nodejs/nodejs_20.5.1-deb-1nodesource1_amd64.deb  404  Not Found [IP: 172.67.10.205 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?`

Changing the node version to 18 worked for a bit as I mentioned, but now that one gives a similar error.

I thought maybe my IP was banned/flagged for some reason after restarting the container a few times (even though that doesn't make much sense), so I tried to run behind a VPN which made no difference (unless VPN IPs are flagged as well)...

Any ideas here?

**Comment by webysther** [comment]
Same.

**Comment by webysther** [comment]
A workaround, remove this mod and use this guide: https://deb.nodesource.com/node_20.x/pool/main/n/nodejs/nodejs_20.5.1-deb-1

**Comment by thespad** [comment]
They've killed off their old repos and moved to a new structure, which broke the mod. I've opened a PR to fix it.
