### ISSUE TITLE
Add Prolog Mod code-server

### ISSUE THREAD

**Issue by MiguelNdeCarvalho** [linuxserver/docker-mods#78]
https://github.com/MiguelNdeCarvalho/docker-mods/tree/code-server-prolog

**Comment by aptalca** [comment]
looks good, but please delete the dockerfile.complex

**Comment by aptalca** [comment]
you can PR to this branch: https://github.com/linuxserver/docker-mods/tree/code-server-prolog
Please squash the commits first.

Thanks

**Comment by MiguelNdeCarvalho** [comment]
Hey, I will delete it and then do the PR.
Thanks,
Miguel de Carvalho

**Comment by aptalca** [comment]
#82
