### ISSUE TITLE
Calibre mod on ARM64

### ISSUE THREAD

**Issue by dimaguy** [linuxserver/docker-mods#791]
As per issue #44, calibre-mod didn't support arm because of a lack of a binary being released. As I can see on [calibre's repo releases](https://github.com/kovidgoyal/calibre/releases), that seems to no longer be the case, could that issue be revisited?

**Comment by thespad** [comment]
The calibre mod has supported arm64 for over a year.

**Comment by dimaguy** [comment]
> The calibre mod has supported arm64 for over a year.

Oh, I haven't noticed because it says 64-bit containers(usually that means amd64), but thanks!
