### ISSUE TITLE
Add scikit-learn mod for Code-Server

### ISSUE THREAD

**Issue by MiguelNdeCarvalho** [linuxserver/docker-mods#80]
https://github.com/MiguelNdeCarvalho/docker-mods/tree/code-server-machinelearning

**Comment by aptalca** [comment]
Not sure if machinelearning is the right name for it. The mod name should be the service/app name rather than a broad description. Perhaps `scikit-learn` would be more appropriate

**Comment by aptalca** [comment]
Also, it shouldn't expect the user to install another mod for this to work. In this case, it wouldn't even work because this mod would be attempted to be installed before the python3 mod (alphabetical) and it would fail. The mod should install its own necessary dependencies

**Comment by MiguelNdeCarvalho** [comment]
So I should install python3 too? I'm going to redo it and rename it

**Comment by MiguelNdeCarvalho** [comment]
Hey @aptalca please recheck the links, I have redone it :+1:

**Comment by aptalca** [comment]
PR here: https://github.com/linuxserver/docker-mods/tree/code-server-scikit-learn

**Comment by aptalca** [comment]
#85
