### ISSUE TITLE
swag-crowdsec is not activating sqlite WAL mode

### ISSUE THREAD

**Issue by GuiPoM** [linuxserver/docker-mods#802]
Hello,

It seems that having sqlite in WAL mode is a must when using community-blocklist, which is adviced to be used with swag-crowdsec.
But the default configuration is not activating this option and triggers a warning:
```
time="18-12-2023 20:16:27" level=warning msg="sqlite is not using WAL mode, LAPI might become unresponsive when inserting the community blocklist"
time="18-12-2023 20:16:28" level=info msg="crowdsecurity/community-blocklist : added 15000 entries, deleted 11060 entries (alert:2)"
```
`/etc/crowdsec/config.yaml`, section `db_config` should be updated with `use_wal: true`. Maybe it should be configurable, if needed. But default config seems not to be the one which is advised in combination with community-blocklist, to my understanding.

Thanks

**Comment by LaurenceJJones** [comment]
This is not controllable by swag, this is purely just CrowdSec configuration. In our latest container you can specify the container environment

```
USE_WAL 	false 	Enable Write-Ahead Logging with SQLite
```

https://hub.docker.com/r/crowdsecurity/crowdsec

**Comment by GuiPoM** [comment]
Hello @LaurenceJJones ,

Thanks for your answer and sorry for the misunderstanding.
I was not aware of that env property, and I will do good use of it !
