### ISSUE TITLE
Create new branch: code-server-rust

### ISSUE THREAD

**Issue by totraku** [linuxserver/docker-mods#804]
Request to create a new branch called code-server-rust. This mod adds the rust toolchain to code-server
Repo url: https://github.com/totraku/docker-mods/tree/code-server-rust

AFAIK using rust on the branch name here should not be problematic as I understand from:
https://foundation.rust-lang.org/policies/logo-policy-and-media-guide/#uses-that-do-not-require-explicit-approval
Especially the first two points seem to suggest this.

**Comment by totraku** [comment]
I built an image to test it under code-server:
https://hub.docker.com/r/erlukani/code-server-rust
I also noticed I have to clarify the versioning and the README.

**Comment by aptalca** [comment]
Here it is:
https://github.com/linuxserver/docker-mods/tree/code-server-rust

**Comment by totraku** [comment]
Thanks, here is the merge request:
https://github.com/linuxserver/docker-mods/pull/808
