### ISSUE TITLE
Persistance of installed Mods

### ISSUE THREAD

**Issue by Yanik39** [linuxserver/docker-mods#806]
Hello,

Is there any way to save installed mods? Everything is being reinstalled at every reboot.

**Comment by j0nnymoe** [comment]
They will reinstall every time the container is rebuilt.

**Comment by Yanik39** [comment]
> They will reinstall every time the container is rebuilt.

I know. That's why i am asking here if any way to persist that..

**Comment by thespad** [comment]
Not really, the mod logic has to modify container init and services so can't persist a container recreation, but should survive a restart/host reboot as long as the container isn't deleted.

There are "ways", but they break the rest of the mod logic and means you wouldn't get updates, etc.

**Comment by j0nnymoe** [comment]
Not between rebuilds but if you're just restarting your host (assuming you're not destroying the container), they should persist.
