### ISSUE TITLE
Add ZSH mod for Code-Server

### ISSUE THREAD

**Issue by MiguelNdeCarvalho** [linuxserver/docker-mods#81]
https://github.com/MiguelNdeCarvalho/docker-mods/tree/code-server-zsh

**Comment by aptalca** [comment]
This should install oh-my-zsh manually rather than use an external install script
Also, if it's not installing from the repo, perhaps the files should be included in the mod image and get copied as necessary during runtime

**Comment by MiguelNdeCarvalho** [comment]
Oki, I will redo the mod, thanks :+1:

**Comment by MiguelNdeCarvalho** [comment]
Hey @aptalca, please recheck the link. I have finished it :+1:

**Comment by aptalca** [comment]
Merge this first: https://github.com/MiguelNdeCarvalho/docker-mods/pull/1
Then PR to this branch: https://github.com/linuxserver/docker-mods/tree/code-server-zsh

**Comment by MiguelNdeCarvalho** [comment]
Done: #86
