### ISSUE TITLE
linuxserver/mods:code-server-python3 could not be found on registry-1.docker.io

### ISSUE THREAD

**Issue by pheetr** [linuxserver/docker-mods#812]
When attempting to add a python interpreter to code-server via the recommended code-server-python3 mod, I'm getting the below error message in the logs. The other mod is getting installed fine, so I imagine this issue is specific to the python3 mod.

```
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Adding DOCKER_MODS=linuxserver/mods:code-server-python3 to container
[mod-init] DOCKER_MODS=linuxserver/mods:code-server-python3 could not be found on registry-1.docker.io
[mod-init] Adding linuxserver/mods:code-server-extension-arguments to container
[mod-init] Downloading linuxserver/mods:code-server-extension-arguments from lscr.io
[mod-init] Installing linuxserver/mods:code-server-extension-arguments
[mod-init] linuxserver/mods:code-server-extension-arguments applied to container
[migrations] started
[migrations] no migrations found
───────────────────────────────────────
```

**Comment by aptalca** [comment]
you set the mod name to `DOCKER_MODS=linuxserver/mods:code-server-python3` instead of `linuxserver/mods:code-server-python3`

**Comment by pheetr** [comment]
A bit of an embarrassing copy-paste mistake. Thanks for spotting it and providing guidance so quickly. Much appreciated.
