### ISSUE TITLE
linuxserver/mods:jellyfin-rffmpeg could not be found

### ISSUE THREAD

**Issue by jordycoding** [linuxserver/docker-mods#817]
I'm trying to add the jellyfin-rffmpeg mod to my jellyfin container but I'm getting the following error message.
```
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Adding linuxserver/mods:jellyfin-rffmpeg to container
[mod-init] linuxserver/mods:jellyfin-rffmpeg could not be found on lscr.io
[migrations] started
[migrations] no migrations found
usermod: no changes
```

**Comment by aptalca** [comment]
try setting the following env vars and the log will be more verbose:
`DOCKER_MODS_DEBUG=true` and `CURL_NOISE_LEVEL="-v"`

**Comment by jordycoding** [comment]
Thank you so much, apparently my docker container had a dns issue, it was giving error messages about not being able to resolve the host ghcr.io

I fixed it by setting a custom dns server in my compose file.
