### ISSUE TITLE
Can't add docker-mod to swag container

### ISSUE THREAD

**Issue by xyleth** [linuxserver/docker-mods#819]
I'm trying to add the swag dashboard and auto-reload mods to the swag container.  I have added the following line to my docker compose file environment section:

`DOCKER_MODS=linuxserver/mods:swag-dashboard|linuxserver/mods:swag-auto-reload`

This is what I get in the container log:

`[mod-init] **** Installing all mod packages ****
fetch http://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
WARNING: fetching http://dl-cdn.alpinelinux.org/alpine/v3.18/main: IO ERROR
fetch http://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
WARNING: fetching http://dl-cdn.alpinelinux.org/alpine/v3.18/community: IO ERROR
ERROR: unable to select packages:
  goaccess (no such package):
    required by: world[goaccess]
  inotify-tools (no such package):
    required by: world[inotify-tools]
[custom-init] No custom files found, skipping...
MOD Auto-reload: Watching the following files/folders for changes (excluding .sample and .md files):
/config/nginx
./run: line 15: inotifywait: command not found
[ls.io-init] done.`

And then nothing works.  Removing the DOCKER_MODS line and swag works as usual.

I've verified that the container has network access and name resolution working so I don't think it's that.  Can anyone suggest other things I should check?

**Comment by Roxedus** [comment]
everything points to there being no network available on startup

**Comment by Nicolas-mahe** [comment]
Hi, this error appear to me too few days ago. To solve it I destroy my containers and create an other network from my docker compose file (I create "web" from CLI with docker and "crowdsec" is automaticaly create at start)
`services:
  swag:
    -----
    environment:
      DOCKER_MODS: ghcr.io/linuxserver/mods:swag-dashboard|ghcr.io/linuxserver/mods:swag-auto-reload|ghcr.io/lineserver/mods:swag-dbip|ghcr.io/linuxserver/mods:swag-crowdsec
    ports:
      - 443:443
    networks:
      - crowdsec
      - web

networks:
  crowdsec:
    name: crowdsec
  web:
    external: true`

**Comment by xyleth** [comment]
Just to update on this, I think I've managed to chase it down to an issue with the underlying Proxmox VE.

For some reason neither the host nor any of the guests, or containers within guests, on it can open connections to services on port 80.  HTTPS works fine, but as most packaging tools by default use HTTP they just time out as they fail to connect.

So I don't think this is a issue with this container, but I have no idea what would be causing something this specific.  If the devs would like to close this issue I think that's appropriate, otherwise I'll drop an update when I finally get to the bottom of this.

**Comment by aptalca** [comment]
Closing

PS. If you're using docker in lxc, we highly recommend against that. It causes many different issues. Even the proxmox devs recommend running docker in a VM and not in lxc.
