### ISSUE TITLE
[CrowdSec docker mod for SWAG] lua error with ngx.timer context

### ISSUE THREAD

**Issue by BackedUpBooty** [linuxserver/docker-mods#821]
After setting up CrowdSec with the docker mod for SWAG, everything was working, but `cscli metrics` showed a quickly increasing swag error.log with nothing being parsed. Checking error.log, I get the following error every 30seconds or so:

```
2024/01/16 20:50:57 [error] 10248#10248: *347230 lua entry thread aborted: runtime error: /usr/local/lua/crowdsec/crowdsec.lua:234: attempt to concatenate local 'err' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/lua/crowdsec/crowdsec.lua: in function </usr/local/lua/crowdsec/crowdsec.lua:184>, context: ngx.timer, client: [publicIP], server: 0.0.0.0:443
2024/01/16 20:51:27 [error] 10247#10247: *347286 lua entry thread aborted: runtime error: /usr/local/lua/crowdsec/crowdsec.lua:234: attempt to concatenate local 'err' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/lua/crowdsec/crowdsec.lua: in function </usr/local/lua/crowdsec/crowdsec.lua:184>, context: ngx.timer, client: [publicIP], server: 0.0.0.0:443
2024/01/16 20:52:04 [error] 10246#10246: *347330 lua entry thread aborted: runtime error: /usr/local/lua/crowdsec/crowdsec.lua:234: attempt to concatenate local 'err' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/lua/crowdsec/crowdsec.lua: in function </usr/local/lua/crowdsec/crowdsec.lua:184>, context: ngx.timer, client: [localIP], server: 0.0.0.0:443
```

As far as I can tell, the service is still working. IPs are getting banned and all buckets bouncers parsers etc. seem to be working. I see what this error is referring to but don't actually know what it is or how to fix it. Redacted the IPs, but the local IP is my Home Assistant instance.

**Comment by LaurenceJJones** [comment]
This was an upstream issue and was fix within https://github.com/crowdsecurity/lua-cs-bouncer/pull/51 once a new version of nginx bouncer is released the fixed code will make it to SWAG

**Comment by BackedUpBooty** [comment]
Thanks for the reply and info. 

Is the LAPI URL you refer to the one in the SWAG environment block? It's routing to the container and port by container name and internal container port as they're on the same docker network, and pretty sure the API is a pure copy paste across from what the command spat out. This is what I get with `cscli metrics` so I had assumed it was working normally. 

```
             Source              │ Lines read │ Lines parsed │ Lines unparsed │ Lines poured to bucket
 file:/var/log/swag/access.log   │ 245.29k    │ 245.29k      │ -              │ 36.98k                 
 file:/var/log/swag/error.log    │ 58.72k     │ 15           │ 58.71k         │ 3
```

> However, this will just fix the error reporting NOT the actual error you are getting
Any suggestion you could give other than to try and reset the API?

**Comment by LaurenceJJones** [comment]
The metric shown are just for parsing the log files. You should have a section for bouncer metrics?

**Comment by BackedUpBooty** [comment]
```
Local API Bouncers Metrics:
╭──────────────┬──────────────────────┬────────┬──────╮
│   Bouncer    │ Route                │ Method │ Hits │
├──────────────┼──────────────────────┼────────┼──────┤
│ bouncer-swag │ /v1/decisions/stream │ GET    │ 60   │
╰──────────────┴──────────────────────┴────────┴──────╯
```

Here it is.

**Comment by LaurenceJJones** [comment]
> ```
> Local API Bouncers Metrics:
> ╭──────────────┬──────────────────────┬────────┬──────╮
> │   Bouncer    │ Route                │ Method │ Hits │
> ├──────────────┼──────────────────────┼────────┼──────┤
> │ bouncer-swag │ /v1/decisions/stream │ GET    │ 60   │
> ╰──────────────┴──────────────────────┴────────┴──────╯
> ```
> 
> Here it is.

Maybe the error was just a temporary outage? Or do you still see them?

**Comment by BackedUpBooty** [comment]
No the errors aren't there anymore, however since you commented about the fix only solving the reporting and not the underlying issue, I wasn't sure if I still had an issue or not.

**Comment by LaurenceJJones** [comment]
> No the errors aren't there anymore, however since you commented about the fix only solving the reporting and not the underlying issue, I wasn't sure if I still had an issue or not. 

It's probably just an intermitted issue you had with lapi not being available.

**Comment by BackedUpBooty** [comment]
Fair enough, I'll go ahead and close this now, thanks for the support.
