### ISSUE TITLE
Cron wont run

### ISSUE THREAD

**Issue by bladecell** [linuxserver/docker-mods#827]
Hello, after adding this mod to code-server image and adding the line `*/5 * * * *    /bin/echo test >> /config/tmp.txt` to `config/crontabs/abs` and restarting the container, I would expect the line to appear in file after running `crontab -e` in docker container, but it is not present. Furthermore no test is appended in `/config/tmp.txt` so the cron job did not run and other commands in abc file wont run either.

**Comment by bladecell** [comment]
My mistake, the file is named `abc`, not `abs`, I am checking crontab like this
```
crontab -l -u abc
# Edit this file to introduce tasks to be run by cron.
# 
# Each task to run has to be defined through a single line
# indicating with different fields when the task will be run
# and what command to run for the task
# 
# To define the time you can provide concrete values for
# minute (m), hour (h), day of month (dom), month (mon),
# and day of week (dow) or use '*' in these fields (for 'any').
# 
# Notice that tasks will be started based on the cron's system
# daemon's notion of time and timezones.
# 
# Output of the crontab jobs (including errors) is sent through
# email to the user the crontab file belongs to (unless redirected).
# 
# For example, you can run a backup of all your user accounts
# at 5 a.m every week with:
# 0 5 * * 1 tar -zcf /var/backups/home.tgz /home/
# 
# For more information see the manual pages of crontab(5) and cron(8)
# 
# m h  dom mon dow   command
```

**Comment by mindset-tk** [comment]
I'm also having this issue. I've tried adding it to both `abc` and `root` crontabs. It seems to me that the cron service isn't actually being started as I don't see crond or anything like that in ps -aux.  When I manually start `crond` the cron job completes until the container is restarted

**Comment by acondura** [comment]
True, I'm also having this problem.  I have added DOCKER_MODS=linuxserver/mods:universal-cron to my docker-compose file, I'm using https://docs.linuxserver.io/images/docker-code-server. I then added a test line in /config/crontabs/abc but nothing works.

The only way I could get it to work is to use a custom script (as outlined here https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers) by adding a volume line like this:
- ./init:/custom-cont-init.d:ro

and then in my init/cron.sh file write this:

#!/bin/bash
cronjob="YOU-COMMAND-GOES-HERE"
(crontab -u abc -l; echo "$cronjob" ) | crontab -u abc -

I hope this helps!
