### ISSUE TITLE
downloading failed 

### ISSUE THREAD

**Issue by dmakhalfeh** [linuxserver/docker-mods#833]
libmaxminddb (1.7.1-r2)

Downloading GeoIP2 City database.

tar: short read

**Comment by dmakhalfeh** [comment]
after a deep dive inside, its look like the crontab script to download the database not functining well, maybe because maxmind changed the uri or api, so the link in use is 
curl --silent "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=<License_key>&suffix=tar.gz" -o "$TMPDIR/${filename}.tar.gz" not working with curl ...

so to get it solve i created an another container to download the file to /config/geoip2db so maxmind can work in a good situation. 
the crontab script should be changed according the documentation of maxmind ...

**Comment by aptalca** [comment]
> the crontab script should be changed according the documentation of maxmind ...

What made you come to that conclusion?

I just tested it locally and the script works just fine. Make sure you entered the license correctly and that your container does not have networking issues

**Comment by aptalca** [comment]
> try to run the script /etc/periodic/weekly/libmaxminddb
> check what you get?

I told you I just did, and it worked with no issues. Being able to ping google says nothing about whether it can resolve or reach the maxmind server, or whether it's inputting a valid license key into the url

**Comment by dmakhalfeh** [comment]
ok then it might be the problem in my side.... but im still not sure about it 
here is the output of the curl: 
<details><summary>Details</summary>
<p>

curl -v "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key="License_key_removed!"&suffix=tar.gz" -o "/root/GeoLite2-Country_20240209.tar.gz"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Host download.maxmind.com:443 was resolved.
* IPv6: 2606:4700:7::a29f:8616, 2606:4700:7::a29f:8716
* IPv4: 162.159.135.22, 162.159.134.22
*   Trying 162.159.135.22:443...
* Connected to download.maxmind.com (162.159.135.22) port 443
* ALPN: curl offers h2,http/1.1
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [2331 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [80 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / X25519 / id-ecPublicKey
* ALPN: server accepted h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Mar 17 00:00:00 2023 GMT
*  expire date: Mar 16 23:59:59 2024 GMT
*  subjectAltName: host "download.maxmind.com" matched cert's "*.maxmind.com"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
*   Certificate level 0: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using ecdsa-with-SHA256
*   Certificate level 1: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 2: Public key type RSA (2048/112 Bits/secBits), signed using sha1WithRSAEncryption
} [5 bytes data]
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=License_key_removed&suffix=tar.gz
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: download.maxmind.com]
* [HTTP/2] [1] [:path: /app/geoip_download?edition_id=GeoLite2-Country&license_key=License_key_removed&suffix=tar.gz]
* [HTTP/2] [1] [user-agent: curl/8.5.0]
* [HTTP/2] [1] [accept: */*]
} [5 bytes data]
> GET /app/geoip_download?edition_id=GeoLite2-Country&license_key=License_key_removed&suffix=tar.gz HTTP/2
> Host: download.maxmind.com
> User-Agent: curl/8.5.0
> Accept: */*
>
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [230 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [230 bytes data]
* old SSL session ID is stale, removing
{ [5 bytes data]
< HTTP/2 302
< date: Mon, 12 Feb 2024 17:05:52 GMT
< content-length: 0
< location: https://mm-prod-geoip-databases.a2649acb697e2c09b632799562c076f2.r2.cloudflarestorage.com/downloads/GeoLite2-Country_20240209.tar.gz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=bcf75f436ae20fad63536d542f05a8b4%2F20240212%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20240212T170552Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&response-cache-control=private%2C%20max-age%3D0&response-content-disposition=attachment%3B%20filename%3DGeoLite2-Country_20240209.tar.gz&response-content-type=application%2Fgzip&response-expires=Mon%2C%2012%20Feb%202024%2017%3A05%3A52%20GMT&x-id=GetObject&X-Amz-Signature=618d59d73835f5c9153ca0ae9a6fe01fb1978e9df33954afaca3dd3d270029ba
< cache-control: private, max-age=0
< expires: Mon, 12 Feb 2024 17:05:52 GMT
< server: cloudflare
< cf-ray: 85466b403bbc7d95-TLV
<
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host download.maxmind.com left intact

</p>
</details>

**Comment by Or-azur** [comment]
Hello 

I have the same problem:

Applying the maxmind mod...
Downloading GeoIP2 City database.
tar: short read
Applied the maxmind mod
[custom-init] No custom files found, skipping...
[ls.io-init] done.
nginx: [emerg] MMDB_open("/config/geoip2db/GeoLite2-City.mmdb") failed - Error opening the specified MaxMind DB file in /config/nginx/maxmind.conf:1

**Comment by aptalca** [comment]
Check the output of `docker exec swag cat /etc/libmaxminddb.cron.conf` and make sure the values look correct. Here's what mine looks like:

```
# Database files to download
# MAXMINDDB_FILES="GeoLite2-City.mmdb"

# Database download directory
# MAXMINDDB_URL="https://download.maxmind.com/app/geoip_download"

# Local target directory
# MAXMINDDB_LIBDIR="/var/lib/libmaxminddb"

# MaxMind license key, can be retrieved through https://www.maxmind.com/en/geolite2/signup
MAXMINDDB_LICENSE_KEY="4UseREDACTEDzAFTL"
```

**Comment by aptalca** [comment]
Something's not adding up here. The whole db download script is managed by the alpine package, source here: https://gitlab.alpinelinux.org/alpine/aports/-/blob/3.19-stable/main/libmaxminddb/libmaxminddb.cron?ref_type=heads

It's supposed to download the `GeoLite2-City` database. But your curl output is referencing the `GeoLite2-Country` so I'm not sure what you're posting or where those entries are coming from.

Please post a full compose yaml for your SWAG (or docker run) along with a full container log so we can see what's going on.

And make sure you're not including the characters `<` and `>` in your license key value.

**Comment by dmakhalfeh** [comment]
thats true i tried even both here is the output of the city 
<details><summary>Details</summary>
<p>

root@7dd91951b61b:/# curl -v "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key="License_Key"&suffix=tar.gz" -o "/root/GeoLite2-Country_20240210.tar.gz"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Host download.maxmind.com:443 was resolved.
* IPv6: 2606:4700:7::a29f:8716, 2606:4700:7::a29f:8616
* IPv4: 162.159.134.22, 162.159.135.22
*   Trying 162.159.134.22:443...
* Connected to download.maxmind.com (162.159.134.22) port 443
* ALPN: curl offers h2,http/1.1
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [2331 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [80 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / X25519 / id-ecPublicKey
* ALPN: server accepted h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Mar 17 00:00:00 2023 GMT
*  expire date: Mar 16 23:59:59 2024 GMT
*  subjectAltName: host "download.maxmind.com" matched cert's "*.maxmind.com"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
*   Certificate level 0: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using ecdsa-with-SHA256
*   Certificate level 1: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 2: Public key type RSA (2048/112 Bits/secBits), signed using sha1WithRSAEncryption
} [5 bytes data]
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=License_key&suffix=tar.gz
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: download.maxmind.com]
* [HTTP/2] [1] [:path: /app/geoip_download?edition_id=GeoLite2-City&license_key=License_key&suffix=tar.gz]
* [HTTP/2] [1] [user-agent: curl/8.5.0]
* [HTTP/2] [1] [accept: */*]
} [5 bytes data]
root@7dd91951b61b:/root# curl -v "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key="License_key"&suffix=tar.gz" -o "/root/GeoLite2-Country_20240210.tar.gz"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Host download.maxmind.com:443 was resolved.
* IPv6: 2606:4700:7::a29f:8716, 2606:4700:7::a29f:8616
* IPv4: 162.159.134.22, 162.159.135.22
*   Trying 162.159.134.22:443...
* Connected to download.maxmind.com (162.159.134.22) port 443
* ALPN: curl offers h2,http/1.1
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [2331 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [80 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / X25519 / id-ecPublicKey
* ALPN: server accepted h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Mar 17 00:00:00 2023 GMT
*  expire date: Mar 16 23:59:59 2024 GMT
*  subjectAltName: host "download.maxmind.com" matched cert's "*.maxmind.com"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
*   Certificate level 0: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using ecdsa-with-SHA256
*   Certificate level 1: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 2: Public key type RSA (2048/112 Bits/secBits), signed using sha1WithRSAEncryption
} [5 bytes data]
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=License_key&suffix=tar.gz
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: download.maxmind.com]
* [HTTP/2] [1] [:path: /app/geoip_download?edition_id=GeoLite2-City&license_key=License_key&suffix=tar.gz]
* [HTTP/2] [1] [user-agent: curl/8.5.0]
* [HTTP/2] [1] [accept: */*]
} [5 bytes data]
> GET /app/geoip_download?edition_id=GeoLite2-City&license_key=License_key&suffix=tar.gz HTTP/2
> Host: download.maxmind.com
> User-Agent: curl/8.5.0
> Accept: */*
>
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [230 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [230 bytes data]
* old SSL session ID is stale, removing
{ [5 bytes data]
< HTTP/2 302
< date: Tue, 13 Feb 2024 22:06:43 GMT
< content-length: 0
< location: https://mm-prod-geoip-databases.a2649acb697e2c09b632799562c076f2.r2.cloudflarestorage.com/downloads/GeoLite2-City_20240213.tar.gz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=bcf75f436ae20fad63536d542f05a8b4%2F20240213%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20240213T220643Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&response-cache-control=private%2C%20max-age%3D0&response-content-disposition=attachment%3B%20filename%3DGeoLite2-City_20240213.tar.gz&response-content-type=application%2Fgzip&response-expires=Tue%2C%2013%20Feb%202024%2022%3A06%3A43%20GMT&x-id=GetObject&X-Amz-Signature=fb1b47ff01b3059255d1e9c70e5eeecb9a6e7e3e85da053b16671aafc213dec7
< cache-control: private, max-age=0
< expires: Tue, 13 Feb 2024 22:06:43 GMT
< server: cloudflare
< cf-ray: 85506150997d7d9e-TLV
<
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host download.maxmind.com left intact
root@7dd91951b61b:/root#

</p>
</details> 

Regarding the <> its included in the file . try to rename the file and to download new one and check the size of the file ...
let me know if i can help with this issue.

**Comment by aptalca** [comment]
If the characters `<` and `>` are in that file, that means you incorrectly set the env var and that's your issue. The var needs to be set to just the api key, nothing else

**Comment by dmakhalfeh** [comment]
@aptalca i tried with a wrong license and it tells me the license is invalid 
here is the details! 
<details><summary>Details</summary>
<p>
root@7dd91951b61b:/# curl -v "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key="justforfun"&suffix=tar.gz" -o "/root/justforfun.tar.gz"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Host download.maxmind.com:443 was resolved.
* IPv6: 2606:4700:7::a29f:8616, 2606:4700:7::a29f:8716
* IPv4: 162.159.134.22, 162.159.135.22
*   Trying 162.159.134.22:443...
* Connected to download.maxmind.com (162.159.134.22) port 443
* ALPN: curl offers h2,http/1.1
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [2331 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [78 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / X25519 / id-ecPublicKey
* ALPN: server accepted h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Mar 17 00:00:00 2023 GMT
*  expire date: Mar 16 23:59:59 2024 GMT
*  subjectAltName: host "download.maxmind.com" matched cert's "*.maxmind.com"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
*   Certificate level 0: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using ecdsa-with-SHA256
*   Certificate level 1: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 2: Public key type RSA (2048/112 Bits/secBits), signed using sha1WithRSAEncryption
} [5 bytes data]
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=justforfun&suffix=tar.gz
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: download.maxmind.com]
* [HTTP/2] [1] [:path: /app/geoip_download?edition_id=GeoLite2-City&license_key=justforfun&suffix=tar.gz]
* [HTTP/2] [1] [user-agent: curl/8.5.0]
* [HTTP/2] [1] [accept: */*]
} [5 bytes data]
> GET /app/geoip_download?edition_id=GeoLite2-City&license_key=justforfun&suffix=tar.gz HTTP/2
> Host: download.maxmind.com
> User-Agent: curl/8.5.0
> Accept: */*
>
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [230 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [230 bytes data]
* old SSL session ID is stale, removing
{ [5 bytes data]
< HTTP/2 401
< date: Tue, 13 Feb 2024 22:35:44 GMT
< content-type: text/plain;charset=UTF-8
< content-length: 20
< cache-control: private, max-age=0
< expires: Tue, 13 Feb 2024 22:35:44 GMT
< server: cloudflare
< cf-ray: 85508bd04d207da1-TLV
<
{ [20 bytes data]
100    20  100    20    0     0     56      0 --:--:-- --:--:-- --:--:--    56
* Connection #0 to host download.maxmind.com left intact
root@7dd91951b61b:/# cd
root@7dd91951b61b:/root# cat justforfun.tar.gz
Invalid license key


</p>
</details>

**Comment by aptalca** [comment]
You're comparing apples and oranges. Do the things I asked above.

**Comment by Or-azur** [comment]
docker exec swag cat /etc/libmaxminddb.cron.conf
# Database files to download
# MAXMINDDB_FILES="GeoLite2-City.mmdb"

# Database download directory
# MAXMINDDB_URL="https://download.maxmind.com/app/geoip_download"

# Local target directory
# MAXMINDDB_LIBDIR="/var/lib/libmaxminddb"

# MaxMind license key, can be retrieved through https://www.maxmind.com/en/geolite2/signup
MAXMINDDB_LICENSE_KEY="0UXXXXXXXXXXXXXXXXXXXXXXX6XBgYD_mmk"

the X's are for hidden

everything is good with icontainer_name: geoipupdate

**Comment by dmakhalfeh** [comment]
Today i also tried to install it a new portainer machine from scratch also didn't work ! also my main machine still not working , also fail2ban not blocking with this error :
2024-02-14 13:56:59,983 fail2ban.actions        [478]: ERROR   Failed to execute ban jail 'nginx-unauthorized' action 'iptables-allports' info 'ActionInfo({'ip': '198.20.69.98', 'family': 'inet4', 'fid': <function Actions.ActionInfo.<lambda> at 0x7f94b05e40>, 'raw-ticket': <function Actions.ActionInfo.<lambda> at 0x7f94b065c0>})': Error starting action Jail('nginx-unauthorized')/iptables-allports: 'Script error'
i didn't touch actions at all !

**Comment by aptalca** [comment]
We're having failure to communicate and this issue has gone off the rails.

Closing.

If you're still having issues with the maxmind mod, you can open a new issue but make sure to include a full compose yaml or docker run for SWAG, along with a full container log.

**Comment by vvoicehovics** [comment]
@aptalca i got the same issue. I think might be related to redirects

curl  "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key={MY_KEY}&suffix=tar.gz" -o "./GeoLite2-City.mmdb.tar.gz" gives me empty tar ---> tar: short read

curl -L  "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key={MY_KEY}&suffix=tar.gz" -o "./GeoLite2-City.mmdb.tar.gz" works


libmaxminddb-1.7.1-r0 -- i had issue in
libmaxminddb-1.9.1-r0 -- in this version -L flag is in the script
