### ISSUE TITLE
Create branch: nextcloud-notify-push

### ISSUE THREAD

**Issue by melonarc** [linuxserver/docker-mods#845]
### Is this a new feature request?

- [X] I have searched the existing issues

### Name of mod

nextcloud-notify-push

### Wanted change

Request to create a new Branch: nextcloud-notify-push.

### Reason for change

I would like to contribute a new Docker mod for the nextcloud notify/client push app. 

### Proposed code change

The repo: https://github.com/melonarc/docker-mods/tree/nextcloud-notify-push
Test image: ghcr.io/melonarc/nextcloud-notify-push-moddev

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-mods/tree/nextcloud-notify-push
