### ISSUE TITLE
Add pnpm mod for code-server

### ISSUE THREAD

**Issue by phyesix** [linuxserver/docker-mods#855]
### Is this a new feature request?

- [X] I have searched the existing issues

### Name of mod

code-server

### Wanted change

I created a mod for code-server that installs pnpm for node.js. 

Here is my repo: https://github.com/phyesix/docker-mods/tree/pnpm

Please create the branch **code-server-pnpm** so that I can create a PR for the mod.

### Reason for change

add pnpm

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-mods/tree/code-server-pnpm
