### ISSUE TITLE
[FEAT] php-cli for code-server (new branch request)

### ISSUE THREAD

**Issue by Saij** [linuxserver/docker-mods#863]
### Is this a new feature request?

- [X] I have searched the existing issues

### Name of mod

php-cli

### Wanted change

Please create a branch for a new mod php-cli (code-server-php-cli)

### Reason for change

I created a mod for the code-server image which installs php-cli, PHP extensions and composer and therefore enables PHP development.

My repository can be found at https://github.com/Saij/docker-mods/tree/code-server-php-cli

**Comment by Roxedus** [comment]
https://github.com/linuxserver/docker-mods/tree/code-server-php-cli

**Comment by Saij** [comment]
Thx
