### ISSUE TITLE
[FEAT] rrsync (double r!) - Easier restriction of rsync commands.

### ISSUE THREAD

**Issue by Xyaren** [linuxserver/docker-mods#870]
### Is this a new feature request?

- [X] I have searched the existing issues

### Name of mod

linuxserver/mods:openssh-server-rsync

### Wanted change

I found https://download.samba.org/pub/rsync/rrsync.1 which is kindof part or rsync but also not...
I wonder if this can be included for easier and better restriction of rsync commands.

### Reason for change

I am running linuxserver/mods:openssh-server-rsync for syncing into a folder from a remote.
I am trying to restrict this operation as much as possible.

**Comment by aptalca** [comment]
you can use this mod to install that package (it's available in the alpine repo as `rrsync`): https://github.com/linuxserver/docker-mods/tree/universal-package-install

**Comment by Xyaren** [comment]
Perfect, thank you.
