### ISSUE TITLE
fatal: during dependency resolution for service

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [linuxserver/docker-mods#896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Name of mod

swag-auto-proxy-setup

### Name of base container

swag

### Current Behavior

swag don't init. 

### Steps To Reproduce

Start container with mod enabled, wait for fail to start swag.

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
docker compose
```

### Container logs

```bash
[mod-init] (DEBUG) Registry='lscr.io', Repository='linuxserver', Image='linuxserver/mods', Tag='swag-auto-proxy'
[mod-init] Adding linuxserver/mods:swag-auto-proxy to container
[mod-init] (DEBUG) Using https://ghcr.io/token?scope=repository%3Alinuxserver%2Fmods%3Apull as auth endpoint
[mod-init] (DEBUG) Arch detected as amd64
[mod-init] Downloading linuxserver/mods:swag-auto-proxy from lscr.io
[mod-init] Installing linuxserver/mods:swag-auto-proxy
[mod-init] linuxserver/mods:swag-auto-proxy applied to container
s6-rc-compile: fatal: during dependency resolution for service init-mod-swag-auto-proxy-setup: undefined service name init-mod-universal-docker-setup
```

**Comment by thespad** [comment]
From https://github.com/linuxserver/docker-mods/tree/swag-auto-proxy?tab=readme-ov-file#requirements

> This mod needs the [universal-docker mod](https://github.com/linuxserver/docker-mods/tree/universal-docker) installed and set up with either mapping docker.sock or setting the environment variable DOCKER_HOST=remoteaddress.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Yes, of course I checked the match requirements beforehand to open the issue and checking both mods are enabled.

`- DOCKER_MODS=` includes
`linuxserver/mods:universal-docker|linuxserver/mods:swag-auto-proxy`

`DOCKER_HOST `uses socket-proxy via linuxserver/socket-proxy

Please don't close unsolved issues.

**Comment by j0nnymoe** [comment]
We get asked this question a lot so based on the information you provided in the issue, we responded appropriately. 

If you'd filled in the issue template correctly from the start, we would've known that you'd had the other docker mod already set.

**Comment by gdelazzer** [comment]
> Yes, of course I checked the match requirements beforehand to open the issue and checking both mods are enabled.
> 
> `- DOCKER_MODS=` includes `linuxserver/mods:universal-docker|linuxserver/mods:swag-auto-proxy`
> 
> `DOCKER_HOST `uses socket-proxy via linuxserver/socket-proxy
> 
> Please don't close unsolved issues.

Have you been able to solve this issue? After more than a year of running it without issue I am now facing the same problem as you...
