### ISSUE TITLE
New mod not found on Github registry

### ISSUE THREAD

**Issue by zJudGenie** [linuxserver/docker-mods#913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Name of mod

universal-openssh

### Name of base container

minetest

### Current Behavior

I've built a new docker mod that I need, and I decided to publish it only on my GitHub as I don't have the time to maintain it, you can find it here https://github.com/zJudGenie/docker-mods/tree/universal-openssh I followed the guide and I published it to this package https://github.com/zJudGenie/docker-mods/pkgs/container/docker-mods but when I use it in `DOCKER_MODS=zjudgenie/docker-mods:universal-openssh` I get this error
```
[mod-init] Adding zjudgenie/docker-mods:universal-openssh to container
[mod-init] (ERROR) zjudgenie/docker-mods:universal-openssh digest could not be fetched from registry-1.docker.io
```

I tried to join the Discord server but I didn't manage to get my phone number verified :(

### Expected Behavior

The docker mod is loaded into the container

### Steps To Reproduce

Pick whatever image you want and try to add this to your env variables 
`DOCKER_MODS=zjudgenie/docker-mods:universal-openssh`

### Environment

```markdown
OS: Ubuntu 20.04
```

### CPU architecture

x86-64

### Docker creation

```bash
services:
  minetest:
    image: lscr.io/linuxserver/minetest:5.8.0
    container_name: minetest-empty
    environment:
      - PUID=1224
      - PGID=1224
      - TZ=Europe/Rome 
      - DOCKER_MODS=linuxserver/mods:universal-package-install|linuxserver/mods:universal-cron|zjudgenie/docker-mods:universal-openssh
      - INSTALL_PACKAGES=git|git-lfs|tmux|vim
    volumes:
      - ./data:/config/.minetest
    ports:
      - 31234:30000/udp
    restart: unless-stopped
```

### Container logs

```bash
minetest-empty  | [mod-init] Running Docker Modification Logic
minetest-empty  | [mod-init] Adding linuxserver/mods:universal-package-install to container
minetest-empty  | [mod-init] linuxserver/mods:universal-package-install at sha256:179666823e425c84f903183aa0b76eb4fe6ce386fdeb55ca85b56b7791669140 has been previously applied skipping
minetest-empty  | [mod-init] Adding linuxserver/mods:universal-cron to container
minetest-empty  | [mod-init] linuxserver/mods:universal-cron at sha256:76cda2de7139afa9c3727602470e028b6ea64967f44fc30691f52e801e84e7b3 has been previously applied skipping
minetest-empty  | [mod-init] Adding zjudgenie/docker-mods:universal-openssh to container
minetest-empty  | [mod-init] (ERROR) zjudgenie/docker-mods:universal-openssh digest could not be fetched from registry-1.docker.io
```

**Comment by Roxedus** [comment]
DOCKER_MODS=ghcr.io/zjudgenie/docker-mods:universal-openssh

**Comment by zJudGenie** [comment]
Thank you, it worked :)
