### ISSUE TITLE
[FEAT] Create new branch:  MediaInfo Plugin for Emby

### ISSUE THREAD

**Issue by DaveO16176** [linuxserver/docker-mods#923]
### Is this a new feature request?

- [X] I have searched the existing issues

### Name of mod

mediainfo-plugin

### Wanted change

Please create a branch for a new docker-mod for Emby:  emby-mediainfo-plugin

### Reason for change

Emby's MediaInfo plugin requires additional packages and files to be installed.  The docker-mod only supports amd64 because the BIF Tool is only available for Linux x86 64-bit machines.

**Comment by Roxedus** [comment]
https://github.com/linuxserver/docker-mods/tree/emby-mediainfo-plugin :)

**Comment by DaveO16176** [comment]
Thanks.  I submitted PR [924](https://github.com/linuxserver/docker-mods/pull/924) and I've addressed all the comments on the PR.
