### ISSUE TITLE
[FEAT] Grammar fix in README

### ISSUE THREAD

**Issue by MarkNBroadhead** [linuxserver/docker-mods#928]
### Is this a new feature request?

- [X] I have searched the existing issues

### Name of mod

N/A

### Wanted change

Both instances of the word "it's" in the README.md should instead be "its".

I went to submit a PR, however, was instructed to instead open an issue by the PR template.

### Reason for change

Grammar is cool.

### Proposed code change

Change instances of "it's" to "its" in README.md.

**Comment by aptalca** [comment]
Thanks for the heads up. Please submit a PR and we'll merge it quickly.
