### ISSUE TITLE
Cutover from Dockerhub

### ISSUE THREAD

**Issue by thelamer** [linuxserver/docker-mods#93]
We need to change docs to reflect we recommend using github as a mod endpoint. Also need to change the endpoints in the baseimages to do some auto detection if starts with linuxserver in the string hit github.

**Comment by aptalca** [comment]
#95 for updating template (needs to be done last, after baseimages are pushed)

**Comment by aptalca** [comment]
This is now largely done, we just need to update the jenkins triggers to initiate github actions
