### ISSUE TITLE
[FEAT] Kubectl + Helm + Helmfile mod for code-server

### ISSUE THREAD

**Issue by GeiserX** [linuxserver/docker-mods#950]
### Is this a new feature request?

- [X] I have searched the existing issues

### Name of mod

I'd like to manage my small at-home infra through code-server and this includes a small Kubernetes cluster. 

### Wanted change

A new docker mod for Kubectl, Helm and Helmfile

### Reason for change

Currently I have to install Kubectl every time I update code-server, which is kind of a pain

**Comment by aptalca** [comment]
PRs welcome. Very few team members use k8s so we don't have the resources to create and test the mod
