### ISSUE TITLE
[FEAT] Create new branch: Python3 with Poetry for code-server

### ISSUE THREAD

**Issue by howardt12345** [linuxserver/docker-mods#958]
### Is this a new feature request?

- [X] I have searched the existing issues

### Name of mod

`code-server-python3-poetry`

### Wanted change

Please create a new branch for `code-server-python3-poetry` 

### Reason for change

I wanted a version of the python3 mod with Poetry for dependency management

### Proposed code change

https://github.com/howardt12345/docker-mods/tree/code-server-python3poetry

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-mods/tree/code-server-python3-poetry

**Comment by howardt12345** [comment]
https://github.com/linuxserver/docker-mods/pull/959
