### ISSUE TITLE
[FEAT] Add Support for Remote Cache/Transcoding Directories Without Direct Mounting

### ISSUE THREAD

**Issue by pinchiguillo** [linuxserver/docker-mods#963]
### Is this a new feature request?

- [X] I have searched the existing issues

### Name of mod

jellyfin-rffmpeg

### Wanted change

I am currently setting up rffmpeg with Jellyfin in a Docker environment, and I encountered a limitation that could be addressed to improve the flexibility of remote transcoding setups.

The issue arises when the rffmpeg transcode server is located on a separate machine, which makes it impossible to mount the server directory directly into the Jellyfin container. For Jellyfin and rffmpeg to work properly in this scenario, both systems need to share access to certain directories, such as the /cache directory used by Jellyfin.

However, the current system seems to rely on direct mounting of remote directories (via Docker volumes), which can be challenging when dealing with remote servers.

### Reason for change

 It would be great if Jellyfin, in conjunction with rffmpeg, could support remote cache and transcoding directories without requiring direct mounting. Instead, implementing a networked solution (such as NFS, SMB, or other network file systems) natively within the container would allow users to configure Jellyfin and rffmpeg on separate machines more easily.

**Comment by aptalca** [comment]
The readme talks about it and links to a setup guide the upstream author maintains.

This mod is meant for remote server use. What your trying to accomplish is already how it's meant to work.
