### ISSUE TITLE
[FEAT] Provide separate jellyfin-opencl-intel mods for legacy and non-legacy Intel iGPUs

### ISSUE THREAD

**Issue by solidsnake1298** [linuxserver/docker-mods#971]
### Is this a new feature request?

- [X] I have searched the existing issues

### Name of mod

jellyfin-opencl-intel

### Wanted change

Intel has dropped OpenCL support for pre-Tigerlake CPUs.  Intel compute packages newer than 24.35.30872.22 will no longer support HD/UHD 5XX and 6XX iGPUs.

Specifying a version is an option, but perhaps having a "legacy" opencl mod would be more clean, in addition to stating in the mod's documentation that this is happening.

```jellyfin-opencl-intel-legacy``` or something like that.  Which is pinned to 24.35.30872.22.

https://github.com/intel/compute-runtime/blob/master/LEGACY_PLATFORMS.md

### Reason for change

Intel dropped support for pre-Tigerlake CPUs for Intel compute packages newer than 24.35.30872.22.

### Proposed code change

Create a new docker hub tag for that is pinned to an Intel compute version that supports legacy Intel CPUs.

```jellyfin-opencl-intel-legacy``` is pinned to version 24.35.30872.22.

**Comment by aptalca** [comment]
This mod has versioned releases. Users can pull a version tag that is compatible with their device.

Intel drops support for architectures all the time. What you consider legacy may be different than someone else's legacy. Legacy is a moving target.

**Comment by solidsnake1298** [comment]
Intel calls them legacy platforms.

![Screenshot_20241030-232650.png](https://github.com/user-attachments/assets/6b878919-1b75-4624-90ee-d2ebba7504f1)

**Comment by aptalca** [comment]
Yes, and when Intel deprecates support for a newer architecture down the line, the version pushed as legacy then will be newer than your legacy device supports. That's what I mean by `legacy is a moving target`. It contains a list of various architectures, not a single one.

> if your CPU is 10th gen core and older

That's a much better solution to list in the readme which gens are supported up to which version.

We do something similar for the various Intel drivers in our ffmpeg image: https://github.com/linuxserver/docker-ffmpeg?tab=readme-ov-file#included-intel-drivers-latest-versions-compiled

PRs welcome

**Comment by solidsnake1298** [comment]
https://github.com/linuxserver/docker-mods/pull/973

**Comment by quietsy** [comment]
@solidsnake1298 Can you please test the following tag `linuxserver/mods:pull_request_996` and verify that opencl works on legacy intel cpus?
<https://github.com/linuxserver/docker-mods/pull/996>

**Comment by solidsnake1298** [comment]
> ~@solidsnake1298 Can you please test the following tag `linuxserver/mods:pull_request_996` and verify that opencl works on legacy intel cpus?~ #996 Has been pushed, you can try the latest build.

Unfortunately, I do not have a "legacy" CPU to test with.
