### ISSUE TITLE
[FEAT] striptracks - only keep forced subtitles

### ISSUE THREAD

**Issue by fatSquirrel42** [linuxserver/docker-mods#978]
### Is this a new feature request?

- [X] I have searched the existing issues

### Name of mod

striptracks

### Wanted change

New command-line argument with which you can control whether you only want to keep subtitles that are “forced” or all subtitles.
The flag could work on a language-specific or global basis.

### Reason for change

Often there are forced subtitles in the same language as the audio track, which serve to give the viewer further context.
I think it would add value if you could use a new flag to only keep subtitles that are marked as forced.

Personally, for example, I currently only keep English and German audio tracks because I understand them. In order to get the right subtitles, I now also keep all English and German subtitles. It would be enough for me if I only kept the forced subtitles.

**Comment by Roxedus** [comment]
Report to project, https://github.com/TheCaptain989/radarr-striptracks
